#pragma once
// This file is auto-generated by scripts/gen_asset_registries.py
// Do not modify this file directly. Run the script to regenerate.

#include "engine/resource/AssetRegistry.hpp"
#include <array>

using namespace entt::literals;

namespace assets::buffs {

    namespace general {
        inline constexpr TextureAsset all_stats = { "buff_all_stats"_hs, "assets/textures/icons/buffs/all_stats.png" };
        inline constexpr TextureAsset attack_speed = { "buff_attack_speed"_hs, "assets/textures/icons/buffs/attack_speed.png" };
        inline constexpr TextureAsset crit_chance = { "buff_crit_chance"_hs, "assets/textures/icons/buffs/crit_chance.png" };
        inline constexpr TextureAsset dexterity = { "buff_dexterity"_hs, "assets/textures/icons/buffs/dexterity.png" };
        inline constexpr TextureAsset flat_armor = { "buff_flat_armor"_hs, "assets/textures/icons/buffs/flat_armor.png" };
        inline constexpr TextureAsset flat_fire = { "buff_flat_fire"_hs, "assets/textures/icons/buffs/flat_fire.png" };
        inline constexpr TextureAsset flat_health = { "buff_flat_health"_hs, "assets/textures/icons/buffs/flat_health.png" };
        inline constexpr TextureAsset flat_mana = { "buff_flat_mana"_hs, "assets/textures/icons/buffs/flat_mana.png" };
        inline constexpr TextureAsset flat_phys = { "buff_flat_phys"_hs, "assets/textures/icons/buffs/flat_phys.png" };
        inline constexpr TextureAsset health_regen = { "buff_health_regen"_hs, "assets/textures/icons/buffs/health_regen.png" };
        inline constexpr TextureAsset intelligence = { "buff_intelligence"_hs, "assets/textures/icons/buffs/intelligence.png" };
        inline constexpr TextureAsset mana_regen = { "buff_mana_regen"_hs, "assets/textures/icons/buffs/mana_regen.png" };
        inline constexpr TextureAsset melee_phys_dmg = { "buff_melee_phys_dmg"_hs, "assets/textures/icons/buffs/melee_phys_dmg.png" };
        inline constexpr TextureAsset move_speed = { "buff_move_speed"_hs, "assets/textures/icons/buffs/move_speed.png" };
        inline constexpr TextureAsset pct_armor = { "buff_pct_armor"_hs, "assets/textures/icons/buffs/pct_armor.png" };
        inline constexpr TextureAsset pct_fire = { "buff_pct_fire"_hs, "assets/textures/icons/buffs/pct_fire.png" };
        inline constexpr TextureAsset pct_health_regen = { "buff_pct_health_regen"_hs, "assets/textures/icons/buffs/pct_health_regen.png" };
        inline constexpr TextureAsset pct_light = { "buff_pct_light"_hs, "assets/textures/icons/buffs/pct_light.png" };
        inline constexpr TextureAsset pct_mana_regen = { "buff_pct_mana_regen"_hs, "assets/textures/icons/buffs/pct_mana_regen.png" };
        inline constexpr TextureAsset pct_phys = { "buff_pct_phys"_hs, "assets/textures/icons/buffs/pct_phys.png" };
        inline constexpr TextureAsset projectile_attack_speed = { "buff_projectile_attack_speed"_hs, "assets/textures/icons/buffs/projectile_attack_speed.png" };
        inline constexpr TextureAsset resist_all = { "buff_resist_all"_hs, "assets/textures/icons/buffs/resist_all.png" };
        inline constexpr TextureAsset resist_cold = { "buff_resist_cold"_hs, "assets/textures/icons/buffs/resist_cold.png" };
        inline constexpr TextureAsset resist_fire = { "buff_resist_fire"_hs, "assets/textures/icons/buffs/resist_fire.png" };
        inline constexpr TextureAsset resist_lightning = { "buff_resist_lightning"_hs, "assets/textures/icons/buffs/resist_lightning.png" };
        inline constexpr TextureAsset spell_crit = { "buff_spell_crit"_hs, "assets/textures/icons/buffs/spell_crit.png" };
        inline constexpr TextureAsset strength = { "buff_strength"_hs, "assets/textures/icons/buffs/strength.png" };
        inline constexpr TextureAsset vitality = { "buff_vitality"_hs, "assets/textures/icons/buffs/vitality.png" };

        constexpr std::array<const TextureAsset*, 28> All = {
            &all_stats,
            &attack_speed,
            &crit_chance,
            &dexterity,
            &flat_armor,
            &flat_fire,
            &flat_health,
            &flat_mana,
            &flat_phys,
            &health_regen,
            &intelligence,
            &mana_regen,
            &melee_phys_dmg,
            &move_speed,
            &pct_armor,
            &pct_fire,
            &pct_health_regen,
            &pct_light,
            &pct_mana_regen,
            &pct_phys,
            &projectile_attack_speed,
            &resist_all,
            &resist_cold,
            &resist_fire,
            &resist_lightning,
            &spell_crit,
            &strength,
            &vitality
        };
    } // namespace general

} // namespace assets::buffs