#pragma once
// This file is auto-generated by scripts/gen_equipment_registry.py
// Do not modify this file directly. Run the script to regenerate.

#include "engine/resource/AssetRegistry.hpp"
#include <array>
#include <span>

using namespace entt::literals;

namespace assets::equipment {

    namespace amulet {
        constexpr TextureAsset amulet_0 = { "equip_amulet_amulet_0"_hs, "assets/textures/equipment/amulet/amulet_0.png" };
        constexpr TextureAsset amulet_1 = { "equip_amulet_amulet_1"_hs, "assets/textures/equipment/amulet/amulet_1.png" };
        constexpr TextureAsset amulet_10 = { "equip_amulet_amulet_10"_hs, "assets/textures/equipment/amulet/amulet_10.png" };
        constexpr TextureAsset amulet_11 = { "equip_amulet_amulet_11"_hs, "assets/textures/equipment/amulet/amulet_11.png" };
        constexpr TextureAsset amulet_12 = { "equip_amulet_amulet_12"_hs, "assets/textures/equipment/amulet/amulet_12.png" };
        constexpr TextureAsset amulet_13 = { "equip_amulet_amulet_13"_hs, "assets/textures/equipment/amulet/amulet_13.png" };
        constexpr TextureAsset amulet_14 = { "equip_amulet_amulet_14"_hs, "assets/textures/equipment/amulet/amulet_14.png" };
        constexpr TextureAsset amulet_15 = { "equip_amulet_amulet_15"_hs, "assets/textures/equipment/amulet/amulet_15.png" };
        constexpr TextureAsset amulet_16 = { "equip_amulet_amulet_16"_hs, "assets/textures/equipment/amulet/amulet_16.png" };
        constexpr TextureAsset amulet_17 = { "equip_amulet_amulet_17"_hs, "assets/textures/equipment/amulet/amulet_17.png" };
        constexpr TextureAsset amulet_18 = { "equip_amulet_amulet_18"_hs, "assets/textures/equipment/amulet/amulet_18.png" };
        constexpr TextureAsset amulet_19 = { "equip_amulet_amulet_19"_hs, "assets/textures/equipment/amulet/amulet_19.png" };
        constexpr TextureAsset amulet_2 = { "equip_amulet_amulet_2"_hs, "assets/textures/equipment/amulet/amulet_2.png" };
        constexpr TextureAsset amulet_20 = { "equip_amulet_amulet_20"_hs, "assets/textures/equipment/amulet/amulet_20.png" };
        constexpr TextureAsset amulet_21 = { "equip_amulet_amulet_21"_hs, "assets/textures/equipment/amulet/amulet_21.png" };
        constexpr TextureAsset amulet_22 = { "equip_amulet_amulet_22"_hs, "assets/textures/equipment/amulet/amulet_22.png" };
        constexpr TextureAsset amulet_23 = { "equip_amulet_amulet_23"_hs, "assets/textures/equipment/amulet/amulet_23.png" };
        constexpr TextureAsset amulet_3 = { "equip_amulet_amulet_3"_hs, "assets/textures/equipment/amulet/amulet_3.png" };
        constexpr TextureAsset amulet_4 = { "equip_amulet_amulet_4"_hs, "assets/textures/equipment/amulet/amulet_4.png" };
        constexpr TextureAsset amulet_5 = { "equip_amulet_amulet_5"_hs, "assets/textures/equipment/amulet/amulet_5.png" };
        constexpr TextureAsset amulet_6 = { "equip_amulet_amulet_6"_hs, "assets/textures/equipment/amulet/amulet_6.png" };
        constexpr TextureAsset amulet_7 = { "equip_amulet_amulet_7"_hs, "assets/textures/equipment/amulet/amulet_7.png" };
        constexpr TextureAsset amulet_8 = { "equip_amulet_amulet_8"_hs, "assets/textures/equipment/amulet/amulet_8.png" };
        constexpr TextureAsset amulet_9 = { "equip_amulet_amulet_9"_hs, "assets/textures/equipment/amulet/amulet_9.png" };

        constexpr std::array<TextureAsset, 24> All = {
            amulet_0,
            amulet_1,
            amulet_10,
            amulet_11,
            amulet_12,
            amulet_13,
            amulet_14,
            amulet_15,
            amulet_16,
            amulet_17,
            amulet_18,
            amulet_19,
            amulet_2,
            amulet_20,
            amulet_21,
            amulet_22,
            amulet_23,
            amulet_3,
            amulet_4,
            amulet_5,
            amulet_6,
            amulet_7,
            amulet_8,
            amulet_9
        };
    }

    namespace axe {
        constexpr TextureAsset axe_0 = { "equip_axe_axe_0"_hs, "assets/textures/equipment/axe/axe_0.png" };
        constexpr TextureAsset axe_1 = { "equip_axe_axe_1"_hs, "assets/textures/equipment/axe/axe_1.png" };
        constexpr TextureAsset axe_10 = { "equip_axe_axe_10"_hs, "assets/textures/equipment/axe/axe_10.png" };
        constexpr TextureAsset axe_11 = { "equip_axe_axe_11"_hs, "assets/textures/equipment/axe/axe_11.png" };
        constexpr TextureAsset axe_12 = { "equip_axe_axe_12"_hs, "assets/textures/equipment/axe/axe_12.png" };
        constexpr TextureAsset axe_13 = { "equip_axe_axe_13"_hs, "assets/textures/equipment/axe/axe_13.png" };
        constexpr TextureAsset axe_14 = { "equip_axe_axe_14"_hs, "assets/textures/equipment/axe/axe_14.png" };
        constexpr TextureAsset axe_15 = { "equip_axe_axe_15"_hs, "assets/textures/equipment/axe/axe_15.png" };
        constexpr TextureAsset axe_16 = { "equip_axe_axe_16"_hs, "assets/textures/equipment/axe/axe_16.png" };
        constexpr TextureAsset axe_17 = { "equip_axe_axe_17"_hs, "assets/textures/equipment/axe/axe_17.png" };
        constexpr TextureAsset axe_18 = { "equip_axe_axe_18"_hs, "assets/textures/equipment/axe/axe_18.png" };
        constexpr TextureAsset axe_2 = { "equip_axe_axe_2"_hs, "assets/textures/equipment/axe/axe_2.png" };
        constexpr TextureAsset axe_3 = { "equip_axe_axe_3"_hs, "assets/textures/equipment/axe/axe_3.png" };
        constexpr TextureAsset axe_4 = { "equip_axe_axe_4"_hs, "assets/textures/equipment/axe/axe_4.png" };
        constexpr TextureAsset axe_5 = { "equip_axe_axe_5"_hs, "assets/textures/equipment/axe/axe_5.png" };
        constexpr TextureAsset axe_6 = { "equip_axe_axe_6"_hs, "assets/textures/equipment/axe/axe_6.png" };
        constexpr TextureAsset axe_7 = { "equip_axe_axe_7"_hs, "assets/textures/equipment/axe/axe_7.png" };
        constexpr TextureAsset axe_8 = { "equip_axe_axe_8"_hs, "assets/textures/equipment/axe/axe_8.png" };
        constexpr TextureAsset axe_9 = { "equip_axe_axe_9"_hs, "assets/textures/equipment/axe/axe_9.png" };

        constexpr std::array<TextureAsset, 19> All = {
            axe_0,
            axe_1,
            axe_10,
            axe_11,
            axe_12,
            axe_13,
            axe_14,
            axe_15,
            axe_16,
            axe_17,
            axe_18,
            axe_2,
            axe_3,
            axe_4,
            axe_5,
            axe_6,
            axe_7,
            axe_8,
            axe_9
        };
    }

    namespace boots {
        constexpr TextureAsset boots_0 = { "equip_boots_boots_0"_hs, "assets/textures/equipment/boots/boots_0.png" };
        constexpr TextureAsset boots_1 = { "equip_boots_boots_1"_hs, "assets/textures/equipment/boots/boots_1.png" };
        constexpr TextureAsset boots_10 = { "equip_boots_boots_10"_hs, "assets/textures/equipment/boots/boots_10.png" };
        constexpr TextureAsset boots_11 = { "equip_boots_boots_11"_hs, "assets/textures/equipment/boots/boots_11.png" };
        constexpr TextureAsset boots_12 = { "equip_boots_boots_12"_hs, "assets/textures/equipment/boots/boots_12.png" };
        constexpr TextureAsset boots_2 = { "equip_boots_boots_2"_hs, "assets/textures/equipment/boots/boots_2.png" };
        constexpr TextureAsset boots_3 = { "equip_boots_boots_3"_hs, "assets/textures/equipment/boots/boots_3.png" };
        constexpr TextureAsset boots_4 = { "equip_boots_boots_4"_hs, "assets/textures/equipment/boots/boots_4.png" };
        constexpr TextureAsset boots_5 = { "equip_boots_boots_5"_hs, "assets/textures/equipment/boots/boots_5.png" };
        constexpr TextureAsset boots_6 = { "equip_boots_boots_6"_hs, "assets/textures/equipment/boots/boots_6.png" };
        constexpr TextureAsset boots_7 = { "equip_boots_boots_7"_hs, "assets/textures/equipment/boots/boots_7.png" };
        constexpr TextureAsset boots_8 = { "equip_boots_boots_8"_hs, "assets/textures/equipment/boots/boots_8.png" };
        constexpr TextureAsset boots_9 = { "equip_boots_boots_9"_hs, "assets/textures/equipment/boots/boots_9.png" };

        constexpr std::array<TextureAsset, 13> All = {
            boots_0,
            boots_1,
            boots_10,
            boots_11,
            boots_12,
            boots_2,
            boots_3,
            boots_4,
            boots_5,
            boots_6,
            boots_7,
            boots_8,
            boots_9
        };
    }

    namespace chest {
        constexpr TextureAsset chest_0 = { "equip_chest_chest_0"_hs, "assets/textures/equipment/chest/chest_0.png" };
        constexpr TextureAsset chest_1 = { "equip_chest_chest_1"_hs, "assets/textures/equipment/chest/chest_1.png" };
        constexpr TextureAsset chest_10 = { "equip_chest_chest_10"_hs, "assets/textures/equipment/chest/chest_10.png" };
        constexpr TextureAsset chest_11 = { "equip_chest_chest_11"_hs, "assets/textures/equipment/chest/chest_11.png" };
        constexpr TextureAsset chest_2 = { "equip_chest_chest_2"_hs, "assets/textures/equipment/chest/chest_2.png" };
        constexpr TextureAsset chest_3 = { "equip_chest_chest_3"_hs, "assets/textures/equipment/chest/chest_3.png" };
        constexpr TextureAsset chest_4 = { "equip_chest_chest_4"_hs, "assets/textures/equipment/chest/chest_4.png" };
        constexpr TextureAsset chest_5 = { "equip_chest_chest_5"_hs, "assets/textures/equipment/chest/chest_5.png" };
        constexpr TextureAsset chest_6 = { "equip_chest_chest_6"_hs, "assets/textures/equipment/chest/chest_6.png" };
        constexpr TextureAsset chest_7 = { "equip_chest_chest_7"_hs, "assets/textures/equipment/chest/chest_7.png" };
        constexpr TextureAsset chest_8 = { "equip_chest_chest_8"_hs, "assets/textures/equipment/chest/chest_8.png" };
        constexpr TextureAsset chest_9 = { "equip_chest_chest_9"_hs, "assets/textures/equipment/chest/chest_9.png" };

        constexpr std::array<TextureAsset, 12> All = {
            chest_0,
            chest_1,
            chest_10,
            chest_11,
            chest_2,
            chest_3,
            chest_4,
            chest_5,
            chest_6,
            chest_7,
            chest_8,
            chest_9
        };
    }

    namespace dagger {
        constexpr TextureAsset dagger_0 = { "equip_dagger_dagger_0"_hs, "assets/textures/equipment/dagger/dagger_0.png" };
        constexpr TextureAsset dagger_1 = { "equip_dagger_dagger_1"_hs, "assets/textures/equipment/dagger/dagger_1.png" };
        constexpr TextureAsset dagger_10 = { "equip_dagger_dagger_10"_hs, "assets/textures/equipment/dagger/dagger_10.png" };
        constexpr TextureAsset dagger_11 = { "equip_dagger_dagger_11"_hs, "assets/textures/equipment/dagger/dagger_11.png" };
        constexpr TextureAsset dagger_12 = { "equip_dagger_dagger_12"_hs, "assets/textures/equipment/dagger/dagger_12.png" };
        constexpr TextureAsset dagger_13 = { "equip_dagger_dagger_13"_hs, "assets/textures/equipment/dagger/dagger_13.png" };
        constexpr TextureAsset dagger_14 = { "equip_dagger_dagger_14"_hs, "assets/textures/equipment/dagger/dagger_14.png" };
        constexpr TextureAsset dagger_15 = { "equip_dagger_dagger_15"_hs, "assets/textures/equipment/dagger/dagger_15.png" };
        constexpr TextureAsset dagger_16 = { "equip_dagger_dagger_16"_hs, "assets/textures/equipment/dagger/dagger_16.png" };
        constexpr TextureAsset dagger_17 = { "equip_dagger_dagger_17"_hs, "assets/textures/equipment/dagger/dagger_17.png" };
        constexpr TextureAsset dagger_18 = { "equip_dagger_dagger_18"_hs, "assets/textures/equipment/dagger/dagger_18.png" };
        constexpr TextureAsset dagger_19 = { "equip_dagger_dagger_19"_hs, "assets/textures/equipment/dagger/dagger_19.png" };
        constexpr TextureAsset dagger_2 = { "equip_dagger_dagger_2"_hs, "assets/textures/equipment/dagger/dagger_2.png" };
        constexpr TextureAsset dagger_20 = { "equip_dagger_dagger_20"_hs, "assets/textures/equipment/dagger/dagger_20.png" };
        constexpr TextureAsset dagger_21 = { "equip_dagger_dagger_21"_hs, "assets/textures/equipment/dagger/dagger_21.png" };
        constexpr TextureAsset dagger_22 = { "equip_dagger_dagger_22"_hs, "assets/textures/equipment/dagger/dagger_22.png" };
        constexpr TextureAsset dagger_3 = { "equip_dagger_dagger_3"_hs, "assets/textures/equipment/dagger/dagger_3.png" };
        constexpr TextureAsset dagger_4 = { "equip_dagger_dagger_4"_hs, "assets/textures/equipment/dagger/dagger_4.png" };
        constexpr TextureAsset dagger_5 = { "equip_dagger_dagger_5"_hs, "assets/textures/equipment/dagger/dagger_5.png" };
        constexpr TextureAsset dagger_6 = { "equip_dagger_dagger_6"_hs, "assets/textures/equipment/dagger/dagger_6.png" };
        constexpr TextureAsset dagger_7 = { "equip_dagger_dagger_7"_hs, "assets/textures/equipment/dagger/dagger_7.png" };
        constexpr TextureAsset dagger_8 = { "equip_dagger_dagger_8"_hs, "assets/textures/equipment/dagger/dagger_8.png" };
        constexpr TextureAsset dagger_9 = { "equip_dagger_dagger_9"_hs, "assets/textures/equipment/dagger/dagger_9.png" };

        constexpr std::array<TextureAsset, 23> All = {
            dagger_0,
            dagger_1,
            dagger_10,
            dagger_11,
            dagger_12,
            dagger_13,
            dagger_14,
            dagger_15,
            dagger_16,
            dagger_17,
            dagger_18,
            dagger_19,
            dagger_2,
            dagger_20,
            dagger_21,
            dagger_22,
            dagger_3,
            dagger_4,
            dagger_5,
            dagger_6,
            dagger_7,
            dagger_8,
            dagger_9
        };
    }

    namespace gauntlets {
        constexpr TextureAsset gauntlets_0 = { "equip_gauntlets_gauntlets_0"_hs, "assets/textures/equipment/gauntlets/gauntlets_0.png" };
        constexpr TextureAsset gauntlets_1 = { "equip_gauntlets_gauntlets_1"_hs, "assets/textures/equipment/gauntlets/gauntlets_1.png" };
        constexpr TextureAsset gauntlets_10 = { "equip_gauntlets_gauntlets_10"_hs, "assets/textures/equipment/gauntlets/gauntlets_10.png" };
        constexpr TextureAsset gauntlets_11 = { "equip_gauntlets_gauntlets_11"_hs, "assets/textures/equipment/gauntlets/gauntlets_11.png" };
        constexpr TextureAsset gauntlets_12 = { "equip_gauntlets_gauntlets_12"_hs, "assets/textures/equipment/gauntlets/gauntlets_12.png" };
        constexpr TextureAsset gauntlets_13 = { "equip_gauntlets_gauntlets_13"_hs, "assets/textures/equipment/gauntlets/gauntlets_13.png" };
        constexpr TextureAsset gauntlets_14 = { "equip_gauntlets_gauntlets_14"_hs, "assets/textures/equipment/gauntlets/gauntlets_14.png" };
        constexpr TextureAsset gauntlets_15 = { "equip_gauntlets_gauntlets_15"_hs, "assets/textures/equipment/gauntlets/gauntlets_15.png" };
        constexpr TextureAsset gauntlets_16 = { "equip_gauntlets_gauntlets_16"_hs, "assets/textures/equipment/gauntlets/gauntlets_16.png" };
        constexpr TextureAsset gauntlets_2 = { "equip_gauntlets_gauntlets_2"_hs, "assets/textures/equipment/gauntlets/gauntlets_2.png" };
        constexpr TextureAsset gauntlets_3 = { "equip_gauntlets_gauntlets_3"_hs, "assets/textures/equipment/gauntlets/gauntlets_3.png" };
        constexpr TextureAsset gauntlets_4 = { "equip_gauntlets_gauntlets_4"_hs, "assets/textures/equipment/gauntlets/gauntlets_4.png" };
        constexpr TextureAsset gauntlets_5 = { "equip_gauntlets_gauntlets_5"_hs, "assets/textures/equipment/gauntlets/gauntlets_5.png" };
        constexpr TextureAsset gauntlets_6 = { "equip_gauntlets_gauntlets_6"_hs, "assets/textures/equipment/gauntlets/gauntlets_6.png" };
        constexpr TextureAsset gauntlets_7 = { "equip_gauntlets_gauntlets_7"_hs, "assets/textures/equipment/gauntlets/gauntlets_7.png" };
        constexpr TextureAsset gauntlets_8 = { "equip_gauntlets_gauntlets_8"_hs, "assets/textures/equipment/gauntlets/gauntlets_8.png" };
        constexpr TextureAsset gauntlets_9 = { "equip_gauntlets_gauntlets_9"_hs, "assets/textures/equipment/gauntlets/gauntlets_9.png" };

        constexpr std::array<TextureAsset, 17> All = {
            gauntlets_0,
            gauntlets_1,
            gauntlets_10,
            gauntlets_11,
            gauntlets_12,
            gauntlets_13,
            gauntlets_14,
            gauntlets_15,
            gauntlets_16,
            gauntlets_2,
            gauntlets_3,
            gauntlets_4,
            gauntlets_5,
            gauntlets_6,
            gauntlets_7,
            gauntlets_8,
            gauntlets_9
        };
    }

    namespace greatsword {
        constexpr TextureAsset greatsword_0 = { "equip_greatsword_greatsword_0"_hs, "assets/textures/equipment/greatsword/greatsword_0.png" };
        constexpr TextureAsset greatsword_1 = { "equip_greatsword_greatsword_1"_hs, "assets/textures/equipment/greatsword/greatsword_1.png" };
        constexpr TextureAsset greatsword_10 = { "equip_greatsword_greatsword_10"_hs, "assets/textures/equipment/greatsword/greatsword_10.png" };
        constexpr TextureAsset greatsword_11 = { "equip_greatsword_greatsword_11"_hs, "assets/textures/equipment/greatsword/greatsword_11.png" };
        constexpr TextureAsset greatsword_12 = { "equip_greatsword_greatsword_12"_hs, "assets/textures/equipment/greatsword/greatsword_12.png" };
        constexpr TextureAsset greatsword_13 = { "equip_greatsword_greatsword_13"_hs, "assets/textures/equipment/greatsword/greatsword_13.png" };
        constexpr TextureAsset greatsword_14 = { "equip_greatsword_greatsword_14"_hs, "assets/textures/equipment/greatsword/greatsword_14.png" };
        constexpr TextureAsset greatsword_2 = { "equip_greatsword_greatsword_2"_hs, "assets/textures/equipment/greatsword/greatsword_2.png" };
        constexpr TextureAsset greatsword_3 = { "equip_greatsword_greatsword_3"_hs, "assets/textures/equipment/greatsword/greatsword_3.png" };
        constexpr TextureAsset greatsword_4 = { "equip_greatsword_greatsword_4"_hs, "assets/textures/equipment/greatsword/greatsword_4.png" };
        constexpr TextureAsset greatsword_5 = { "equip_greatsword_greatsword_5"_hs, "assets/textures/equipment/greatsword/greatsword_5.png" };
        constexpr TextureAsset greatsword_6 = { "equip_greatsword_greatsword_6"_hs, "assets/textures/equipment/greatsword/greatsword_6.png" };
        constexpr TextureAsset greatsword_7 = { "equip_greatsword_greatsword_7"_hs, "assets/textures/equipment/greatsword/greatsword_7.png" };
        constexpr TextureAsset greatsword_8 = { "equip_greatsword_greatsword_8"_hs, "assets/textures/equipment/greatsword/greatsword_8.png" };
        constexpr TextureAsset greatsword_9 = { "equip_greatsword_greatsword_9"_hs, "assets/textures/equipment/greatsword/greatsword_9.png" };

        constexpr std::array<TextureAsset, 15> All = {
            greatsword_0,
            greatsword_1,
            greatsword_10,
            greatsword_11,
            greatsword_12,
            greatsword_13,
            greatsword_14,
            greatsword_2,
            greatsword_3,
            greatsword_4,
            greatsword_5,
            greatsword_6,
            greatsword_7,
            greatsword_8,
            greatsword_9
        };
    }

    namespace grimoire {
        constexpr TextureAsset grimoire_0 = { "equip_grimoire_grimoire_0"_hs, "assets/textures/equipment/grimoire/grimoire_0.png" };
        constexpr TextureAsset grimoire_1 = { "equip_grimoire_grimoire_1"_hs, "assets/textures/equipment/grimoire/grimoire_1.png" };
        constexpr TextureAsset grimoire_10 = { "equip_grimoire_grimoire_10"_hs, "assets/textures/equipment/grimoire/grimoire_10.png" };
        constexpr TextureAsset grimoire_11 = { "equip_grimoire_grimoire_11"_hs, "assets/textures/equipment/grimoire/grimoire_11.png" };
        constexpr TextureAsset grimoire_12 = { "equip_grimoire_grimoire_12"_hs, "assets/textures/equipment/grimoire/grimoire_12.png" };
        constexpr TextureAsset grimoire_13 = { "equip_grimoire_grimoire_13"_hs, "assets/textures/equipment/grimoire/grimoire_13.png" };
        constexpr TextureAsset grimoire_14 = { "equip_grimoire_grimoire_14"_hs, "assets/textures/equipment/grimoire/grimoire_14.png" };
        constexpr TextureAsset grimoire_15 = { "equip_grimoire_grimoire_15"_hs, "assets/textures/equipment/grimoire/grimoire_15.png" };
        constexpr TextureAsset grimoire_16 = { "equip_grimoire_grimoire_16"_hs, "assets/textures/equipment/grimoire/grimoire_16.png" };
        constexpr TextureAsset grimoire_17 = { "equip_grimoire_grimoire_17"_hs, "assets/textures/equipment/grimoire/grimoire_17.png" };
        constexpr TextureAsset grimoire_18 = { "equip_grimoire_grimoire_18"_hs, "assets/textures/equipment/grimoire/grimoire_18.png" };
        constexpr TextureAsset grimoire_19 = { "equip_grimoire_grimoire_19"_hs, "assets/textures/equipment/grimoire/grimoire_19.png" };
        constexpr TextureAsset grimoire_2 = { "equip_grimoire_grimoire_2"_hs, "assets/textures/equipment/grimoire/grimoire_2.png" };
        constexpr TextureAsset grimoire_3 = { "equip_grimoire_grimoire_3"_hs, "assets/textures/equipment/grimoire/grimoire_3.png" };
        constexpr TextureAsset grimoire_4 = { "equip_grimoire_grimoire_4"_hs, "assets/textures/equipment/grimoire/grimoire_4.png" };
        constexpr TextureAsset grimoire_5 = { "equip_grimoire_grimoire_5"_hs, "assets/textures/equipment/grimoire/grimoire_5.png" };
        constexpr TextureAsset grimoire_6 = { "equip_grimoire_grimoire_6"_hs, "assets/textures/equipment/grimoire/grimoire_6.png" };
        constexpr TextureAsset grimoire_7 = { "equip_grimoire_grimoire_7"_hs, "assets/textures/equipment/grimoire/grimoire_7.png" };
        constexpr TextureAsset grimoire_8 = { "equip_grimoire_grimoire_8"_hs, "assets/textures/equipment/grimoire/grimoire_8.png" };
        constexpr TextureAsset grimoire_9 = { "equip_grimoire_grimoire_9"_hs, "assets/textures/equipment/grimoire/grimoire_9.png" };

        constexpr std::array<TextureAsset, 20> All = {
            grimoire_0,
            grimoire_1,
            grimoire_10,
            grimoire_11,
            grimoire_12,
            grimoire_13,
            grimoire_14,
            grimoire_15,
            grimoire_16,
            grimoire_17,
            grimoire_18,
            grimoire_19,
            grimoire_2,
            grimoire_3,
            grimoire_4,
            grimoire_5,
            grimoire_6,
            grimoire_7,
            grimoire_8,
            grimoire_9
        };
    }

    namespace hammer {
        constexpr TextureAsset hammer_0 = { "equip_hammer_hammer_0"_hs, "assets/textures/equipment/hammer/hammer_0.png" };
        constexpr TextureAsset hammer_1 = { "equip_hammer_hammer_1"_hs, "assets/textures/equipment/hammer/hammer_1.png" };
        constexpr TextureAsset hammer_10 = { "equip_hammer_hammer_10"_hs, "assets/textures/equipment/hammer/hammer_10.png" };
        constexpr TextureAsset hammer_11 = { "equip_hammer_hammer_11"_hs, "assets/textures/equipment/hammer/hammer_11.png" };
        constexpr TextureAsset hammer_12 = { "equip_hammer_hammer_12"_hs, "assets/textures/equipment/hammer/hammer_12.png" };
        constexpr TextureAsset hammer_13 = { "equip_hammer_hammer_13"_hs, "assets/textures/equipment/hammer/hammer_13.png" };
        constexpr TextureAsset hammer_14 = { "equip_hammer_hammer_14"_hs, "assets/textures/equipment/hammer/hammer_14.png" };
        constexpr TextureAsset hammer_15 = { "equip_hammer_hammer_15"_hs, "assets/textures/equipment/hammer/hammer_15.png" };
        constexpr TextureAsset hammer_16 = { "equip_hammer_hammer_16"_hs, "assets/textures/equipment/hammer/hammer_16.png" };
        constexpr TextureAsset hammer_17 = { "equip_hammer_hammer_17"_hs, "assets/textures/equipment/hammer/hammer_17.png" };
        constexpr TextureAsset hammer_18 = { "equip_hammer_hammer_18"_hs, "assets/textures/equipment/hammer/hammer_18.png" };
        constexpr TextureAsset hammer_19 = { "equip_hammer_hammer_19"_hs, "assets/textures/equipment/hammer/hammer_19.png" };
        constexpr TextureAsset hammer_2 = { "equip_hammer_hammer_2"_hs, "assets/textures/equipment/hammer/hammer_2.png" };
        constexpr TextureAsset hammer_20 = { "equip_hammer_hammer_20"_hs, "assets/textures/equipment/hammer/hammer_20.png" };
        constexpr TextureAsset hammer_21 = { "equip_hammer_hammer_21"_hs, "assets/textures/equipment/hammer/hammer_21.png" };
        constexpr TextureAsset hammer_22 = { "equip_hammer_hammer_22"_hs, "assets/textures/equipment/hammer/hammer_22.png" };
        constexpr TextureAsset hammer_23 = { "equip_hammer_hammer_23"_hs, "assets/textures/equipment/hammer/hammer_23.png" };
        constexpr TextureAsset hammer_24 = { "equip_hammer_hammer_24"_hs, "assets/textures/equipment/hammer/hammer_24.png" };
        constexpr TextureAsset hammer_25 = { "equip_hammer_hammer_25"_hs, "assets/textures/equipment/hammer/hammer_25.png" };
        constexpr TextureAsset hammer_26 = { "equip_hammer_hammer_26"_hs, "assets/textures/equipment/hammer/hammer_26.png" };
        constexpr TextureAsset hammer_3 = { "equip_hammer_hammer_3"_hs, "assets/textures/equipment/hammer/hammer_3.png" };
        constexpr TextureAsset hammer_4 = { "equip_hammer_hammer_4"_hs, "assets/textures/equipment/hammer/hammer_4.png" };
        constexpr TextureAsset hammer_5 = { "equip_hammer_hammer_5"_hs, "assets/textures/equipment/hammer/hammer_5.png" };
        constexpr TextureAsset hammer_6 = { "equip_hammer_hammer_6"_hs, "assets/textures/equipment/hammer/hammer_6.png" };
        constexpr TextureAsset hammer_7 = { "equip_hammer_hammer_7"_hs, "assets/textures/equipment/hammer/hammer_7.png" };
        constexpr TextureAsset hammer_8 = { "equip_hammer_hammer_8"_hs, "assets/textures/equipment/hammer/hammer_8.png" };
        constexpr TextureAsset hammer_9 = { "equip_hammer_hammer_9"_hs, "assets/textures/equipment/hammer/hammer_9.png" };

        constexpr std::array<TextureAsset, 27> All = {
            hammer_0,
            hammer_1,
            hammer_10,
            hammer_11,
            hammer_12,
            hammer_13,
            hammer_14,
            hammer_15,
            hammer_16,
            hammer_17,
            hammer_18,
            hammer_19,
            hammer_2,
            hammer_20,
            hammer_21,
            hammer_22,
            hammer_23,
            hammer_24,
            hammer_25,
            hammer_26,
            hammer_3,
            hammer_4,
            hammer_5,
            hammer_6,
            hammer_7,
            hammer_8,
            hammer_9
        };
    }

    namespace helmet {
        constexpr TextureAsset helmet_0 = { "equip_helmet_helmet_0"_hs, "assets/textures/equipment/helmet/helmet_0.png" };
        constexpr TextureAsset helmet_1 = { "equip_helmet_helmet_1"_hs, "assets/textures/equipment/helmet/helmet_1.png" };
        constexpr TextureAsset helmet_10 = { "equip_helmet_helmet_10"_hs, "assets/textures/equipment/helmet/helmet_10.png" };
        constexpr TextureAsset helmet_11 = { "equip_helmet_helmet_11"_hs, "assets/textures/equipment/helmet/helmet_11.png" };
        constexpr TextureAsset helmet_12 = { "equip_helmet_helmet_12"_hs, "assets/textures/equipment/helmet/helmet_12.png" };
        constexpr TextureAsset helmet_13 = { "equip_helmet_helmet_13"_hs, "assets/textures/equipment/helmet/helmet_13.png" };
        constexpr TextureAsset helmet_14 = { "equip_helmet_helmet_14"_hs, "assets/textures/equipment/helmet/helmet_14.png" };
        constexpr TextureAsset helmet_15 = { "equip_helmet_helmet_15"_hs, "assets/textures/equipment/helmet/helmet_15.png" };
        constexpr TextureAsset helmet_16 = { "equip_helmet_helmet_16"_hs, "assets/textures/equipment/helmet/helmet_16.png" };
        constexpr TextureAsset helmet_17 = { "equip_helmet_helmet_17"_hs, "assets/textures/equipment/helmet/helmet_17.png" };
        constexpr TextureAsset helmet_18 = { "equip_helmet_helmet_18"_hs, "assets/textures/equipment/helmet/helmet_18.png" };
        constexpr TextureAsset helmet_19 = { "equip_helmet_helmet_19"_hs, "assets/textures/equipment/helmet/helmet_19.png" };
        constexpr TextureAsset helmet_2 = { "equip_helmet_helmet_2"_hs, "assets/textures/equipment/helmet/helmet_2.png" };
        constexpr TextureAsset helmet_20 = { "equip_helmet_helmet_20"_hs, "assets/textures/equipment/helmet/helmet_20.png" };
        constexpr TextureAsset helmet_21 = { "equip_helmet_helmet_21"_hs, "assets/textures/equipment/helmet/helmet_21.png" };
        constexpr TextureAsset helmet_22 = { "equip_helmet_helmet_22"_hs, "assets/textures/equipment/helmet/helmet_22.png" };
        constexpr TextureAsset helmet_23 = { "equip_helmet_helmet_23"_hs, "assets/textures/equipment/helmet/helmet_23.png" };
        constexpr TextureAsset helmet_24 = { "equip_helmet_helmet_24"_hs, "assets/textures/equipment/helmet/helmet_24.png" };
        constexpr TextureAsset helmet_25 = { "equip_helmet_helmet_25"_hs, "assets/textures/equipment/helmet/helmet_25.png" };
        constexpr TextureAsset helmet_26 = { "equip_helmet_helmet_26"_hs, "assets/textures/equipment/helmet/helmet_26.png" };
        constexpr TextureAsset helmet_27 = { "equip_helmet_helmet_27"_hs, "assets/textures/equipment/helmet/helmet_27.png" };
        constexpr TextureAsset helmet_28 = { "equip_helmet_helmet_28"_hs, "assets/textures/equipment/helmet/helmet_28.png" };
        constexpr TextureAsset helmet_3 = { "equip_helmet_helmet_3"_hs, "assets/textures/equipment/helmet/helmet_3.png" };
        constexpr TextureAsset helmet_4 = { "equip_helmet_helmet_4"_hs, "assets/textures/equipment/helmet/helmet_4.png" };
        constexpr TextureAsset helmet_5 = { "equip_helmet_helmet_5"_hs, "assets/textures/equipment/helmet/helmet_5.png" };
        constexpr TextureAsset helmet_6 = { "equip_helmet_helmet_6"_hs, "assets/textures/equipment/helmet/helmet_6.png" };
        constexpr TextureAsset helmet_7 = { "equip_helmet_helmet_7"_hs, "assets/textures/equipment/helmet/helmet_7.png" };
        constexpr TextureAsset helmet_8 = { "equip_helmet_helmet_8"_hs, "assets/textures/equipment/helmet/helmet_8.png" };
        constexpr TextureAsset helmet_9 = { "equip_helmet_helmet_9"_hs, "assets/textures/equipment/helmet/helmet_9.png" };

        constexpr std::array<TextureAsset, 29> All = {
            helmet_0,
            helmet_1,
            helmet_10,
            helmet_11,
            helmet_12,
            helmet_13,
            helmet_14,
            helmet_15,
            helmet_16,
            helmet_17,
            helmet_18,
            helmet_19,
            helmet_2,
            helmet_20,
            helmet_21,
            helmet_22,
            helmet_23,
            helmet_24,
            helmet_25,
            helmet_26,
            helmet_27,
            helmet_28,
            helmet_3,
            helmet_4,
            helmet_5,
            helmet_6,
            helmet_7,
            helmet_8,
            helmet_9
        };
    }

    namespace leggings {
        constexpr TextureAsset leggings_0 = { "equip_leggings_leggings_0"_hs, "assets/textures/equipment/leggings/leggings_0.png" };
        constexpr TextureAsset leggings_1 = { "equip_leggings_leggings_1"_hs, "assets/textures/equipment/leggings/leggings_1.png" };
        constexpr TextureAsset leggings_10 = { "equip_leggings_leggings_10"_hs, "assets/textures/equipment/leggings/leggings_10.png" };
        constexpr TextureAsset leggings_11 = { "equip_leggings_leggings_11"_hs, "assets/textures/equipment/leggings/leggings_11.png" };
        constexpr TextureAsset leggings_12 = { "equip_leggings_leggings_12"_hs, "assets/textures/equipment/leggings/leggings_12.png" };
        constexpr TextureAsset leggings_13 = { "equip_leggings_leggings_13"_hs, "assets/textures/equipment/leggings/leggings_13.png" };
        constexpr TextureAsset leggings_14 = { "equip_leggings_leggings_14"_hs, "assets/textures/equipment/leggings/leggings_14.png" };
        constexpr TextureAsset leggings_15 = { "equip_leggings_leggings_15"_hs, "assets/textures/equipment/leggings/leggings_15.png" };
        constexpr TextureAsset leggings_16 = { "equip_leggings_leggings_16"_hs, "assets/textures/equipment/leggings/leggings_16.png" };
        constexpr TextureAsset leggings_17 = { "equip_leggings_leggings_17"_hs, "assets/textures/equipment/leggings/leggings_17.png" };
        constexpr TextureAsset leggings_18 = { "equip_leggings_leggings_18"_hs, "assets/textures/equipment/leggings/leggings_18.png" };
        constexpr TextureAsset leggings_19 = { "equip_leggings_leggings_19"_hs, "assets/textures/equipment/leggings/leggings_19.png" };
        constexpr TextureAsset leggings_2 = { "equip_leggings_leggings_2"_hs, "assets/textures/equipment/leggings/leggings_2.png" };
        constexpr TextureAsset leggings_20 = { "equip_leggings_leggings_20"_hs, "assets/textures/equipment/leggings/leggings_20.png" };
        constexpr TextureAsset leggings_21 = { "equip_leggings_leggings_21"_hs, "assets/textures/equipment/leggings/leggings_21.png" };
        constexpr TextureAsset leggings_3 = { "equip_leggings_leggings_3"_hs, "assets/textures/equipment/leggings/leggings_3.png" };
        constexpr TextureAsset leggings_4 = { "equip_leggings_leggings_4"_hs, "assets/textures/equipment/leggings/leggings_4.png" };
        constexpr TextureAsset leggings_5 = { "equip_leggings_leggings_5"_hs, "assets/textures/equipment/leggings/leggings_5.png" };
        constexpr TextureAsset leggings_6 = { "equip_leggings_leggings_6"_hs, "assets/textures/equipment/leggings/leggings_6.png" };
        constexpr TextureAsset leggings_7 = { "equip_leggings_leggings_7"_hs, "assets/textures/equipment/leggings/leggings_7.png" };
        constexpr TextureAsset leggings_8 = { "equip_leggings_leggings_8"_hs, "assets/textures/equipment/leggings/leggings_8.png" };
        constexpr TextureAsset leggings_9 = { "equip_leggings_leggings_9"_hs, "assets/textures/equipment/leggings/leggings_9.png" };

        constexpr std::array<TextureAsset, 22> All = {
            leggings_0,
            leggings_1,
            leggings_10,
            leggings_11,
            leggings_12,
            leggings_13,
            leggings_14,
            leggings_15,
            leggings_16,
            leggings_17,
            leggings_18,
            leggings_19,
            leggings_2,
            leggings_20,
            leggings_21,
            leggings_3,
            leggings_4,
            leggings_5,
            leggings_6,
            leggings_7,
            leggings_8,
            leggings_9
        };
    }

    namespace orb {
        constexpr TextureAsset orb_0 = { "equip_orb_orb_0"_hs, "assets/textures/equipment/orb/orb_0.png" };
        constexpr TextureAsset orb_1 = { "equip_orb_orb_1"_hs, "assets/textures/equipment/orb/orb_1.png" };
        constexpr TextureAsset orb_10 = { "equip_orb_orb_10"_hs, "assets/textures/equipment/orb/orb_10.png" };
        constexpr TextureAsset orb_11 = { "equip_orb_orb_11"_hs, "assets/textures/equipment/orb/orb_11.png" };
        constexpr TextureAsset orb_12 = { "equip_orb_orb_12"_hs, "assets/textures/equipment/orb/orb_12.png" };
        constexpr TextureAsset orb_13 = { "equip_orb_orb_13"_hs, "assets/textures/equipment/orb/orb_13.png" };
        constexpr TextureAsset orb_14 = { "equip_orb_orb_14"_hs, "assets/textures/equipment/orb/orb_14.png" };
        constexpr TextureAsset orb_15 = { "equip_orb_orb_15"_hs, "assets/textures/equipment/orb/orb_15.png" };
        constexpr TextureAsset orb_16 = { "equip_orb_orb_16"_hs, "assets/textures/equipment/orb/orb_16.png" };
        constexpr TextureAsset orb_17 = { "equip_orb_orb_17"_hs, "assets/textures/equipment/orb/orb_17.png" };
        constexpr TextureAsset orb_18 = { "equip_orb_orb_18"_hs, "assets/textures/equipment/orb/orb_18.png" };
        constexpr TextureAsset orb_19 = { "equip_orb_orb_19"_hs, "assets/textures/equipment/orb/orb_19.png" };
        constexpr TextureAsset orb_2 = { "equip_orb_orb_2"_hs, "assets/textures/equipment/orb/orb_2.png" };
        constexpr TextureAsset orb_20 = { "equip_orb_orb_20"_hs, "assets/textures/equipment/orb/orb_20.png" };
        constexpr TextureAsset orb_21 = { "equip_orb_orb_21"_hs, "assets/textures/equipment/orb/orb_21.png" };
        constexpr TextureAsset orb_22 = { "equip_orb_orb_22"_hs, "assets/textures/equipment/orb/orb_22.png" };
        constexpr TextureAsset orb_23 = { "equip_orb_orb_23"_hs, "assets/textures/equipment/orb/orb_23.png" };
        constexpr TextureAsset orb_24 = { "equip_orb_orb_24"_hs, "assets/textures/equipment/orb/orb_24.png" };
        constexpr TextureAsset orb_25 = { "equip_orb_orb_25"_hs, "assets/textures/equipment/orb/orb_25.png" };
        constexpr TextureAsset orb_26 = { "equip_orb_orb_26"_hs, "assets/textures/equipment/orb/orb_26.png" };
        constexpr TextureAsset orb_27 = { "equip_orb_orb_27"_hs, "assets/textures/equipment/orb/orb_27.png" };
        constexpr TextureAsset orb_28 = { "equip_orb_orb_28"_hs, "assets/textures/equipment/orb/orb_28.png" };
        constexpr TextureAsset orb_29 = { "equip_orb_orb_29"_hs, "assets/textures/equipment/orb/orb_29.png" };
        constexpr TextureAsset orb_3 = { "equip_orb_orb_3"_hs, "assets/textures/equipment/orb/orb_3.png" };
        constexpr TextureAsset orb_4 = { "equip_orb_orb_4"_hs, "assets/textures/equipment/orb/orb_4.png" };
        constexpr TextureAsset orb_5 = { "equip_orb_orb_5"_hs, "assets/textures/equipment/orb/orb_5.png" };
        constexpr TextureAsset orb_6 = { "equip_orb_orb_6"_hs, "assets/textures/equipment/orb/orb_6.png" };
        constexpr TextureAsset orb_7 = { "equip_orb_orb_7"_hs, "assets/textures/equipment/orb/orb_7.png" };
        constexpr TextureAsset orb_8 = { "equip_orb_orb_8"_hs, "assets/textures/equipment/orb/orb_8.png" };
        constexpr TextureAsset orb_9 = { "equip_orb_orb_9"_hs, "assets/textures/equipment/orb/orb_9.png" };

        constexpr std::array<TextureAsset, 30> All = {
            orb_0,
            orb_1,
            orb_10,
            orb_11,
            orb_12,
            orb_13,
            orb_14,
            orb_15,
            orb_16,
            orb_17,
            orb_18,
            orb_19,
            orb_2,
            orb_20,
            orb_21,
            orb_22,
            orb_23,
            orb_24,
            orb_25,
            orb_26,
            orb_27,
            orb_28,
            orb_29,
            orb_3,
            orb_4,
            orb_5,
            orb_6,
            orb_7,
            orb_8,
            orb_9
        };
    }

    namespace pauldrons {
        constexpr TextureAsset pauldrons_0 = { "equip_pauldrons_pauldrons_0"_hs, "assets/textures/equipment/pauldrons/pauldrons_0.png" };
        constexpr TextureAsset pauldrons_1 = { "equip_pauldrons_pauldrons_1"_hs, "assets/textures/equipment/pauldrons/pauldrons_1.png" };
        constexpr TextureAsset pauldrons_10 = { "equip_pauldrons_pauldrons_10"_hs, "assets/textures/equipment/pauldrons/pauldrons_10.png" };
        constexpr TextureAsset pauldrons_11 = { "equip_pauldrons_pauldrons_11"_hs, "assets/textures/equipment/pauldrons/pauldrons_11.png" };
        constexpr TextureAsset pauldrons_12 = { "equip_pauldrons_pauldrons_12"_hs, "assets/textures/equipment/pauldrons/pauldrons_12.png" };
        constexpr TextureAsset pauldrons_13 = { "equip_pauldrons_pauldrons_13"_hs, "assets/textures/equipment/pauldrons/pauldrons_13.png" };
        constexpr TextureAsset pauldrons_14 = { "equip_pauldrons_pauldrons_14"_hs, "assets/textures/equipment/pauldrons/pauldrons_14.png" };
        constexpr TextureAsset pauldrons_15 = { "equip_pauldrons_pauldrons_15"_hs, "assets/textures/equipment/pauldrons/pauldrons_15.png" };
        constexpr TextureAsset pauldrons_16 = { "equip_pauldrons_pauldrons_16"_hs, "assets/textures/equipment/pauldrons/pauldrons_16.png" };
        constexpr TextureAsset pauldrons_17 = { "equip_pauldrons_pauldrons_17"_hs, "assets/textures/equipment/pauldrons/pauldrons_17.png" };
        constexpr TextureAsset pauldrons_18 = { "equip_pauldrons_pauldrons_18"_hs, "assets/textures/equipment/pauldrons/pauldrons_18.png" };
        constexpr TextureAsset pauldrons_19 = { "equip_pauldrons_pauldrons_19"_hs, "assets/textures/equipment/pauldrons/pauldrons_19.png" };
        constexpr TextureAsset pauldrons_2 = { "equip_pauldrons_pauldrons_2"_hs, "assets/textures/equipment/pauldrons/pauldrons_2.png" };
        constexpr TextureAsset pauldrons_20 = { "equip_pauldrons_pauldrons_20"_hs, "assets/textures/equipment/pauldrons/pauldrons_20.png" };
        constexpr TextureAsset pauldrons_21 = { "equip_pauldrons_pauldrons_21"_hs, "assets/textures/equipment/pauldrons/pauldrons_21.png" };
        constexpr TextureAsset pauldrons_22 = { "equip_pauldrons_pauldrons_22"_hs, "assets/textures/equipment/pauldrons/pauldrons_22.png" };
        constexpr TextureAsset pauldrons_23 = { "equip_pauldrons_pauldrons_23"_hs, "assets/textures/equipment/pauldrons/pauldrons_23.png" };
        constexpr TextureAsset pauldrons_3 = { "equip_pauldrons_pauldrons_3"_hs, "assets/textures/equipment/pauldrons/pauldrons_3.png" };
        constexpr TextureAsset pauldrons_4 = { "equip_pauldrons_pauldrons_4"_hs, "assets/textures/equipment/pauldrons/pauldrons_4.png" };
        constexpr TextureAsset pauldrons_5 = { "equip_pauldrons_pauldrons_5"_hs, "assets/textures/equipment/pauldrons/pauldrons_5.png" };
        constexpr TextureAsset pauldrons_6 = { "equip_pauldrons_pauldrons_6"_hs, "assets/textures/equipment/pauldrons/pauldrons_6.png" };
        constexpr TextureAsset pauldrons_7 = { "equip_pauldrons_pauldrons_7"_hs, "assets/textures/equipment/pauldrons/pauldrons_7.png" };
        constexpr TextureAsset pauldrons_8 = { "equip_pauldrons_pauldrons_8"_hs, "assets/textures/equipment/pauldrons/pauldrons_8.png" };
        constexpr TextureAsset pauldrons_9 = { "equip_pauldrons_pauldrons_9"_hs, "assets/textures/equipment/pauldrons/pauldrons_9.png" };

        constexpr std::array<TextureAsset, 24> All = {
            pauldrons_0,
            pauldrons_1,
            pauldrons_10,
            pauldrons_11,
            pauldrons_12,
            pauldrons_13,
            pauldrons_14,
            pauldrons_15,
            pauldrons_16,
            pauldrons_17,
            pauldrons_18,
            pauldrons_19,
            pauldrons_2,
            pauldrons_20,
            pauldrons_21,
            pauldrons_22,
            pauldrons_23,
            pauldrons_3,
            pauldrons_4,
            pauldrons_5,
            pauldrons_6,
            pauldrons_7,
            pauldrons_8,
            pauldrons_9
        };
    }

    namespace ring {
        constexpr TextureAsset ring_0 = { "equip_ring_ring_0"_hs, "assets/textures/equipment/ring/ring_0.png" };
        constexpr TextureAsset ring_1 = { "equip_ring_ring_1"_hs, "assets/textures/equipment/ring/ring_1.png" };
        constexpr TextureAsset ring_10 = { "equip_ring_ring_10"_hs, "assets/textures/equipment/ring/ring_10.png" };
        constexpr TextureAsset ring_11 = { "equip_ring_ring_11"_hs, "assets/textures/equipment/ring/ring_11.png" };
        constexpr TextureAsset ring_12 = { "equip_ring_ring_12"_hs, "assets/textures/equipment/ring/ring_12.png" };
        constexpr TextureAsset ring_13 = { "equip_ring_ring_13"_hs, "assets/textures/equipment/ring/ring_13.png" };
        constexpr TextureAsset ring_14 = { "equip_ring_ring_14"_hs, "assets/textures/equipment/ring/ring_14.png" };
        constexpr TextureAsset ring_15 = { "equip_ring_ring_15"_hs, "assets/textures/equipment/ring/ring_15.png" };
        constexpr TextureAsset ring_16 = { "equip_ring_ring_16"_hs, "assets/textures/equipment/ring/ring_16.png" };
        constexpr TextureAsset ring_17 = { "equip_ring_ring_17"_hs, "assets/textures/equipment/ring/ring_17.png" };
        constexpr TextureAsset ring_18 = { "equip_ring_ring_18"_hs, "assets/textures/equipment/ring/ring_18.png" };
        constexpr TextureAsset ring_19 = { "equip_ring_ring_19"_hs, "assets/textures/equipment/ring/ring_19.png" };
        constexpr TextureAsset ring_2 = { "equip_ring_ring_2"_hs, "assets/textures/equipment/ring/ring_2.png" };
        constexpr TextureAsset ring_20 = { "equip_ring_ring_20"_hs, "assets/textures/equipment/ring/ring_20.png" };
        constexpr TextureAsset ring_21 = { "equip_ring_ring_21"_hs, "assets/textures/equipment/ring/ring_21.png" };
        constexpr TextureAsset ring_22 = { "equip_ring_ring_22"_hs, "assets/textures/equipment/ring/ring_22.png" };
        constexpr TextureAsset ring_23 = { "equip_ring_ring_23"_hs, "assets/textures/equipment/ring/ring_23.png" };
        constexpr TextureAsset ring_24 = { "equip_ring_ring_24"_hs, "assets/textures/equipment/ring/ring_24.png" };
        constexpr TextureAsset ring_25 = { "equip_ring_ring_25"_hs, "assets/textures/equipment/ring/ring_25.png" };
        constexpr TextureAsset ring_26 = { "equip_ring_ring_26"_hs, "assets/textures/equipment/ring/ring_26.png" };
        constexpr TextureAsset ring_27 = { "equip_ring_ring_27"_hs, "assets/textures/equipment/ring/ring_27.png" };
        constexpr TextureAsset ring_28 = { "equip_ring_ring_28"_hs, "assets/textures/equipment/ring/ring_28.png" };
        constexpr TextureAsset ring_3 = { "equip_ring_ring_3"_hs, "assets/textures/equipment/ring/ring_3.png" };
        constexpr TextureAsset ring_4 = { "equip_ring_ring_4"_hs, "assets/textures/equipment/ring/ring_4.png" };
        constexpr TextureAsset ring_5 = { "equip_ring_ring_5"_hs, "assets/textures/equipment/ring/ring_5.png" };
        constexpr TextureAsset ring_6 = { "equip_ring_ring_6"_hs, "assets/textures/equipment/ring/ring_6.png" };
        constexpr TextureAsset ring_7 = { "equip_ring_ring_7"_hs, "assets/textures/equipment/ring/ring_7.png" };
        constexpr TextureAsset ring_8 = { "equip_ring_ring_8"_hs, "assets/textures/equipment/ring/ring_8.png" };
        constexpr TextureAsset ring_9 = { "equip_ring_ring_9"_hs, "assets/textures/equipment/ring/ring_9.png" };

        constexpr std::array<TextureAsset, 29> All = {
            ring_0,
            ring_1,
            ring_10,
            ring_11,
            ring_12,
            ring_13,
            ring_14,
            ring_15,
            ring_16,
            ring_17,
            ring_18,
            ring_19,
            ring_2,
            ring_20,
            ring_21,
            ring_22,
            ring_23,
            ring_24,
            ring_25,
            ring_26,
            ring_27,
            ring_28,
            ring_3,
            ring_4,
            ring_5,
            ring_6,
            ring_7,
            ring_8,
            ring_9
        };
    }

    namespace shield {
        constexpr TextureAsset shield_0 = { "equip_shield_shield_0"_hs, "assets/textures/equipment/shield/shield_0.png" };
        constexpr TextureAsset shield_1 = { "equip_shield_shield_1"_hs, "assets/textures/equipment/shield/shield_1.png" };
        constexpr TextureAsset shield_10 = { "equip_shield_shield_10"_hs, "assets/textures/equipment/shield/shield_10.png" };
        constexpr TextureAsset shield_11 = { "equip_shield_shield_11"_hs, "assets/textures/equipment/shield/shield_11.png" };
        constexpr TextureAsset shield_12 = { "equip_shield_shield_12"_hs, "assets/textures/equipment/shield/shield_12.png" };
        constexpr TextureAsset shield_13 = { "equip_shield_shield_13"_hs, "assets/textures/equipment/shield/shield_13.png" };
        constexpr TextureAsset shield_14 = { "equip_shield_shield_14"_hs, "assets/textures/equipment/shield/shield_14.png" };
        constexpr TextureAsset shield_15 = { "equip_shield_shield_15"_hs, "assets/textures/equipment/shield/shield_15.png" };
        constexpr TextureAsset shield_16 = { "equip_shield_shield_16"_hs, "assets/textures/equipment/shield/shield_16.png" };
        constexpr TextureAsset shield_17 = { "equip_shield_shield_17"_hs, "assets/textures/equipment/shield/shield_17.png" };
        constexpr TextureAsset shield_18 = { "equip_shield_shield_18"_hs, "assets/textures/equipment/shield/shield_18.png" };
        constexpr TextureAsset shield_19 = { "equip_shield_shield_19"_hs, "assets/textures/equipment/shield/shield_19.png" };
        constexpr TextureAsset shield_2 = { "equip_shield_shield_2"_hs, "assets/textures/equipment/shield/shield_2.png" };
        constexpr TextureAsset shield_20 = { "equip_shield_shield_20"_hs, "assets/textures/equipment/shield/shield_20.png" };
        constexpr TextureAsset shield_21 = { "equip_shield_shield_21"_hs, "assets/textures/equipment/shield/shield_21.png" };
        constexpr TextureAsset shield_22 = { "equip_shield_shield_22"_hs, "assets/textures/equipment/shield/shield_22.png" };
        constexpr TextureAsset shield_23 = { "equip_shield_shield_23"_hs, "assets/textures/equipment/shield/shield_23.png" };
        constexpr TextureAsset shield_24 = { "equip_shield_shield_24"_hs, "assets/textures/equipment/shield/shield_24.png" };
        constexpr TextureAsset shield_25 = { "equip_shield_shield_25"_hs, "assets/textures/equipment/shield/shield_25.png" };
        constexpr TextureAsset shield_26 = { "equip_shield_shield_26"_hs, "assets/textures/equipment/shield/shield_26.png" };
        constexpr TextureAsset shield_3 = { "equip_shield_shield_3"_hs, "assets/textures/equipment/shield/shield_3.png" };
        constexpr TextureAsset shield_4 = { "equip_shield_shield_4"_hs, "assets/textures/equipment/shield/shield_4.png" };
        constexpr TextureAsset shield_5 = { "equip_shield_shield_5"_hs, "assets/textures/equipment/shield/shield_5.png" };
        constexpr TextureAsset shield_6 = { "equip_shield_shield_6"_hs, "assets/textures/equipment/shield/shield_6.png" };
        constexpr TextureAsset shield_7 = { "equip_shield_shield_7"_hs, "assets/textures/equipment/shield/shield_7.png" };
        constexpr TextureAsset shield_8 = { "equip_shield_shield_8"_hs, "assets/textures/equipment/shield/shield_8.png" };
        constexpr TextureAsset shield_9 = { "equip_shield_shield_9"_hs, "assets/textures/equipment/shield/shield_9.png" };

        constexpr std::array<TextureAsset, 27> All = {
            shield_0,
            shield_1,
            shield_10,
            shield_11,
            shield_12,
            shield_13,
            shield_14,
            shield_15,
            shield_16,
            shield_17,
            shield_18,
            shield_19,
            shield_2,
            shield_20,
            shield_21,
            shield_22,
            shield_23,
            shield_24,
            shield_25,
            shield_26,
            shield_3,
            shield_4,
            shield_5,
            shield_6,
            shield_7,
            shield_8,
            shield_9
        };
    }

    namespace staff {
        constexpr TextureAsset staff_0 = { "equip_staff_staff_0"_hs, "assets/textures/equipment/staff/staff_0.png" };
        constexpr TextureAsset staff_1 = { "equip_staff_staff_1"_hs, "assets/textures/equipment/staff/staff_1.png" };
        constexpr TextureAsset staff_10 = { "equip_staff_staff_10"_hs, "assets/textures/equipment/staff/staff_10.png" };
        constexpr TextureAsset staff_11 = { "equip_staff_staff_11"_hs, "assets/textures/equipment/staff/staff_11.png" };
        constexpr TextureAsset staff_12 = { "equip_staff_staff_12"_hs, "assets/textures/equipment/staff/staff_12.png" };
        constexpr TextureAsset staff_13 = { "equip_staff_staff_13"_hs, "assets/textures/equipment/staff/staff_13.png" };
        constexpr TextureAsset staff_14 = { "equip_staff_staff_14"_hs, "assets/textures/equipment/staff/staff_14.png" };
        constexpr TextureAsset staff_15 = { "equip_staff_staff_15"_hs, "assets/textures/equipment/staff/staff_15.png" };
        constexpr TextureAsset staff_16 = { "equip_staff_staff_16"_hs, "assets/textures/equipment/staff/staff_16.png" };
        constexpr TextureAsset staff_17 = { "equip_staff_staff_17"_hs, "assets/textures/equipment/staff/staff_17.png" };
        constexpr TextureAsset staff_18 = { "equip_staff_staff_18"_hs, "assets/textures/equipment/staff/staff_18.png" };
        constexpr TextureAsset staff_19 = { "equip_staff_staff_19"_hs, "assets/textures/equipment/staff/staff_19.png" };
        constexpr TextureAsset staff_2 = { "equip_staff_staff_2"_hs, "assets/textures/equipment/staff/staff_2.png" };
        constexpr TextureAsset staff_20 = { "equip_staff_staff_20"_hs, "assets/textures/equipment/staff/staff_20.png" };
        constexpr TextureAsset staff_21 = { "equip_staff_staff_21"_hs, "assets/textures/equipment/staff/staff_21.png" };
        constexpr TextureAsset staff_3 = { "equip_staff_staff_3"_hs, "assets/textures/equipment/staff/staff_3.png" };
        constexpr TextureAsset staff_4 = { "equip_staff_staff_4"_hs, "assets/textures/equipment/staff/staff_4.png" };
        constexpr TextureAsset staff_5 = { "equip_staff_staff_5"_hs, "assets/textures/equipment/staff/staff_5.png" };
        constexpr TextureAsset staff_6 = { "equip_staff_staff_6"_hs, "assets/textures/equipment/staff/staff_6.png" };
        constexpr TextureAsset staff_7 = { "equip_staff_staff_7"_hs, "assets/textures/equipment/staff/staff_7.png" };
        constexpr TextureAsset staff_8 = { "equip_staff_staff_8"_hs, "assets/textures/equipment/staff/staff_8.png" };
        constexpr TextureAsset staff_9 = { "equip_staff_staff_9"_hs, "assets/textures/equipment/staff/staff_9.png" };

        constexpr std::array<TextureAsset, 22> All = {
            staff_0,
            staff_1,
            staff_10,
            staff_11,
            staff_12,
            staff_13,
            staff_14,
            staff_15,
            staff_16,
            staff_17,
            staff_18,
            staff_19,
            staff_2,
            staff_20,
            staff_21,
            staff_3,
            staff_4,
            staff_5,
            staff_6,
            staff_7,
            staff_8,
            staff_9
        };
    }

    namespace sword {
        constexpr TextureAsset sword_0 = { "equip_sword_sword_0"_hs, "assets/textures/equipment/sword/sword_0.png" };
        constexpr TextureAsset sword_1 = { "equip_sword_sword_1"_hs, "assets/textures/equipment/sword/sword_1.png" };
        constexpr TextureAsset sword_10 = { "equip_sword_sword_10"_hs, "assets/textures/equipment/sword/sword_10.png" };
        constexpr TextureAsset sword_11 = { "equip_sword_sword_11"_hs, "assets/textures/equipment/sword/sword_11.png" };
        constexpr TextureAsset sword_12 = { "equip_sword_sword_12"_hs, "assets/textures/equipment/sword/sword_12.png" };
        constexpr TextureAsset sword_13 = { "equip_sword_sword_13"_hs, "assets/textures/equipment/sword/sword_13.png" };
        constexpr TextureAsset sword_14 = { "equip_sword_sword_14"_hs, "assets/textures/equipment/sword/sword_14.png" };
        constexpr TextureAsset sword_15 = { "equip_sword_sword_15"_hs, "assets/textures/equipment/sword/sword_15.png" };
        constexpr TextureAsset sword_16 = { "equip_sword_sword_16"_hs, "assets/textures/equipment/sword/sword_16.png" };
        constexpr TextureAsset sword_17 = { "equip_sword_sword_17"_hs, "assets/textures/equipment/sword/sword_17.png" };
        constexpr TextureAsset sword_18 = { "equip_sword_sword_18"_hs, "assets/textures/equipment/sword/sword_18.png" };
        constexpr TextureAsset sword_19 = { "equip_sword_sword_19"_hs, "assets/textures/equipment/sword/sword_19.png" };
        constexpr TextureAsset sword_2 = { "equip_sword_sword_2"_hs, "assets/textures/equipment/sword/sword_2.png" };
        constexpr TextureAsset sword_3 = { "equip_sword_sword_3"_hs, "assets/textures/equipment/sword/sword_3.png" };
        constexpr TextureAsset sword_4 = { "equip_sword_sword_4"_hs, "assets/textures/equipment/sword/sword_4.png" };
        constexpr TextureAsset sword_5 = { "equip_sword_sword_5"_hs, "assets/textures/equipment/sword/sword_5.png" };
        constexpr TextureAsset sword_6 = { "equip_sword_sword_6"_hs, "assets/textures/equipment/sword/sword_6.png" };
        constexpr TextureAsset sword_7 = { "equip_sword_sword_7"_hs, "assets/textures/equipment/sword/sword_7.png" };
        constexpr TextureAsset sword_8 = { "equip_sword_sword_8"_hs, "assets/textures/equipment/sword/sword_8.png" };
        constexpr TextureAsset sword_9 = { "equip_sword_sword_9"_hs, "assets/textures/equipment/sword/sword_9.png" };

        constexpr std::array<TextureAsset, 20> All = {
            sword_0,
            sword_1,
            sword_10,
            sword_11,
            sword_12,
            sword_13,
            sword_14,
            sword_15,
            sword_16,
            sword_17,
            sword_18,
            sword_19,
            sword_2,
            sword_3,
            sword_4,
            sword_5,
            sword_6,
            sword_7,
            sword_8,
            sword_9
        };
    }

    namespace wand {
        constexpr TextureAsset wand_0 = { "equip_wand_wand_0"_hs, "assets/textures/equipment/wand/wand_0.png" };
        constexpr TextureAsset wand_1 = { "equip_wand_wand_1"_hs, "assets/textures/equipment/wand/wand_1.png" };
        constexpr TextureAsset wand_10 = { "equip_wand_wand_10"_hs, "assets/textures/equipment/wand/wand_10.png" };
        constexpr TextureAsset wand_11 = { "equip_wand_wand_11"_hs, "assets/textures/equipment/wand/wand_11.png" };
        constexpr TextureAsset wand_12 = { "equip_wand_wand_12"_hs, "assets/textures/equipment/wand/wand_12.png" };
        constexpr TextureAsset wand_13 = { "equip_wand_wand_13"_hs, "assets/textures/equipment/wand/wand_13.png" };
        constexpr TextureAsset wand_14 = { "equip_wand_wand_14"_hs, "assets/textures/equipment/wand/wand_14.png" };
        constexpr TextureAsset wand_15 = { "equip_wand_wand_15"_hs, "assets/textures/equipment/wand/wand_15.png" };
        constexpr TextureAsset wand_16 = { "equip_wand_wand_16"_hs, "assets/textures/equipment/wand/wand_16.png" };
        constexpr TextureAsset wand_17 = { "equip_wand_wand_17"_hs, "assets/textures/equipment/wand/wand_17.png" };
        constexpr TextureAsset wand_18 = { "equip_wand_wand_18"_hs, "assets/textures/equipment/wand/wand_18.png" };
        constexpr TextureAsset wand_19 = { "equip_wand_wand_19"_hs, "assets/textures/equipment/wand/wand_19.png" };
        constexpr TextureAsset wand_2 = { "equip_wand_wand_2"_hs, "assets/textures/equipment/wand/wand_2.png" };
        constexpr TextureAsset wand_20 = { "equip_wand_wand_20"_hs, "assets/textures/equipment/wand/wand_20.png" };
        constexpr TextureAsset wand_21 = { "equip_wand_wand_21"_hs, "assets/textures/equipment/wand/wand_21.png" };
        constexpr TextureAsset wand_22 = { "equip_wand_wand_22"_hs, "assets/textures/equipment/wand/wand_22.png" };
        constexpr TextureAsset wand_23 = { "equip_wand_wand_23"_hs, "assets/textures/equipment/wand/wand_23.png" };
        constexpr TextureAsset wand_3 = { "equip_wand_wand_3"_hs, "assets/textures/equipment/wand/wand_3.png" };
        constexpr TextureAsset wand_4 = { "equip_wand_wand_4"_hs, "assets/textures/equipment/wand/wand_4.png" };
        constexpr TextureAsset wand_5 = { "equip_wand_wand_5"_hs, "assets/textures/equipment/wand/wand_5.png" };
        constexpr TextureAsset wand_6 = { "equip_wand_wand_6"_hs, "assets/textures/equipment/wand/wand_6.png" };
        constexpr TextureAsset wand_7 = { "equip_wand_wand_7"_hs, "assets/textures/equipment/wand/wand_7.png" };
        constexpr TextureAsset wand_8 = { "equip_wand_wand_8"_hs, "assets/textures/equipment/wand/wand_8.png" };
        constexpr TextureAsset wand_9 = { "equip_wand_wand_9"_hs, "assets/textures/equipment/wand/wand_9.png" };

        constexpr std::array<TextureAsset, 24> All = {
            wand_0,
            wand_1,
            wand_10,
            wand_11,
            wand_12,
            wand_13,
            wand_14,
            wand_15,
            wand_16,
            wand_17,
            wand_18,
            wand_19,
            wand_2,
            wand_20,
            wand_21,
            wand_22,
            wand_23,
            wand_3,
            wand_4,
            wand_5,
            wand_6,
            wand_7,
            wand_8,
            wand_9
        };
    }

}