#pragma once
// This file is auto-generated by scripts/gen_asset_registries.py
// Do not modify this file directly. Run the script to regenerate.

#include "engine/resource/AssetRegistry.hpp"
#include <array>

using namespace entt::literals;

namespace assets::equipment {

    namespace amulet {
        inline constexpr TextureAsset amulet_0 = { "equip_amulet_amulet_0"_hs, "assets/textures/equipment/amulet/amulet_0.png" };
        inline constexpr TextureAsset amulet_1 = { "equip_amulet_amulet_1"_hs, "assets/textures/equipment/amulet/amulet_1.png" };
        inline constexpr TextureAsset amulet_2 = { "equip_amulet_amulet_2"_hs, "assets/textures/equipment/amulet/amulet_2.png" };
        inline constexpr TextureAsset amulet_3 = { "equip_amulet_amulet_3"_hs, "assets/textures/equipment/amulet/amulet_3.png" };
        inline constexpr TextureAsset amulet_4 = { "equip_amulet_amulet_4"_hs, "assets/textures/equipment/amulet/amulet_4.png" };
        inline constexpr TextureAsset amulet_5 = { "equip_amulet_amulet_5"_hs, "assets/textures/equipment/amulet/amulet_5.png" };
        inline constexpr TextureAsset amulet_6 = { "equip_amulet_amulet_6"_hs, "assets/textures/equipment/amulet/amulet_6.png" };
        inline constexpr TextureAsset amulet_7 = { "equip_amulet_amulet_7"_hs, "assets/textures/equipment/amulet/amulet_7.png" };
        inline constexpr TextureAsset amulet_8 = { "equip_amulet_amulet_8"_hs, "assets/textures/equipment/amulet/amulet_8.png" };
        inline constexpr TextureAsset amulet_9 = { "equip_amulet_amulet_9"_hs, "assets/textures/equipment/amulet/amulet_9.png" };

        constexpr std::array<const TextureAsset*, 10> All = {
            &amulet_0,
            &amulet_1,
            &amulet_2,
            &amulet_3,
            &amulet_4,
            &amulet_5,
            &amulet_6,
            &amulet_7,
            &amulet_8,
            &amulet_9
        };
    } // namespace amulet

    namespace axe {
        inline constexpr TextureAsset axe_0 = { "equip_axe_axe_0"_hs, "assets/textures/equipment/axe/axe_0.png" };
        inline constexpr TextureAsset axe_1 = { "equip_axe_axe_1"_hs, "assets/textures/equipment/axe/axe_1.png" };
        inline constexpr TextureAsset axe_2 = { "equip_axe_axe_2"_hs, "assets/textures/equipment/axe/axe_2.png" };
        inline constexpr TextureAsset axe_3 = { "equip_axe_axe_3"_hs, "assets/textures/equipment/axe/axe_3.png" };
        inline constexpr TextureAsset axe_4 = { "equip_axe_axe_4"_hs, "assets/textures/equipment/axe/axe_4.png" };
        inline constexpr TextureAsset axe_5 = { "equip_axe_axe_5"_hs, "assets/textures/equipment/axe/axe_5.png" };
        inline constexpr TextureAsset axe_6 = { "equip_axe_axe_6"_hs, "assets/textures/equipment/axe/axe_6.png" };
        inline constexpr TextureAsset axe_7 = { "equip_axe_axe_7"_hs, "assets/textures/equipment/axe/axe_7.png" };
        inline constexpr TextureAsset axe_8 = { "equip_axe_axe_8"_hs, "assets/textures/equipment/axe/axe_8.png" };
        inline constexpr TextureAsset axe_9 = { "equip_axe_axe_9"_hs, "assets/textures/equipment/axe/axe_9.png" };

        constexpr std::array<const TextureAsset*, 10> All = {
            &axe_0,
            &axe_1,
            &axe_2,
            &axe_3,
            &axe_4,
            &axe_5,
            &axe_6,
            &axe_7,
            &axe_8,
            &axe_9
        };
    } // namespace axe

    namespace boots {
        inline constexpr TextureAsset boots_0 = { "equip_boots_boots_0"_hs, "assets/textures/equipment/boots/boots_0.png" };
        inline constexpr TextureAsset boots_1 = { "equip_boots_boots_1"_hs, "assets/textures/equipment/boots/boots_1.png" };
        inline constexpr TextureAsset boots_2 = { "equip_boots_boots_2"_hs, "assets/textures/equipment/boots/boots_2.png" };
        inline constexpr TextureAsset boots_3 = { "equip_boots_boots_3"_hs, "assets/textures/equipment/boots/boots_3.png" };
        inline constexpr TextureAsset boots_4 = { "equip_boots_boots_4"_hs, "assets/textures/equipment/boots/boots_4.png" };
        inline constexpr TextureAsset boots_5 = { "equip_boots_boots_5"_hs, "assets/textures/equipment/boots/boots_5.png" };
        inline constexpr TextureAsset boots_6 = { "equip_boots_boots_6"_hs, "assets/textures/equipment/boots/boots_6.png" };
        inline constexpr TextureAsset boots_7 = { "equip_boots_boots_7"_hs, "assets/textures/equipment/boots/boots_7.png" };
        inline constexpr TextureAsset boots_8 = { "equip_boots_boots_8"_hs, "assets/textures/equipment/boots/boots_8.png" };
        inline constexpr TextureAsset boots_9 = { "equip_boots_boots_9"_hs, "assets/textures/equipment/boots/boots_9.png" };

        constexpr std::array<const TextureAsset*, 10> All = {
            &boots_0,
            &boots_1,
            &boots_2,
            &boots_3,
            &boots_4,
            &boots_5,
            &boots_6,
            &boots_7,
            &boots_8,
            &boots_9
        };
    } // namespace boots

    namespace chest {
        inline constexpr TextureAsset chest_0 = { "equip_chest_chest_0"_hs, "assets/textures/equipment/chest/chest_0.png" };
        inline constexpr TextureAsset chest_1 = { "equip_chest_chest_1"_hs, "assets/textures/equipment/chest/chest_1.png" };
        inline constexpr TextureAsset chest_2 = { "equip_chest_chest_2"_hs, "assets/textures/equipment/chest/chest_2.png" };
        inline constexpr TextureAsset chest_3 = { "equip_chest_chest_3"_hs, "assets/textures/equipment/chest/chest_3.png" };
        inline constexpr TextureAsset chest_4 = { "equip_chest_chest_4"_hs, "assets/textures/equipment/chest/chest_4.png" };
        inline constexpr TextureAsset chest_5 = { "equip_chest_chest_5"_hs, "assets/textures/equipment/chest/chest_5.png" };
        inline constexpr TextureAsset chest_6 = { "equip_chest_chest_6"_hs, "assets/textures/equipment/chest/chest_6.png" };
        inline constexpr TextureAsset chest_7 = { "equip_chest_chest_7"_hs, "assets/textures/equipment/chest/chest_7.png" };
        inline constexpr TextureAsset chest_8 = { "equip_chest_chest_8"_hs, "assets/textures/equipment/chest/chest_8.png" };
        inline constexpr TextureAsset chest_9 = { "equip_chest_chest_9"_hs, "assets/textures/equipment/chest/chest_9.png" };

        constexpr std::array<const TextureAsset*, 10> All = {
            &chest_0,
            &chest_1,
            &chest_2,
            &chest_3,
            &chest_4,
            &chest_5,
            &chest_6,
            &chest_7,
            &chest_8,
            &chest_9
        };
    } // namespace chest

    namespace dagger {
        inline constexpr TextureAsset dagger_0 = { "equip_dagger_dagger_0"_hs, "assets/textures/equipment/dagger/dagger_0.png" };
        inline constexpr TextureAsset dagger_1 = { "equip_dagger_dagger_1"_hs, "assets/textures/equipment/dagger/dagger_1.png" };
        inline constexpr TextureAsset dagger_2 = { "equip_dagger_dagger_2"_hs, "assets/textures/equipment/dagger/dagger_2.png" };
        inline constexpr TextureAsset dagger_3 = { "equip_dagger_dagger_3"_hs, "assets/textures/equipment/dagger/dagger_3.png" };
        inline constexpr TextureAsset dagger_4 = { "equip_dagger_dagger_4"_hs, "assets/textures/equipment/dagger/dagger_4.png" };
        inline constexpr TextureAsset dagger_5 = { "equip_dagger_dagger_5"_hs, "assets/textures/equipment/dagger/dagger_5.png" };
        inline constexpr TextureAsset dagger_6 = { "equip_dagger_dagger_6"_hs, "assets/textures/equipment/dagger/dagger_6.png" };
        inline constexpr TextureAsset dagger_7 = { "equip_dagger_dagger_7"_hs, "assets/textures/equipment/dagger/dagger_7.png" };
        inline constexpr TextureAsset dagger_8 = { "equip_dagger_dagger_8"_hs, "assets/textures/equipment/dagger/dagger_8.png" };
        inline constexpr TextureAsset dagger_9 = { "equip_dagger_dagger_9"_hs, "assets/textures/equipment/dagger/dagger_9.png" };

        constexpr std::array<const TextureAsset*, 10> All = {
            &dagger_0,
            &dagger_1,
            &dagger_2,
            &dagger_3,
            &dagger_4,
            &dagger_5,
            &dagger_6,
            &dagger_7,
            &dagger_8,
            &dagger_9
        };
    } // namespace dagger

    namespace gauntlets {
        inline constexpr TextureAsset gauntlets_0 = { "equip_gauntlets_gauntlets_0"_hs, "assets/textures/equipment/gauntlets/gauntlets_0.png" };
        inline constexpr TextureAsset gauntlets_1 = { "equip_gauntlets_gauntlets_1"_hs, "assets/textures/equipment/gauntlets/gauntlets_1.png" };
        inline constexpr TextureAsset gauntlets_2 = { "equip_gauntlets_gauntlets_2"_hs, "assets/textures/equipment/gauntlets/gauntlets_2.png" };
        inline constexpr TextureAsset gauntlets_3 = { "equip_gauntlets_gauntlets_3"_hs, "assets/textures/equipment/gauntlets/gauntlets_3.png" };
        inline constexpr TextureAsset gauntlets_4 = { "equip_gauntlets_gauntlets_4"_hs, "assets/textures/equipment/gauntlets/gauntlets_4.png" };
        inline constexpr TextureAsset gauntlets_5 = { "equip_gauntlets_gauntlets_5"_hs, "assets/textures/equipment/gauntlets/gauntlets_5.png" };
        inline constexpr TextureAsset gauntlets_6 = { "equip_gauntlets_gauntlets_6"_hs, "assets/textures/equipment/gauntlets/gauntlets_6.png" };
        inline constexpr TextureAsset gauntlets_7 = { "equip_gauntlets_gauntlets_7"_hs, "assets/textures/equipment/gauntlets/gauntlets_7.png" };
        inline constexpr TextureAsset gauntlets_8 = { "equip_gauntlets_gauntlets_8"_hs, "assets/textures/equipment/gauntlets/gauntlets_8.png" };
        inline constexpr TextureAsset gauntlets_9 = { "equip_gauntlets_gauntlets_9"_hs, "assets/textures/equipment/gauntlets/gauntlets_9.png" };

        constexpr std::array<const TextureAsset*, 10> All = {
            &gauntlets_0,
            &gauntlets_1,
            &gauntlets_2,
            &gauntlets_3,
            &gauntlets_4,
            &gauntlets_5,
            &gauntlets_6,
            &gauntlets_7,
            &gauntlets_8,
            &gauntlets_9
        };
    } // namespace gauntlets

    namespace greatsword {
        inline constexpr TextureAsset greatsword_0 = { "equip_greatsword_greatsword_0"_hs, "assets/textures/equipment/greatsword/greatsword_0.png" };
        inline constexpr TextureAsset greatsword_1 = { "equip_greatsword_greatsword_1"_hs, "assets/textures/equipment/greatsword/greatsword_1.png" };
        inline constexpr TextureAsset greatsword_2 = { "equip_greatsword_greatsword_2"_hs, "assets/textures/equipment/greatsword/greatsword_2.png" };
        inline constexpr TextureAsset greatsword_3 = { "equip_greatsword_greatsword_3"_hs, "assets/textures/equipment/greatsword/greatsword_3.png" };
        inline constexpr TextureAsset greatsword_4 = { "equip_greatsword_greatsword_4"_hs, "assets/textures/equipment/greatsword/greatsword_4.png" };
        inline constexpr TextureAsset greatsword_5 = { "equip_greatsword_greatsword_5"_hs, "assets/textures/equipment/greatsword/greatsword_5.png" };
        inline constexpr TextureAsset greatsword_6 = { "equip_greatsword_greatsword_6"_hs, "assets/textures/equipment/greatsword/greatsword_6.png" };
        inline constexpr TextureAsset greatsword_7 = { "equip_greatsword_greatsword_7"_hs, "assets/textures/equipment/greatsword/greatsword_7.png" };
        inline constexpr TextureAsset greatsword_8 = { "equip_greatsword_greatsword_8"_hs, "assets/textures/equipment/greatsword/greatsword_8.png" };

        constexpr std::array<const TextureAsset*, 9> All = {
            &greatsword_0,
            &greatsword_1,
            &greatsword_2,
            &greatsword_3,
            &greatsword_4,
            &greatsword_5,
            &greatsword_6,
            &greatsword_7,
            &greatsword_8
        };
    } // namespace greatsword

    namespace grimoire {
        inline constexpr TextureAsset grimoire_0 = { "equip_grimoire_grimoire_0"_hs, "assets/textures/equipment/grimoire/grimoire_0.png" };
        inline constexpr TextureAsset grimoire_1 = { "equip_grimoire_grimoire_1"_hs, "assets/textures/equipment/grimoire/grimoire_1.png" };
        inline constexpr TextureAsset grimoire_2 = { "equip_grimoire_grimoire_2"_hs, "assets/textures/equipment/grimoire/grimoire_2.png" };
        inline constexpr TextureAsset grimoire_3 = { "equip_grimoire_grimoire_3"_hs, "assets/textures/equipment/grimoire/grimoire_3.png" };
        inline constexpr TextureAsset grimoire_4 = { "equip_grimoire_grimoire_4"_hs, "assets/textures/equipment/grimoire/grimoire_4.png" };
        inline constexpr TextureAsset grimoire_5 = { "equip_grimoire_grimoire_5"_hs, "assets/textures/equipment/grimoire/grimoire_5.png" };
        inline constexpr TextureAsset grimoire_6 = { "equip_grimoire_grimoire_6"_hs, "assets/textures/equipment/grimoire/grimoire_6.png" };
        inline constexpr TextureAsset grimoire_7 = { "equip_grimoire_grimoire_7"_hs, "assets/textures/equipment/grimoire/grimoire_7.png" };
        inline constexpr TextureAsset grimoire_8 = { "equip_grimoire_grimoire_8"_hs, "assets/textures/equipment/grimoire/grimoire_8.png" };

        constexpr std::array<const TextureAsset*, 9> All = {
            &grimoire_0,
            &grimoire_1,
            &grimoire_2,
            &grimoire_3,
            &grimoire_4,
            &grimoire_5,
            &grimoire_6,
            &grimoire_7,
            &grimoire_8
        };
    } // namespace grimoire

    namespace hammer {
        inline constexpr TextureAsset hammer_0 = { "equip_hammer_hammer_0"_hs, "assets/textures/equipment/hammer/hammer_0.png" };
        inline constexpr TextureAsset hammer_1 = { "equip_hammer_hammer_1"_hs, "assets/textures/equipment/hammer/hammer_1.png" };
        inline constexpr TextureAsset hammer_2 = { "equip_hammer_hammer_2"_hs, "assets/textures/equipment/hammer/hammer_2.png" };
        inline constexpr TextureAsset hammer_3 = { "equip_hammer_hammer_3"_hs, "assets/textures/equipment/hammer/hammer_3.png" };
        inline constexpr TextureAsset hammer_4 = { "equip_hammer_hammer_4"_hs, "assets/textures/equipment/hammer/hammer_4.png" };
        inline constexpr TextureAsset hammer_5 = { "equip_hammer_hammer_5"_hs, "assets/textures/equipment/hammer/hammer_5.png" };
        inline constexpr TextureAsset hammer_6 = { "equip_hammer_hammer_6"_hs, "assets/textures/equipment/hammer/hammer_6.png" };
        inline constexpr TextureAsset hammer_7 = { "equip_hammer_hammer_7"_hs, "assets/textures/equipment/hammer/hammer_7.png" };
        inline constexpr TextureAsset hammer_8 = { "equip_hammer_hammer_8"_hs, "assets/textures/equipment/hammer/hammer_8.png" };
        inline constexpr TextureAsset hammer_9 = { "equip_hammer_hammer_9"_hs, "assets/textures/equipment/hammer/hammer_9.png" };

        constexpr std::array<const TextureAsset*, 10> All = {
            &hammer_0,
            &hammer_1,
            &hammer_2,
            &hammer_3,
            &hammer_4,
            &hammer_5,
            &hammer_6,
            &hammer_7,
            &hammer_8,
            &hammer_9
        };
    } // namespace hammer

    namespace helmet {
        inline constexpr TextureAsset helmet_0 = { "equip_helmet_helmet_0"_hs, "assets/textures/equipment/helmet/helmet_0.png" };
        inline constexpr TextureAsset helmet_1 = { "equip_helmet_helmet_1"_hs, "assets/textures/equipment/helmet/helmet_1.png" };
        inline constexpr TextureAsset helmet_2 = { "equip_helmet_helmet_2"_hs, "assets/textures/equipment/helmet/helmet_2.png" };
        inline constexpr TextureAsset helmet_3 = { "equip_helmet_helmet_3"_hs, "assets/textures/equipment/helmet/helmet_3.png" };
        inline constexpr TextureAsset helmet_4 = { "equip_helmet_helmet_4"_hs, "assets/textures/equipment/helmet/helmet_4.png" };
        inline constexpr TextureAsset helmet_5 = { "equip_helmet_helmet_5"_hs, "assets/textures/equipment/helmet/helmet_5.png" };
        inline constexpr TextureAsset helmet_6 = { "equip_helmet_helmet_6"_hs, "assets/textures/equipment/helmet/helmet_6.png" };
        inline constexpr TextureAsset helmet_7 = { "equip_helmet_helmet_7"_hs, "assets/textures/equipment/helmet/helmet_7.png" };
        inline constexpr TextureAsset helmet_8 = { "equip_helmet_helmet_8"_hs, "assets/textures/equipment/helmet/helmet_8.png" };
        inline constexpr TextureAsset helmet_9 = { "equip_helmet_helmet_9"_hs, "assets/textures/equipment/helmet/helmet_9.png" };

        constexpr std::array<const TextureAsset*, 10> All = {
            &helmet_0,
            &helmet_1,
            &helmet_2,
            &helmet_3,
            &helmet_4,
            &helmet_5,
            &helmet_6,
            &helmet_7,
            &helmet_8,
            &helmet_9
        };
    } // namespace helmet

    namespace leggings {
        inline constexpr TextureAsset leggings_0 = { "equip_leggings_leggings_0"_hs, "assets/textures/equipment/leggings/leggings_0.png" };
        inline constexpr TextureAsset leggings_1 = { "equip_leggings_leggings_1"_hs, "assets/textures/equipment/leggings/leggings_1.png" };
        inline constexpr TextureAsset leggings_2 = { "equip_leggings_leggings_2"_hs, "assets/textures/equipment/leggings/leggings_2.png" };
        inline constexpr TextureAsset leggings_3 = { "equip_leggings_leggings_3"_hs, "assets/textures/equipment/leggings/leggings_3.png" };
        inline constexpr TextureAsset leggings_4 = { "equip_leggings_leggings_4"_hs, "assets/textures/equipment/leggings/leggings_4.png" };
        inline constexpr TextureAsset leggings_5 = { "equip_leggings_leggings_5"_hs, "assets/textures/equipment/leggings/leggings_5.png" };
        inline constexpr TextureAsset leggings_6 = { "equip_leggings_leggings_6"_hs, "assets/textures/equipment/leggings/leggings_6.png" };
        inline constexpr TextureAsset leggings_7 = { "equip_leggings_leggings_7"_hs, "assets/textures/equipment/leggings/leggings_7.png" };
        inline constexpr TextureAsset leggings_8 = { "equip_leggings_leggings_8"_hs, "assets/textures/equipment/leggings/leggings_8.png" };
        inline constexpr TextureAsset leggings_9 = { "equip_leggings_leggings_9"_hs, "assets/textures/equipment/leggings/leggings_9.png" };

        constexpr std::array<const TextureAsset*, 10> All = {
            &leggings_0,
            &leggings_1,
            &leggings_2,
            &leggings_3,
            &leggings_4,
            &leggings_5,
            &leggings_6,
            &leggings_7,
            &leggings_8,
            &leggings_9
        };
    } // namespace leggings

    namespace orb {
        inline constexpr TextureAsset orb_0 = { "equip_orb_orb_0"_hs, "assets/textures/equipment/orb/orb_0.png" };
        inline constexpr TextureAsset orb_1 = { "equip_orb_orb_1"_hs, "assets/textures/equipment/orb/orb_1.png" };
        inline constexpr TextureAsset orb_2 = { "equip_orb_orb_2"_hs, "assets/textures/equipment/orb/orb_2.png" };
        inline constexpr TextureAsset orb_3 = { "equip_orb_orb_3"_hs, "assets/textures/equipment/orb/orb_3.png" };
        inline constexpr TextureAsset orb_4 = { "equip_orb_orb_4"_hs, "assets/textures/equipment/orb/orb_4.png" };
        inline constexpr TextureAsset orb_5 = { "equip_orb_orb_5"_hs, "assets/textures/equipment/orb/orb_5.png" };
        inline constexpr TextureAsset orb_6 = { "equip_orb_orb_6"_hs, "assets/textures/equipment/orb/orb_6.png" };
        inline constexpr TextureAsset orb_7 = { "equip_orb_orb_7"_hs, "assets/textures/equipment/orb/orb_7.png" };
        inline constexpr TextureAsset orb_8 = { "equip_orb_orb_8"_hs, "assets/textures/equipment/orb/orb_8.png" };

        constexpr std::array<const TextureAsset*, 9> All = {
            &orb_0,
            &orb_1,
            &orb_2,
            &orb_3,
            &orb_4,
            &orb_5,
            &orb_6,
            &orb_7,
            &orb_8
        };
    } // namespace orb

    namespace pauldrons {
        inline constexpr TextureAsset pauldrons_0 = { "equip_pauldrons_pauldrons_0"_hs, "assets/textures/equipment/pauldrons/pauldrons_0.png" };
        inline constexpr TextureAsset pauldrons_1 = { "equip_pauldrons_pauldrons_1"_hs, "assets/textures/equipment/pauldrons/pauldrons_1.png" };
        inline constexpr TextureAsset pauldrons_2 = { "equip_pauldrons_pauldrons_2"_hs, "assets/textures/equipment/pauldrons/pauldrons_2.png" };
        inline constexpr TextureAsset pauldrons_3 = { "equip_pauldrons_pauldrons_3"_hs, "assets/textures/equipment/pauldrons/pauldrons_3.png" };
        inline constexpr TextureAsset pauldrons_4 = { "equip_pauldrons_pauldrons_4"_hs, "assets/textures/equipment/pauldrons/pauldrons_4.png" };
        inline constexpr TextureAsset pauldrons_5 = { "equip_pauldrons_pauldrons_5"_hs, "assets/textures/equipment/pauldrons/pauldrons_5.png" };
        inline constexpr TextureAsset pauldrons_6 = { "equip_pauldrons_pauldrons_6"_hs, "assets/textures/equipment/pauldrons/pauldrons_6.png" };
        inline constexpr TextureAsset pauldrons_7 = { "equip_pauldrons_pauldrons_7"_hs, "assets/textures/equipment/pauldrons/pauldrons_7.png" };
        inline constexpr TextureAsset pauldrons_8 = { "equip_pauldrons_pauldrons_8"_hs, "assets/textures/equipment/pauldrons/pauldrons_8.png" };
        inline constexpr TextureAsset pauldrons_9 = { "equip_pauldrons_pauldrons_9"_hs, "assets/textures/equipment/pauldrons/pauldrons_9.png" };

        constexpr std::array<const TextureAsset*, 10> All = {
            &pauldrons_0,
            &pauldrons_1,
            &pauldrons_2,
            &pauldrons_3,
            &pauldrons_4,
            &pauldrons_5,
            &pauldrons_6,
            &pauldrons_7,
            &pauldrons_8,
            &pauldrons_9
        };
    } // namespace pauldrons

    namespace ring {
        inline constexpr TextureAsset ring_0 = { "equip_ring_ring_0"_hs, "assets/textures/equipment/ring/ring_0.png" };
        inline constexpr TextureAsset ring_1 = { "equip_ring_ring_1"_hs, "assets/textures/equipment/ring/ring_1.png" };
        inline constexpr TextureAsset ring_2 = { "equip_ring_ring_2"_hs, "assets/textures/equipment/ring/ring_2.png" };
        inline constexpr TextureAsset ring_3 = { "equip_ring_ring_3"_hs, "assets/textures/equipment/ring/ring_3.png" };
        inline constexpr TextureAsset ring_4 = { "equip_ring_ring_4"_hs, "assets/textures/equipment/ring/ring_4.png" };
        inline constexpr TextureAsset ring_5 = { "equip_ring_ring_5"_hs, "assets/textures/equipment/ring/ring_5.png" };
        inline constexpr TextureAsset ring_6 = { "equip_ring_ring_6"_hs, "assets/textures/equipment/ring/ring_6.png" };
        inline constexpr TextureAsset ring_7 = { "equip_ring_ring_7"_hs, "assets/textures/equipment/ring/ring_7.png" };
        inline constexpr TextureAsset ring_8 = { "equip_ring_ring_8"_hs, "assets/textures/equipment/ring/ring_8.png" };
        inline constexpr TextureAsset ring_9 = { "equip_ring_ring_9"_hs, "assets/textures/equipment/ring/ring_9.png" };

        constexpr std::array<const TextureAsset*, 10> All = {
            &ring_0,
            &ring_1,
            &ring_2,
            &ring_3,
            &ring_4,
            &ring_5,
            &ring_6,
            &ring_7,
            &ring_8,
            &ring_9
        };
    } // namespace ring

    namespace shield {
        inline constexpr TextureAsset shield_0 = { "equip_shield_shield_0"_hs, "assets/textures/equipment/shield/shield_0.png" };
        inline constexpr TextureAsset shield_1 = { "equip_shield_shield_1"_hs, "assets/textures/equipment/shield/shield_1.png" };
        inline constexpr TextureAsset shield_2 = { "equip_shield_shield_2"_hs, "assets/textures/equipment/shield/shield_2.png" };
        inline constexpr TextureAsset shield_3 = { "equip_shield_shield_3"_hs, "assets/textures/equipment/shield/shield_3.png" };
        inline constexpr TextureAsset shield_4 = { "equip_shield_shield_4"_hs, "assets/textures/equipment/shield/shield_4.png" };
        inline constexpr TextureAsset shield_5 = { "equip_shield_shield_5"_hs, "assets/textures/equipment/shield/shield_5.png" };
        inline constexpr TextureAsset shield_6 = { "equip_shield_shield_6"_hs, "assets/textures/equipment/shield/shield_6.png" };
        inline constexpr TextureAsset shield_7 = { "equip_shield_shield_7"_hs, "assets/textures/equipment/shield/shield_7.png" };
        inline constexpr TextureAsset shield_8 = { "equip_shield_shield_8"_hs, "assets/textures/equipment/shield/shield_8.png" };

        constexpr std::array<const TextureAsset*, 9> All = {
            &shield_0,
            &shield_1,
            &shield_2,
            &shield_3,
            &shield_4,
            &shield_5,
            &shield_6,
            &shield_7,
            &shield_8
        };
    } // namespace shield

    namespace staff {
        inline constexpr TextureAsset staff_0 = { "equip_staff_staff_0"_hs, "assets/textures/equipment/staff/staff_0.png" };
        inline constexpr TextureAsset staff_1 = { "equip_staff_staff_1"_hs, "assets/textures/equipment/staff/staff_1.png" };
        inline constexpr TextureAsset staff_2 = { "equip_staff_staff_2"_hs, "assets/textures/equipment/staff/staff_2.png" };
        inline constexpr TextureAsset staff_3 = { "equip_staff_staff_3"_hs, "assets/textures/equipment/staff/staff_3.png" };
        inline constexpr TextureAsset staff_4 = { "equip_staff_staff_4"_hs, "assets/textures/equipment/staff/staff_4.png" };
        inline constexpr TextureAsset staff_5 = { "equip_staff_staff_5"_hs, "assets/textures/equipment/staff/staff_5.png" };
        inline constexpr TextureAsset staff_6 = { "equip_staff_staff_6"_hs, "assets/textures/equipment/staff/staff_6.png" };
        inline constexpr TextureAsset staff_7 = { "equip_staff_staff_7"_hs, "assets/textures/equipment/staff/staff_7.png" };
        inline constexpr TextureAsset staff_8 = { "equip_staff_staff_8"_hs, "assets/textures/equipment/staff/staff_8.png" };
        inline constexpr TextureAsset staff_9 = { "equip_staff_staff_9"_hs, "assets/textures/equipment/staff/staff_9.png" };

        constexpr std::array<const TextureAsset*, 10> All = {
            &staff_0,
            &staff_1,
            &staff_2,
            &staff_3,
            &staff_4,
            &staff_5,
            &staff_6,
            &staff_7,
            &staff_8,
            &staff_9
        };
    } // namespace staff

    namespace sword {
        inline constexpr TextureAsset sword_0 = { "equip_sword_sword_0"_hs, "assets/textures/equipment/sword/sword_0.png" };
        inline constexpr TextureAsset sword_1 = { "equip_sword_sword_1"_hs, "assets/textures/equipment/sword/sword_1.png" };
        inline constexpr TextureAsset sword_10 = { "equip_sword_sword_10"_hs, "assets/textures/equipment/sword/sword_10.png" };
        inline constexpr TextureAsset sword_2 = { "equip_sword_sword_2"_hs, "assets/textures/equipment/sword/sword_2.png" };
        inline constexpr TextureAsset sword_3 = { "equip_sword_sword_3"_hs, "assets/textures/equipment/sword/sword_3.png" };
        inline constexpr TextureAsset sword_4 = { "equip_sword_sword_4"_hs, "assets/textures/equipment/sword/sword_4.png" };
        inline constexpr TextureAsset sword_5 = { "equip_sword_sword_5"_hs, "assets/textures/equipment/sword/sword_5.png" };
        inline constexpr TextureAsset sword_6 = { "equip_sword_sword_6"_hs, "assets/textures/equipment/sword/sword_6.png" };
        inline constexpr TextureAsset sword_7 = { "equip_sword_sword_7"_hs, "assets/textures/equipment/sword/sword_7.png" };
        inline constexpr TextureAsset sword_8 = { "equip_sword_sword_8"_hs, "assets/textures/equipment/sword/sword_8.png" };
        inline constexpr TextureAsset sword_9 = { "equip_sword_sword_9"_hs, "assets/textures/equipment/sword/sword_9.png" };

        constexpr std::array<const TextureAsset*, 11> All = {
            &sword_0,
            &sword_1,
            &sword_10,
            &sword_2,
            &sword_3,
            &sword_4,
            &sword_5,
            &sword_6,
            &sword_7,
            &sword_8,
            &sword_9
        };
    } // namespace sword

    namespace wand {
        inline constexpr TextureAsset wand_0 = { "equip_wand_wand_0"_hs, "assets/textures/equipment/wand/wand_0.png" };
        inline constexpr TextureAsset wand_1 = { "equip_wand_wand_1"_hs, "assets/textures/equipment/wand/wand_1.png" };
        inline constexpr TextureAsset wand_2 = { "equip_wand_wand_2"_hs, "assets/textures/equipment/wand/wand_2.png" };
        inline constexpr TextureAsset wand_3 = { "equip_wand_wand_3"_hs, "assets/textures/equipment/wand/wand_3.png" };
        inline constexpr TextureAsset wand_4 = { "equip_wand_wand_4"_hs, "assets/textures/equipment/wand/wand_4.png" };
        inline constexpr TextureAsset wand_5 = { "equip_wand_wand_5"_hs, "assets/textures/equipment/wand/wand_5.png" };
        inline constexpr TextureAsset wand_6 = { "equip_wand_wand_6"_hs, "assets/textures/equipment/wand/wand_6.png" };
        inline constexpr TextureAsset wand_7 = { "equip_wand_wand_7"_hs, "assets/textures/equipment/wand/wand_7.png" };
        inline constexpr TextureAsset wand_8 = { "equip_wand_wand_8"_hs, "assets/textures/equipment/wand/wand_8.png" };
        inline constexpr TextureAsset wand_9 = { "equip_wand_wand_9"_hs, "assets/textures/equipment/wand/wand_9.png" };

        constexpr std::array<const TextureAsset*, 10> All = {
            &wand_0,
            &wand_1,
            &wand_2,
            &wand_3,
            &wand_4,
            &wand_5,
            &wand_6,
            &wand_7,
            &wand_8,
            &wand_9
        };
    } // namespace wand

} // namespace assets::equipment