#pragma once
// This file is auto-generated by scripts/gen_asset_registries.py
// Do not modify this file directly. Run the script to regenerate.

#include "engine/resource/AssetRegistry.hpp"
#include <array>

using namespace entt::literals;

namespace assets::monsters {

    namespace general {
        // 野兽
        inline constexpr TextureAsset beast_0 = { "monster_beast_0"_hs, "assets/textures/monster/beast_0.png" };
        inline constexpr TextureAsset beast_1 = { "monster_beast_1"_hs, "assets/textures/monster/beast_1.png" };
        inline constexpr TextureAsset beast_2 = { "monster_beast_2"_hs, "assets/textures/monster/beast_2.png" };
        inline constexpr TextureAsset beast_3 = { "monster_beast_3"_hs, "assets/textures/monster/beast_3.png" };
        inline constexpr TextureAsset beast_4 = { "monster_beast_4"_hs, "assets/textures/monster/beast_4.png" };
        // 邪教徒
        inline constexpr TextureAsset cultist_0 = { "monster_cultist_0"_hs, "assets/textures/monster/cultist_0.png" };
        inline constexpr TextureAsset cultist_1 = { "monster_cultist_1"_hs, "assets/textures/monster/cultist_1.png" };
        inline constexpr TextureAsset cultist_2 = { "monster_cultist_2"_hs, "assets/textures/monster/cultist_2.png" };
        inline constexpr TextureAsset cultist_3 = { "monster_cultist_3"_hs, "assets/textures/monster/cultist_3.png" };
        inline constexpr TextureAsset cultist_4 = { "monster_cultist_4"_hs, "assets/textures/monster/cultist_4.png" };
        // 恶魔
        inline constexpr TextureAsset demon_0 = { "monster_demon_0"_hs, "assets/textures/monster/demon_0.png" };
        inline constexpr TextureAsset demon_1 = { "monster_demon_1"_hs, "assets/textures/monster/demon_1.png" };
        inline constexpr TextureAsset demon_2 = { "monster_demon_2"_hs, "assets/textures/monster/demon_2.png" };
        inline constexpr TextureAsset demon_3 = { "monster_demon_3"_hs, "assets/textures/monster/demon_3.png" };
        inline constexpr TextureAsset demon_4 = { "monster_demon_4"_hs, "assets/textures/monster/demon_4.png" };
        // 元素
        inline constexpr TextureAsset elemental_0 = { "monster_elemental_0"_hs, "assets/textures/monster/elemental_0.png" };
        inline constexpr TextureAsset elemental_1 = { "monster_elemental_1"_hs, "assets/textures/monster/elemental_1.png" };
        inline constexpr TextureAsset elemental_2 = { "monster_elemental_2"_hs, "assets/textures/monster/elemental_2.png" };
        inline constexpr TextureAsset elemental_3 = { "monster_elemental_3"_hs, "assets/textures/monster/elemental_3.png" };
        inline constexpr TextureAsset elemental_4 = { "monster_elemental_4"_hs, "assets/textures/monster/elemental_4.png" };
        // 精灵
        inline constexpr TextureAsset elf_0 = { "monster_elf_0"_hs, "assets/textures/monster/elf_0.png" };
        inline constexpr TextureAsset elf_1 = { "monster_elf_1"_hs, "assets/textures/monster/elf_1.png" };
        inline constexpr TextureAsset elf_2 = { "monster_elf_2"_hs, "assets/textures/monster/elf_2.png" };
        inline constexpr TextureAsset elf_3 = { "monster_elf_3"_hs, "assets/textures/monster/elf_3.png" };
        inline constexpr TextureAsset elf_4 = { "monster_elf_4"_hs, "assets/textures/monster/elf_4.png" };
        // 哥布林
        inline constexpr TextureAsset goblin_0 = { "monster_goblin_0"_hs, "assets/textures/monster/goblin_0.png" };
        inline constexpr TextureAsset goblin_1 = { "monster_goblin_1"_hs, "assets/textures/monster/goblin_1.png" };
        inline constexpr TextureAsset goblin_2 = { "monster_goblin_2"_hs, "assets/textures/monster/goblin_2.png" };
        inline constexpr TextureAsset goblin_3 = { "monster_goblin_3"_hs, "assets/textures/monster/goblin_3.png" };
        inline constexpr TextureAsset goblin_4 = { "monster_goblin_4"_hs, "assets/textures/monster/goblin_4.png" };
        // 机械
        inline constexpr TextureAsset mech_0 = { "monster_mech_0"_hs, "assets/textures/monster/mech_0.png" };
        inline constexpr TextureAsset mech_1 = { "monster_mech_1"_hs, "assets/textures/monster/mech_1.png" };
        inline constexpr TextureAsset mech_2 = { "monster_mech_2"_hs, "assets/textures/monster/mech_2.png" };
        inline constexpr TextureAsset mech_3 = { "monster_mech_3"_hs, "assets/textures/monster/mech_3.png" };
        inline constexpr TextureAsset mech_4 = { "monster_mech_4"_hs, "assets/textures/monster/mech_4.png" };
        // 骷髅
        inline constexpr TextureAsset skeleton_0 = { "monster_skeleton_0"_hs, "assets/textures/monster/skeleton_0.png" };
        inline constexpr TextureAsset skeleton_1 = { "monster_skeleton_1"_hs, "assets/textures/monster/skeleton_1.png" };
        inline constexpr TextureAsset skeleton_2 = { "monster_skeleton_2"_hs, "assets/textures/monster/skeleton_2.png" };
        inline constexpr TextureAsset skeleton_3 = { "monster_skeleton_3"_hs, "assets/textures/monster/skeleton_3.png" };
        inline constexpr TextureAsset skeleton_4 = { "monster_skeleton_4"_hs, "assets/textures/monster/skeleton_4.png" };
        // 兽人
        inline constexpr TextureAsset warcraft_0 = { "monster_warcraft_0"_hs, "assets/textures/monster/warcraft_0.png" };
        inline constexpr TextureAsset warcraft_1 = { "monster_warcraft_1"_hs, "assets/textures/monster/warcraft_1.png" };
        inline constexpr TextureAsset warcraft_2 = { "monster_warcraft_2"_hs, "assets/textures/monster/warcraft_2.png" };
        inline constexpr TextureAsset warcraft_3 = { "monster_warcraft_3"_hs, "assets/textures/monster/warcraft_3.png" };
        inline constexpr TextureAsset warcraft_4 = { "monster_warcraft_4"_hs, "assets/textures/monster/warcraft_4.png" };

        constexpr std::array<const TextureAsset*, 45> All = {
            &beast_0,
            &beast_1,
            &beast_2,
            &beast_3,
            &beast_4,
            &cultist_0,
            &cultist_1,
            &cultist_2,
            &cultist_3,
            &cultist_4,
            &demon_0,
            &demon_1,
            &demon_2,
            &demon_3,
            &demon_4,
            &elemental_0,
            &elemental_1,
            &elemental_2,
            &elemental_3,
            &elemental_4,
            &elf_0,
            &elf_1,
            &elf_2,
            &elf_3,
            &elf_4,
            &goblin_0,
            &goblin_1,
            &goblin_2,
            &goblin_3,
            &goblin_4,
            &mech_0,
            &mech_1,
            &mech_2,
            &mech_3,
            &mech_4,
            &skeleton_0,
            &skeleton_1,
            &skeleton_2,
            &skeleton_3,
            &skeleton_4,
            &warcraft_0,
            &warcraft_1,
            &warcraft_2,
            &warcraft_3,
            &warcraft_4
        };
    } // namespace general

} // namespace assets::monsters