#pragma once
// This file is auto-generated by scripts/gen_asset_registries.py
// Do not modify this file directly. Run the script to regenerate.

#include "engine/resource/AssetRegistry.hpp"
#include <array>

using namespace entt::literals;

namespace assets::runes {

    namespace general {
        inline constexpr TextureAsset rune_1 = { "rune_rune_1"_hs, "assets/textures/icons/materials/runes/rune_1.png" };
        inline constexpr TextureAsset rune_10 = { "rune_rune_10"_hs, "assets/textures/icons/materials/runes/rune_10.png" };
        inline constexpr TextureAsset rune_11 = { "rune_rune_11"_hs, "assets/textures/icons/materials/runes/rune_11.png" };
        inline constexpr TextureAsset rune_12 = { "rune_rune_12"_hs, "assets/textures/icons/materials/runes/rune_12.png" };
        inline constexpr TextureAsset rune_13 = { "rune_rune_13"_hs, "assets/textures/icons/materials/runes/rune_13.png" };
        inline constexpr TextureAsset rune_14 = { "rune_rune_14"_hs, "assets/textures/icons/materials/runes/rune_14.png" };
        inline constexpr TextureAsset rune_15 = { "rune_rune_15"_hs, "assets/textures/icons/materials/runes/rune_15.png" };
        inline constexpr TextureAsset rune_16 = { "rune_rune_16"_hs, "assets/textures/icons/materials/runes/rune_16.png" };
        inline constexpr TextureAsset rune_17 = { "rune_rune_17"_hs, "assets/textures/icons/materials/runes/rune_17.png" };
        inline constexpr TextureAsset rune_18 = { "rune_rune_18"_hs, "assets/textures/icons/materials/runes/rune_18.png" };
        inline constexpr TextureAsset rune_19 = { "rune_rune_19"_hs, "assets/textures/icons/materials/runes/rune_19.png" };
        inline constexpr TextureAsset rune_2 = { "rune_rune_2"_hs, "assets/textures/icons/materials/runes/rune_2.png" };
        inline constexpr TextureAsset rune_20 = { "rune_rune_20"_hs, "assets/textures/icons/materials/runes/rune_20.png" };
        inline constexpr TextureAsset rune_21 = { "rune_rune_21"_hs, "assets/textures/icons/materials/runes/rune_21.png" };
        inline constexpr TextureAsset rune_22 = { "rune_rune_22"_hs, "assets/textures/icons/materials/runes/rune_22.png" };
        inline constexpr TextureAsset rune_23 = { "rune_rune_23"_hs, "assets/textures/icons/materials/runes/rune_23.png" };
        inline constexpr TextureAsset rune_24 = { "rune_rune_24"_hs, "assets/textures/icons/materials/runes/rune_24.png" };
        inline constexpr TextureAsset rune_25 = { "rune_rune_25"_hs, "assets/textures/icons/materials/runes/rune_25.png" };
        inline constexpr TextureAsset rune_26 = { "rune_rune_26"_hs, "assets/textures/icons/materials/runes/rune_26.png" };
        inline constexpr TextureAsset rune_27 = { "rune_rune_27"_hs, "assets/textures/icons/materials/runes/rune_27.png" };
        inline constexpr TextureAsset rune_28 = { "rune_rune_28"_hs, "assets/textures/icons/materials/runes/rune_28.png" };
        inline constexpr TextureAsset rune_29 = { "rune_rune_29"_hs, "assets/textures/icons/materials/runes/rune_29.png" };
        inline constexpr TextureAsset rune_3 = { "rune_rune_3"_hs, "assets/textures/icons/materials/runes/rune_3.png" };
        inline constexpr TextureAsset rune_30 = { "rune_rune_30"_hs, "assets/textures/icons/materials/runes/rune_30.png" };
        inline constexpr TextureAsset rune_31 = { "rune_rune_31"_hs, "assets/textures/icons/materials/runes/rune_31.png" };
        inline constexpr TextureAsset rune_32 = { "rune_rune_32"_hs, "assets/textures/icons/materials/runes/rune_32.png" };
        inline constexpr TextureAsset rune_33 = { "rune_rune_33"_hs, "assets/textures/icons/materials/runes/rune_33.png" };
        inline constexpr TextureAsset rune_4 = { "rune_rune_4"_hs, "assets/textures/icons/materials/runes/rune_4.png" };
        inline constexpr TextureAsset rune_5 = { "rune_rune_5"_hs, "assets/textures/icons/materials/runes/rune_5.png" };
        inline constexpr TextureAsset rune_6 = { "rune_rune_6"_hs, "assets/textures/icons/materials/runes/rune_6.png" };
        inline constexpr TextureAsset rune_7 = { "rune_rune_7"_hs, "assets/textures/icons/materials/runes/rune_7.png" };
        inline constexpr TextureAsset rune_8 = { "rune_rune_8"_hs, "assets/textures/icons/materials/runes/rune_8.png" };
        inline constexpr TextureAsset rune_9 = { "rune_rune_9"_hs, "assets/textures/icons/materials/runes/rune_9.png" };

        constexpr std::array<const TextureAsset*, 33> All = {
            &rune_1,
            &rune_10,
            &rune_11,
            &rune_12,
            &rune_13,
            &rune_14,
            &rune_15,
            &rune_16,
            &rune_17,
            &rune_18,
            &rune_19,
            &rune_2,
            &rune_20,
            &rune_21,
            &rune_22,
            &rune_23,
            &rune_24,
            &rune_25,
            &rune_26,
            &rune_27,
            &rune_28,
            &rune_29,
            &rune_3,
            &rune_30,
            &rune_31,
            &rune_32,
            &rune_33,
            &rune_4,
            &rune_5,
            &rune_6,
            &rune_7,
            &rune_8,
            &rune_9
        };
    } // namespace general

} // namespace assets::runes