#pragma once
// This file is auto-generated by scripts/gen_asset_registries.py
// Do not modify this file directly. Run the script to regenerate.

#include "engine/resource/AssetRegistry.hpp"
#include <array>
#include <cstdint>

using namespace entt::literals;

namespace assets::skill_nodes {

    inline constexpr TextureAsset node_100 = { "skill_node_100"_hs, "assets/textures/skill_nodes/skill_nodes_100.png" };
    inline constexpr TextureAsset node_101 = { "skill_node_101"_hs, "assets/textures/skill_nodes/skill_nodes_101.png" };
    inline constexpr TextureAsset node_102 = { "skill_node_102"_hs, "assets/textures/skill_nodes/skill_nodes_102.png" };
    inline constexpr TextureAsset node_103 = { "skill_node_103"_hs, "assets/textures/skill_nodes/skill_nodes_103.png" };
    inline constexpr TextureAsset node_110 = { "skill_node_110"_hs, "assets/textures/skill_nodes/skill_nodes_110.png" };
    inline constexpr TextureAsset node_111 = { "skill_node_111"_hs, "assets/textures/skill_nodes/skill_nodes_111.png" };
    inline constexpr TextureAsset node_112 = { "skill_node_112"_hs, "assets/textures/skill_nodes/skill_nodes_112.png" };
    inline constexpr TextureAsset node_113 = { "skill_node_113"_hs, "assets/textures/skill_nodes/skill_nodes_113.png" };
    inline constexpr TextureAsset node_114 = { "skill_node_114"_hs, "assets/textures/skill_nodes/skill_nodes_114.png" };
    inline constexpr TextureAsset node_115 = { "skill_node_115"_hs, "assets/textures/skill_nodes/skill_nodes_115.png" };
    inline constexpr TextureAsset node_130 = { "skill_node_130"_hs, "assets/textures/skill_nodes/skill_nodes_130.png" };
    inline constexpr TextureAsset node_131 = { "skill_node_131"_hs, "assets/textures/skill_nodes/skill_nodes_131.png" };
    inline constexpr TextureAsset node_132 = { "skill_node_132"_hs, "assets/textures/skill_nodes/skill_nodes_132.png" };
    inline constexpr TextureAsset node_133 = { "skill_node_133"_hs, "assets/textures/skill_nodes/skill_nodes_133.png" };
    inline constexpr TextureAsset node_134 = { "skill_node_134"_hs, "assets/textures/skill_nodes/skill_nodes_134.png" };
    inline constexpr TextureAsset node_135 = { "skill_node_135"_hs, "assets/textures/skill_nodes/skill_nodes_135.png" };
    inline constexpr TextureAsset node_150 = { "skill_node_150"_hs, "assets/textures/skill_nodes/skill_nodes_150.png" };
    inline constexpr TextureAsset node_151 = { "skill_node_151"_hs, "assets/textures/skill_nodes/skill_nodes_151.png" };
    inline constexpr TextureAsset node_152 = { "skill_node_152"_hs, "assets/textures/skill_nodes/skill_nodes_152.png" };
    inline constexpr TextureAsset node_153 = { "skill_node_153"_hs, "assets/textures/skill_nodes/skill_nodes_153.png" };
    inline constexpr TextureAsset node_154 = { "skill_node_154"_hs, "assets/textures/skill_nodes/skill_nodes_154.png" };
    inline constexpr TextureAsset node_155 = { "skill_node_155"_hs, "assets/textures/skill_nodes/skill_nodes_155.png" };
    inline constexpr TextureAsset node_170 = { "skill_node_170"_hs, "assets/textures/skill_nodes/skill_nodes_170.png" };
    inline constexpr TextureAsset node_171 = { "skill_node_171"_hs, "assets/textures/skill_nodes/skill_nodes_171.png" };
    inline constexpr TextureAsset node_172 = { "skill_node_172"_hs, "assets/textures/skill_nodes/skill_nodes_172.png" };
    inline constexpr TextureAsset node_173 = { "skill_node_173"_hs, "assets/textures/skill_nodes/skill_nodes_173.png" };
    inline constexpr TextureAsset node_174 = { "skill_node_174"_hs, "assets/textures/skill_nodes/skill_nodes_174.png" };
    inline constexpr TextureAsset node_175 = { "skill_node_175"_hs, "assets/textures/skill_nodes/skill_nodes_175.png" };
    inline constexpr TextureAsset node_200 = { "skill_node_200"_hs, "assets/textures/skill_nodes/skill_nodes_200.png" };
    inline constexpr TextureAsset node_201 = { "skill_node_201"_hs, "assets/textures/skill_nodes/skill_nodes_201.png" };
    inline constexpr TextureAsset node_202 = { "skill_node_202"_hs, "assets/textures/skill_nodes/skill_nodes_202.png" };
    inline constexpr TextureAsset node_203 = { "skill_node_203"_hs, "assets/textures/skill_nodes/skill_nodes_203.png" };
    inline constexpr TextureAsset node_210 = { "skill_node_210"_hs, "assets/textures/skill_nodes/skill_nodes_210.png" };
    inline constexpr TextureAsset node_211 = { "skill_node_211"_hs, "assets/textures/skill_nodes/skill_nodes_211.png" };
    inline constexpr TextureAsset node_212 = { "skill_node_212"_hs, "assets/textures/skill_nodes/skill_nodes_212.png" };
    inline constexpr TextureAsset node_213 = { "skill_node_213"_hs, "assets/textures/skill_nodes/skill_nodes_213.png" };
    inline constexpr TextureAsset node_214 = { "skill_node_214"_hs, "assets/textures/skill_nodes/skill_nodes_214.png" };
    inline constexpr TextureAsset node_215 = { "skill_node_215"_hs, "assets/textures/skill_nodes/skill_nodes_215.png" };
    inline constexpr TextureAsset node_230 = { "skill_node_230"_hs, "assets/textures/skill_nodes/skill_nodes_230.png" };
    inline constexpr TextureAsset node_231 = { "skill_node_231"_hs, "assets/textures/skill_nodes/skill_nodes_231.png" };
    inline constexpr TextureAsset node_232 = { "skill_node_232"_hs, "assets/textures/skill_nodes/skill_nodes_232.png" };
    inline constexpr TextureAsset node_233 = { "skill_node_233"_hs, "assets/textures/skill_nodes/skill_nodes_233.png" };
    inline constexpr TextureAsset node_234 = { "skill_node_234"_hs, "assets/textures/skill_nodes/skill_nodes_234.png" };
    inline constexpr TextureAsset node_235 = { "skill_node_235"_hs, "assets/textures/skill_nodes/skill_nodes_235.png" };
    inline constexpr TextureAsset node_250 = { "skill_node_250"_hs, "assets/textures/skill_nodes/skill_nodes_250.png" };
    inline constexpr TextureAsset node_251 = { "skill_node_251"_hs, "assets/textures/skill_nodes/skill_nodes_251.png" };
    inline constexpr TextureAsset node_252 = { "skill_node_252"_hs, "assets/textures/skill_nodes/skill_nodes_252.png" };
    inline constexpr TextureAsset node_253 = { "skill_node_253"_hs, "assets/textures/skill_nodes/skill_nodes_253.png" };
    inline constexpr TextureAsset node_254 = { "skill_node_254"_hs, "assets/textures/skill_nodes/skill_nodes_254.png" };
    inline constexpr TextureAsset node_255 = { "skill_node_255"_hs, "assets/textures/skill_nodes/skill_nodes_255.png" };
    inline constexpr TextureAsset node_270 = { "skill_node_270"_hs, "assets/textures/skill_nodes/skill_nodes_270.png" };
    inline constexpr TextureAsset node_271 = { "skill_node_271"_hs, "assets/textures/skill_nodes/skill_nodes_271.png" };
    inline constexpr TextureAsset node_272 = { "skill_node_272"_hs, "assets/textures/skill_nodes/skill_nodes_272.png" };
    inline constexpr TextureAsset node_273 = { "skill_node_273"_hs, "assets/textures/skill_nodes/skill_nodes_273.png" };
    inline constexpr TextureAsset node_274 = { "skill_node_274"_hs, "assets/textures/skill_nodes/skill_nodes_274.png" };
    inline constexpr TextureAsset node_275 = { "skill_node_275"_hs, "assets/textures/skill_nodes/skill_nodes_275.png" };
    inline constexpr TextureAsset node_300 = { "skill_node_300"_hs, "assets/textures/skill_nodes/skill_nodes_300.png" };
    inline constexpr TextureAsset node_301 = { "skill_node_301"_hs, "assets/textures/skill_nodes/skill_nodes_301.png" };
    inline constexpr TextureAsset node_302 = { "skill_node_302"_hs, "assets/textures/skill_nodes/skill_nodes_302.png" };
    inline constexpr TextureAsset node_303 = { "skill_node_303"_hs, "assets/textures/skill_nodes/skill_nodes_303.png" };
    inline constexpr TextureAsset node_310 = { "skill_node_310"_hs, "assets/textures/skill_nodes/skill_nodes_310.png" };
    inline constexpr TextureAsset node_311 = { "skill_node_311"_hs, "assets/textures/skill_nodes/skill_nodes_311.png" };
    inline constexpr TextureAsset node_312 = { "skill_node_312"_hs, "assets/textures/skill_nodes/skill_nodes_312.png" };
    inline constexpr TextureAsset node_313 = { "skill_node_313"_hs, "assets/textures/skill_nodes/skill_nodes_313.png" };
    inline constexpr TextureAsset node_314 = { "skill_node_314"_hs, "assets/textures/skill_nodes/skill_nodes_314.png" };
    inline constexpr TextureAsset node_315 = { "skill_node_315"_hs, "assets/textures/skill_nodes/skill_nodes_315.png" };
    inline constexpr TextureAsset node_330 = { "skill_node_330"_hs, "assets/textures/skill_nodes/skill_nodes_330.png" };
    inline constexpr TextureAsset node_331 = { "skill_node_331"_hs, "assets/textures/skill_nodes/skill_nodes_331.png" };
    inline constexpr TextureAsset node_332 = { "skill_node_332"_hs, "assets/textures/skill_nodes/skill_nodes_332.png" };
    inline constexpr TextureAsset node_333 = { "skill_node_333"_hs, "assets/textures/skill_nodes/skill_nodes_333.png" };
    inline constexpr TextureAsset node_334 = { "skill_node_334"_hs, "assets/textures/skill_nodes/skill_nodes_334.png" };
    inline constexpr TextureAsset node_335 = { "skill_node_335"_hs, "assets/textures/skill_nodes/skill_nodes_335.png" };
    inline constexpr TextureAsset node_350 = { "skill_node_350"_hs, "assets/textures/skill_nodes/skill_nodes_350.png" };
    inline constexpr TextureAsset node_351 = { "skill_node_351"_hs, "assets/textures/skill_nodes/skill_nodes_351.png" };
    inline constexpr TextureAsset node_352 = { "skill_node_352"_hs, "assets/textures/skill_nodes/skill_nodes_352.png" };
    inline constexpr TextureAsset node_353 = { "skill_node_353"_hs, "assets/textures/skill_nodes/skill_nodes_353.png" };
    inline constexpr TextureAsset node_354 = { "skill_node_354"_hs, "assets/textures/skill_nodes/skill_nodes_354.png" };
    inline constexpr TextureAsset node_355 = { "skill_node_355"_hs, "assets/textures/skill_nodes/skill_nodes_355.png" };
    inline constexpr TextureAsset node_370 = { "skill_node_370"_hs, "assets/textures/skill_nodes/skill_nodes_370.png" };
    inline constexpr TextureAsset node_371 = { "skill_node_371"_hs, "assets/textures/skill_nodes/skill_nodes_371.png" };
    inline constexpr TextureAsset node_372 = { "skill_node_372"_hs, "assets/textures/skill_nodes/skill_nodes_372.png" };
    inline constexpr TextureAsset node_373 = { "skill_node_373"_hs, "assets/textures/skill_nodes/skill_nodes_373.png" };
    inline constexpr TextureAsset node_374 = { "skill_node_374"_hs, "assets/textures/skill_nodes/skill_nodes_374.png" };
    inline constexpr TextureAsset node_375 = { "skill_node_375"_hs, "assets/textures/skill_nodes/skill_nodes_375.png" };
    inline constexpr TextureAsset node_400 = { "skill_node_400"_hs, "assets/textures/skill_nodes/skill_nodes_400.png" };
    inline constexpr TextureAsset node_401 = { "skill_node_401"_hs, "assets/textures/skill_nodes/skill_nodes_401.png" };
    inline constexpr TextureAsset node_402 = { "skill_node_402"_hs, "assets/textures/skill_nodes/skill_nodes_402.png" };
    inline constexpr TextureAsset node_403 = { "skill_node_403"_hs, "assets/textures/skill_nodes/skill_nodes_403.png" };
    inline constexpr TextureAsset node_410 = { "skill_node_410"_hs, "assets/textures/skill_nodes/skill_nodes_410.png" };
    inline constexpr TextureAsset node_411 = { "skill_node_411"_hs, "assets/textures/skill_nodes/skill_nodes_411.png" };
    inline constexpr TextureAsset node_412 = { "skill_node_412"_hs, "assets/textures/skill_nodes/skill_nodes_412.png" };
    inline constexpr TextureAsset node_413 = { "skill_node_413"_hs, "assets/textures/skill_nodes/skill_nodes_413.png" };
    inline constexpr TextureAsset node_414 = { "skill_node_414"_hs, "assets/textures/skill_nodes/skill_nodes_414.png" };
    inline constexpr TextureAsset node_415 = { "skill_node_415"_hs, "assets/textures/skill_nodes/skill_nodes_415.png" };
    inline constexpr TextureAsset node_430 = { "skill_node_430"_hs, "assets/textures/skill_nodes/skill_nodes_430.png" };
    inline constexpr TextureAsset node_431 = { "skill_node_431"_hs, "assets/textures/skill_nodes/skill_nodes_431.png" };
    inline constexpr TextureAsset node_432 = { "skill_node_432"_hs, "assets/textures/skill_nodes/skill_nodes_432.png" };
    inline constexpr TextureAsset node_433 = { "skill_node_433"_hs, "assets/textures/skill_nodes/skill_nodes_433.png" };
    inline constexpr TextureAsset node_434 = { "skill_node_434"_hs, "assets/textures/skill_nodes/skill_nodes_434.png" };
    inline constexpr TextureAsset node_435 = { "skill_node_435"_hs, "assets/textures/skill_nodes/skill_nodes_435.png" };
    inline constexpr TextureAsset node_450 = { "skill_node_450"_hs, "assets/textures/skill_nodes/skill_nodes_450.png" };
    inline constexpr TextureAsset node_451 = { "skill_node_451"_hs, "assets/textures/skill_nodes/skill_nodes_451.png" };
    inline constexpr TextureAsset node_452 = { "skill_node_452"_hs, "assets/textures/skill_nodes/skill_nodes_452.png" };
    inline constexpr TextureAsset node_453 = { "skill_node_453"_hs, "assets/textures/skill_nodes/skill_nodes_453.png" };
    inline constexpr TextureAsset node_454 = { "skill_node_454"_hs, "assets/textures/skill_nodes/skill_nodes_454.png" };
    inline constexpr TextureAsset node_455 = { "skill_node_455"_hs, "assets/textures/skill_nodes/skill_nodes_455.png" };
    inline constexpr TextureAsset node_470 = { "skill_node_470"_hs, "assets/textures/skill_nodes/skill_nodes_470.png" };
    inline constexpr TextureAsset node_471 = { "skill_node_471"_hs, "assets/textures/skill_nodes/skill_nodes_471.png" };
    inline constexpr TextureAsset node_472 = { "skill_node_472"_hs, "assets/textures/skill_nodes/skill_nodes_472.png" };
    inline constexpr TextureAsset node_473 = { "skill_node_473"_hs, "assets/textures/skill_nodes/skill_nodes_473.png" };
    inline constexpr TextureAsset node_474 = { "skill_node_474"_hs, "assets/textures/skill_nodes/skill_nodes_474.png" };
    inline constexpr TextureAsset node_475 = { "skill_node_475"_hs, "assets/textures/skill_nodes/skill_nodes_475.png" };
    inline constexpr TextureAsset node_476 = { "skill_node_476"_hs, "assets/textures/skill_nodes/skill_nodes_476.png" };
    inline constexpr TextureAsset node_500 = { "skill_node_500"_hs, "assets/textures/skill_nodes/skill_nodes_500.png" };
    inline constexpr TextureAsset node_501 = { "skill_node_501"_hs, "assets/textures/skill_nodes/skill_nodes_501.png" };
    inline constexpr TextureAsset node_502 = { "skill_node_502"_hs, "assets/textures/skill_nodes/skill_nodes_502.png" };
    inline constexpr TextureAsset node_503 = { "skill_node_503"_hs, "assets/textures/skill_nodes/skill_nodes_503.png" };
    inline constexpr TextureAsset node_510 = { "skill_node_510"_hs, "assets/textures/skill_nodes/skill_nodes_510.png" };
    inline constexpr TextureAsset node_511 = { "skill_node_511"_hs, "assets/textures/skill_nodes/skill_nodes_511.png" };
    inline constexpr TextureAsset node_512 = { "skill_node_512"_hs, "assets/textures/skill_nodes/skill_nodes_512.png" };
    inline constexpr TextureAsset node_513 = { "skill_node_513"_hs, "assets/textures/skill_nodes/skill_nodes_513.png" };
    inline constexpr TextureAsset node_514 = { "skill_node_514"_hs, "assets/textures/skill_nodes/skill_nodes_514.png" };
    inline constexpr TextureAsset node_515 = { "skill_node_515"_hs, "assets/textures/skill_nodes/skill_nodes_515.png" };
    inline constexpr TextureAsset node_530 = { "skill_node_530"_hs, "assets/textures/skill_nodes/skill_nodes_530.png" };
    inline constexpr TextureAsset node_531 = { "skill_node_531"_hs, "assets/textures/skill_nodes/skill_nodes_531.png" };
    inline constexpr TextureAsset node_532 = { "skill_node_532"_hs, "assets/textures/skill_nodes/skill_nodes_532.png" };
    inline constexpr TextureAsset node_533 = { "skill_node_533"_hs, "assets/textures/skill_nodes/skill_nodes_533.png" };
    inline constexpr TextureAsset node_534 = { "skill_node_534"_hs, "assets/textures/skill_nodes/skill_nodes_534.png" };
    inline constexpr TextureAsset node_535 = { "skill_node_535"_hs, "assets/textures/skill_nodes/skill_nodes_535.png" };
    inline constexpr TextureAsset node_550 = { "skill_node_550"_hs, "assets/textures/skill_nodes/skill_nodes_550.png" };
    inline constexpr TextureAsset node_551 = { "skill_node_551"_hs, "assets/textures/skill_nodes/skill_nodes_551.png" };
    inline constexpr TextureAsset node_552 = { "skill_node_552"_hs, "assets/textures/skill_nodes/skill_nodes_552.png" };
    inline constexpr TextureAsset node_553 = { "skill_node_553"_hs, "assets/textures/skill_nodes/skill_nodes_553.png" };
    inline constexpr TextureAsset node_554 = { "skill_node_554"_hs, "assets/textures/skill_nodes/skill_nodes_554.png" };
    inline constexpr TextureAsset node_555 = { "skill_node_555"_hs, "assets/textures/skill_nodes/skill_nodes_555.png" };
    inline constexpr TextureAsset node_570 = { "skill_node_570"_hs, "assets/textures/skill_nodes/skill_nodes_570.png" };
    inline constexpr TextureAsset node_571 = { "skill_node_571"_hs, "assets/textures/skill_nodes/skill_nodes_571.png" };
    inline constexpr TextureAsset node_572 = { "skill_node_572"_hs, "assets/textures/skill_nodes/skill_nodes_572.png" };
    inline constexpr TextureAsset node_573 = { "skill_node_573"_hs, "assets/textures/skill_nodes/skill_nodes_573.png" };
    inline constexpr TextureAsset node_574 = { "skill_node_574"_hs, "assets/textures/skill_nodes/skill_nodes_574.png" };
    inline constexpr TextureAsset node_575 = { "skill_node_575"_hs, "assets/textures/skill_nodes/skill_nodes_575.png" };
    inline constexpr TextureAsset node_600 = { "skill_node_600"_hs, "assets/textures/skill_nodes/skill_nodes_600.png" };
    inline constexpr TextureAsset node_601 = { "skill_node_601"_hs, "assets/textures/skill_nodes/skill_nodes_601.png" };
    inline constexpr TextureAsset node_602 = { "skill_node_602"_hs, "assets/textures/skill_nodes/skill_nodes_602.png" };
    inline constexpr TextureAsset node_603 = { "skill_node_603"_hs, "assets/textures/skill_nodes/skill_nodes_603.png" };
    inline constexpr TextureAsset node_610 = { "skill_node_610"_hs, "assets/textures/skill_nodes/skill_nodes_610.png" };
    inline constexpr TextureAsset node_611 = { "skill_node_611"_hs, "assets/textures/skill_nodes/skill_nodes_611.png" };
    inline constexpr TextureAsset node_612 = { "skill_node_612"_hs, "assets/textures/skill_nodes/skill_nodes_612.png" };
    inline constexpr TextureAsset node_613 = { "skill_node_613"_hs, "assets/textures/skill_nodes/skill_nodes_613.png" };
    inline constexpr TextureAsset node_614 = { "skill_node_614"_hs, "assets/textures/skill_nodes/skill_nodes_614.png" };
    inline constexpr TextureAsset node_615 = { "skill_node_615"_hs, "assets/textures/skill_nodes/skill_nodes_615.png" };
    inline constexpr TextureAsset node_630 = { "skill_node_630"_hs, "assets/textures/skill_nodes/skill_nodes_630.png" };
    inline constexpr TextureAsset node_631 = { "skill_node_631"_hs, "assets/textures/skill_nodes/skill_nodes_631.png" };
    inline constexpr TextureAsset node_632 = { "skill_node_632"_hs, "assets/textures/skill_nodes/skill_nodes_632.png" };
    inline constexpr TextureAsset node_633 = { "skill_node_633"_hs, "assets/textures/skill_nodes/skill_nodes_633.png" };
    inline constexpr TextureAsset node_634 = { "skill_node_634"_hs, "assets/textures/skill_nodes/skill_nodes_634.png" };
    inline constexpr TextureAsset node_635 = { "skill_node_635"_hs, "assets/textures/skill_nodes/skill_nodes_635.png" };
    inline constexpr TextureAsset node_650 = { "skill_node_650"_hs, "assets/textures/skill_nodes/skill_nodes_650.png" };
    inline constexpr TextureAsset node_651 = { "skill_node_651"_hs, "assets/textures/skill_nodes/skill_nodes_651.png" };
    inline constexpr TextureAsset node_652 = { "skill_node_652"_hs, "assets/textures/skill_nodes/skill_nodes_652.png" };
    inline constexpr TextureAsset node_653 = { "skill_node_653"_hs, "assets/textures/skill_nodes/skill_nodes_653.png" };
    inline constexpr TextureAsset node_654 = { "skill_node_654"_hs, "assets/textures/skill_nodes/skill_nodes_654.png" };
    inline constexpr TextureAsset node_655 = { "skill_node_655"_hs, "assets/textures/skill_nodes/skill_nodes_655.png" };
    inline constexpr TextureAsset node_670 = { "skill_node_670"_hs, "assets/textures/skill_nodes/skill_nodes_670.png" };
    inline constexpr TextureAsset node_671 = { "skill_node_671"_hs, "assets/textures/skill_nodes/skill_nodes_671.png" };
    inline constexpr TextureAsset node_672 = { "skill_node_672"_hs, "assets/textures/skill_nodes/skill_nodes_672.png" };
    inline constexpr TextureAsset node_673 = { "skill_node_673"_hs, "assets/textures/skill_nodes/skill_nodes_673.png" };
    inline constexpr TextureAsset node_674 = { "skill_node_674"_hs, "assets/textures/skill_nodes/skill_nodes_674.png" };
    inline constexpr TextureAsset node_675 = { "skill_node_675"_hs, "assets/textures/skill_nodes/skill_nodes_675.png" };
    inline constexpr TextureAsset node_700 = { "skill_node_700"_hs, "assets/textures/skill_nodes/skill_nodes_700.png" };
    inline constexpr TextureAsset node_701 = { "skill_node_701"_hs, "assets/textures/skill_nodes/skill_nodes_701.png" };
    inline constexpr TextureAsset node_702 = { "skill_node_702"_hs, "assets/textures/skill_nodes/skill_nodes_702.png" };
    inline constexpr TextureAsset node_703 = { "skill_node_703"_hs, "assets/textures/skill_nodes/skill_nodes_703.png" };
    inline constexpr TextureAsset node_710 = { "skill_node_710"_hs, "assets/textures/skill_nodes/skill_nodes_710.png" };
    inline constexpr TextureAsset node_711 = { "skill_node_711"_hs, "assets/textures/skill_nodes/skill_nodes_711.png" };
    inline constexpr TextureAsset node_712 = { "skill_node_712"_hs, "assets/textures/skill_nodes/skill_nodes_712.png" };
    inline constexpr TextureAsset node_713 = { "skill_node_713"_hs, "assets/textures/skill_nodes/skill_nodes_713.png" };
    inline constexpr TextureAsset node_714 = { "skill_node_714"_hs, "assets/textures/skill_nodes/skill_nodes_714.png" };
    inline constexpr TextureAsset node_715 = { "skill_node_715"_hs, "assets/textures/skill_nodes/skill_nodes_715.png" };
    inline constexpr TextureAsset node_730 = { "skill_node_730"_hs, "assets/textures/skill_nodes/skill_nodes_730.png" };
    inline constexpr TextureAsset node_731 = { "skill_node_731"_hs, "assets/textures/skill_nodes/skill_nodes_731.png" };
    inline constexpr TextureAsset node_732 = { "skill_node_732"_hs, "assets/textures/skill_nodes/skill_nodes_732.png" };
    inline constexpr TextureAsset node_733 = { "skill_node_733"_hs, "assets/textures/skill_nodes/skill_nodes_733.png" };
    inline constexpr TextureAsset node_734 = { "skill_node_734"_hs, "assets/textures/skill_nodes/skill_nodes_734.png" };
    inline constexpr TextureAsset node_735 = { "skill_node_735"_hs, "assets/textures/skill_nodes/skill_nodes_735.png" };
    inline constexpr TextureAsset node_750 = { "skill_node_750"_hs, "assets/textures/skill_nodes/skill_nodes_750.png" };
    inline constexpr TextureAsset node_751 = { "skill_node_751"_hs, "assets/textures/skill_nodes/skill_nodes_751.png" };
    inline constexpr TextureAsset node_752 = { "skill_node_752"_hs, "assets/textures/skill_nodes/skill_nodes_752.png" };
    inline constexpr TextureAsset node_753 = { "skill_node_753"_hs, "assets/textures/skill_nodes/skill_nodes_753.png" };
    inline constexpr TextureAsset node_754 = { "skill_node_754"_hs, "assets/textures/skill_nodes/skill_nodes_754.png" };
    inline constexpr TextureAsset node_755 = { "skill_node_755"_hs, "assets/textures/skill_nodes/skill_nodes_755.png" };
    inline constexpr TextureAsset node_770 = { "skill_node_770"_hs, "assets/textures/skill_nodes/skill_nodes_770.png" };
    inline constexpr TextureAsset node_771 = { "skill_node_771"_hs, "assets/textures/skill_nodes/skill_nodes_771.png" };
    inline constexpr TextureAsset node_772 = { "skill_node_772"_hs, "assets/textures/skill_nodes/skill_nodes_772.png" };
    inline constexpr TextureAsset node_773 = { "skill_node_773"_hs, "assets/textures/skill_nodes/skill_nodes_773.png" };
    inline constexpr TextureAsset node_774 = { "skill_node_774"_hs, "assets/textures/skill_nodes/skill_nodes_774.png" };
    inline constexpr TextureAsset node_775 = { "skill_node_775"_hs, "assets/textures/skill_nodes/skill_nodes_775.png" };
    inline constexpr TextureAsset node_800 = { "skill_node_800"_hs, "assets/textures/skill_nodes/skill_nodes_800.png" };
    inline constexpr TextureAsset node_801 = { "skill_node_801"_hs, "assets/textures/skill_nodes/skill_nodes_801.png" };
    inline constexpr TextureAsset node_802 = { "skill_node_802"_hs, "assets/textures/skill_nodes/skill_nodes_802.png" };
    inline constexpr TextureAsset node_803 = { "skill_node_803"_hs, "assets/textures/skill_nodes/skill_nodes_803.png" };
    inline constexpr TextureAsset node_810 = { "skill_node_810"_hs, "assets/textures/skill_nodes/skill_nodes_810.png" };
    inline constexpr TextureAsset node_811 = { "skill_node_811"_hs, "assets/textures/skill_nodes/skill_nodes_811.png" };
    inline constexpr TextureAsset node_812 = { "skill_node_812"_hs, "assets/textures/skill_nodes/skill_nodes_812.png" };
    inline constexpr TextureAsset node_813 = { "skill_node_813"_hs, "assets/textures/skill_nodes/skill_nodes_813.png" };
    inline constexpr TextureAsset node_814 = { "skill_node_814"_hs, "assets/textures/skill_nodes/skill_nodes_814.png" };
    inline constexpr TextureAsset node_815 = { "skill_node_815"_hs, "assets/textures/skill_nodes/skill_nodes_815.png" };
    inline constexpr TextureAsset node_830 = { "skill_node_830"_hs, "assets/textures/skill_nodes/skill_nodes_830.png" };
    inline constexpr TextureAsset node_831 = { "skill_node_831"_hs, "assets/textures/skill_nodes/skill_nodes_831.png" };
    inline constexpr TextureAsset node_832 = { "skill_node_832"_hs, "assets/textures/skill_nodes/skill_nodes_832.png" };
    inline constexpr TextureAsset node_833 = { "skill_node_833"_hs, "assets/textures/skill_nodes/skill_nodes_833.png" };
    inline constexpr TextureAsset node_834 = { "skill_node_834"_hs, "assets/textures/skill_nodes/skill_nodes_834.png" };
    inline constexpr TextureAsset node_835 = { "skill_node_835"_hs, "assets/textures/skill_nodes/skill_nodes_835.png" };
    inline constexpr TextureAsset node_850 = { "skill_node_850"_hs, "assets/textures/skill_nodes/skill_nodes_850.png" };
    inline constexpr TextureAsset node_851 = { "skill_node_851"_hs, "assets/textures/skill_nodes/skill_nodes_851.png" };
    inline constexpr TextureAsset node_852 = { "skill_node_852"_hs, "assets/textures/skill_nodes/skill_nodes_852.png" };
    inline constexpr TextureAsset node_853 = { "skill_node_853"_hs, "assets/textures/skill_nodes/skill_nodes_853.png" };
    inline constexpr TextureAsset node_854 = { "skill_node_854"_hs, "assets/textures/skill_nodes/skill_nodes_854.png" };
    inline constexpr TextureAsset node_855 = { "skill_node_855"_hs, "assets/textures/skill_nodes/skill_nodes_855.png" };
    inline constexpr TextureAsset node_870 = { "skill_node_870"_hs, "assets/textures/skill_nodes/skill_nodes_870.png" };
    inline constexpr TextureAsset node_871 = { "skill_node_871"_hs, "assets/textures/skill_nodes/skill_nodes_871.png" };
    inline constexpr TextureAsset node_872 = { "skill_node_872"_hs, "assets/textures/skill_nodes/skill_nodes_872.png" };
    inline constexpr TextureAsset node_873 = { "skill_node_873"_hs, "assets/textures/skill_nodes/skill_nodes_873.png" };
    inline constexpr TextureAsset node_874 = { "skill_node_874"_hs, "assets/textures/skill_nodes/skill_nodes_874.png" };
    inline constexpr TextureAsset node_875 = { "skill_node_875"_hs, "assets/textures/skill_nodes/skill_nodes_875.png" };
    inline constexpr TextureAsset node_876 = { "skill_node_876"_hs, "assets/textures/skill_nodes/skill_nodes_876.png" };
    inline constexpr TextureAsset node_900 = { "skill_node_900"_hs, "assets/textures/skill_nodes/skill_nodes_900.png" };
    inline constexpr TextureAsset node_901 = { "skill_node_901"_hs, "assets/textures/skill_nodes/skill_nodes_901.png" };
    inline constexpr TextureAsset node_902 = { "skill_node_902"_hs, "assets/textures/skill_nodes/skill_nodes_902.png" };
    inline constexpr TextureAsset node_903 = { "skill_node_903"_hs, "assets/textures/skill_nodes/skill_nodes_903.png" };
    inline constexpr TextureAsset node_910 = { "skill_node_910"_hs, "assets/textures/skill_nodes/skill_nodes_910.png" };
    inline constexpr TextureAsset node_911 = { "skill_node_911"_hs, "assets/textures/skill_nodes/skill_nodes_911.png" };
    inline constexpr TextureAsset node_912 = { "skill_node_912"_hs, "assets/textures/skill_nodes/skill_nodes_912.png" };
    inline constexpr TextureAsset node_913 = { "skill_node_913"_hs, "assets/textures/skill_nodes/skill_nodes_913.png" };
    inline constexpr TextureAsset node_914 = { "skill_node_914"_hs, "assets/textures/skill_nodes/skill_nodes_914.png" };
    inline constexpr TextureAsset node_930 = { "skill_node_930"_hs, "assets/textures/skill_nodes/skill_nodes_930.png" };
    inline constexpr TextureAsset node_931 = { "skill_node_931"_hs, "assets/textures/skill_nodes/skill_nodes_931.png" };
    inline constexpr TextureAsset node_932 = { "skill_node_932"_hs, "assets/textures/skill_nodes/skill_nodes_932.png" };
    inline constexpr TextureAsset node_933 = { "skill_node_933"_hs, "assets/textures/skill_nodes/skill_nodes_933.png" };
    inline constexpr TextureAsset node_934 = { "skill_node_934"_hs, "assets/textures/skill_nodes/skill_nodes_934.png" };
    inline constexpr TextureAsset node_935 = { "skill_node_935"_hs, "assets/textures/skill_nodes/skill_nodes_935.png" };
    inline constexpr TextureAsset node_950 = { "skill_node_950"_hs, "assets/textures/skill_nodes/skill_nodes_950.png" };
    inline constexpr TextureAsset node_951 = { "skill_node_951"_hs, "assets/textures/skill_nodes/skill_nodes_951.png" };
    inline constexpr TextureAsset node_952 = { "skill_node_952"_hs, "assets/textures/skill_nodes/skill_nodes_952.png" };
    inline constexpr TextureAsset node_953 = { "skill_node_953"_hs, "assets/textures/skill_nodes/skill_nodes_953.png" };
    inline constexpr TextureAsset node_954 = { "skill_node_954"_hs, "assets/textures/skill_nodes/skill_nodes_954.png" };
    inline constexpr TextureAsset node_955 = { "skill_node_955"_hs, "assets/textures/skill_nodes/skill_nodes_955.png" };
    inline constexpr TextureAsset node_970 = { "skill_node_970"_hs, "assets/textures/skill_nodes/skill_nodes_970.png" };
    inline constexpr TextureAsset node_971 = { "skill_node_971"_hs, "assets/textures/skill_nodes/skill_nodes_971.png" };
    inline constexpr TextureAsset node_972 = { "skill_node_972"_hs, "assets/textures/skill_nodes/skill_nodes_972.png" };
    inline constexpr TextureAsset node_973 = { "skill_node_973"_hs, "assets/textures/skill_nodes/skill_nodes_973.png" };
    inline constexpr TextureAsset node_974 = { "skill_node_974"_hs, "assets/textures/skill_nodes/skill_nodes_974.png" };

    struct SkillNodeIconEntry {
        uint32_t node_id;
        entt::id_type icon_id;
        const TextureAsset* asset;
    };

    constexpr std::array<const TextureAsset*, 252> All = {
        &node_100,
        &node_101,
        &node_102,
        &node_103,
        &node_110,
        &node_111,
        &node_112,
        &node_113,
        &node_114,
        &node_115,
        &node_130,
        &node_131,
        &node_132,
        &node_133,
        &node_134,
        &node_135,
        &node_150,
        &node_151,
        &node_152,
        &node_153,
        &node_154,
        &node_155,
        &node_170,
        &node_171,
        &node_172,
        &node_173,
        &node_174,
        &node_175,
        &node_200,
        &node_201,
        &node_202,
        &node_203,
        &node_210,
        &node_211,
        &node_212,
        &node_213,
        &node_214,
        &node_215,
        &node_230,
        &node_231,
        &node_232,
        &node_233,
        &node_234,
        &node_235,
        &node_250,
        &node_251,
        &node_252,
        &node_253,
        &node_254,
        &node_255,
        &node_270,
        &node_271,
        &node_272,
        &node_273,
        &node_274,
        &node_275,
        &node_300,
        &node_301,
        &node_302,
        &node_303,
        &node_310,
        &node_311,
        &node_312,
        &node_313,
        &node_314,
        &node_315,
        &node_330,
        &node_331,
        &node_332,
        &node_333,
        &node_334,
        &node_335,
        &node_350,
        &node_351,
        &node_352,
        &node_353,
        &node_354,
        &node_355,
        &node_370,
        &node_371,
        &node_372,
        &node_373,
        &node_374,
        &node_375,
        &node_400,
        &node_401,
        &node_402,
        &node_403,
        &node_410,
        &node_411,
        &node_412,
        &node_413,
        &node_414,
        &node_415,
        &node_430,
        &node_431,
        &node_432,
        &node_433,
        &node_434,
        &node_435,
        &node_450,
        &node_451,
        &node_452,
        &node_453,
        &node_454,
        &node_455,
        &node_470,
        &node_471,
        &node_472,
        &node_473,
        &node_474,
        &node_475,
        &node_476,
        &node_500,
        &node_501,
        &node_502,
        &node_503,
        &node_510,
        &node_511,
        &node_512,
        &node_513,
        &node_514,
        &node_515,
        &node_530,
        &node_531,
        &node_532,
        &node_533,
        &node_534,
        &node_535,
        &node_550,
        &node_551,
        &node_552,
        &node_553,
        &node_554,
        &node_555,
        &node_570,
        &node_571,
        &node_572,
        &node_573,
        &node_574,
        &node_575,
        &node_600,
        &node_601,
        &node_602,
        &node_603,
        &node_610,
        &node_611,
        &node_612,
        &node_613,
        &node_614,
        &node_615,
        &node_630,
        &node_631,
        &node_632,
        &node_633,
        &node_634,
        &node_635,
        &node_650,
        &node_651,
        &node_652,
        &node_653,
        &node_654,
        &node_655,
        &node_670,
        &node_671,
        &node_672,
        &node_673,
        &node_674,
        &node_675,
        &node_700,
        &node_701,
        &node_702,
        &node_703,
        &node_710,
        &node_711,
        &node_712,
        &node_713,
        &node_714,
        &node_715,
        &node_730,
        &node_731,
        &node_732,
        &node_733,
        &node_734,
        &node_735,
        &node_750,
        &node_751,
        &node_752,
        &node_753,
        &node_754,
        &node_755,
        &node_770,
        &node_771,
        &node_772,
        &node_773,
        &node_774,
        &node_775,
        &node_800,
        &node_801,
        &node_802,
        &node_803,
        &node_810,
        &node_811,
        &node_812,
        &node_813,
        &node_814,
        &node_815,
        &node_830,
        &node_831,
        &node_832,
        &node_833,
        &node_834,
        &node_835,
        &node_850,
        &node_851,
        &node_852,
        &node_853,
        &node_854,
        &node_855,
        &node_870,
        &node_871,
        &node_872,
        &node_873,
        &node_874,
        &node_875,
        &node_876,
        &node_900,
        &node_901,
        &node_902,
        &node_903,
        &node_910,
        &node_911,
        &node_912,
        &node_913,
        &node_914,
        &node_930,
        &node_931,
        &node_932,
        &node_933,
        &node_934,
        &node_935,
        &node_950,
        &node_951,
        &node_952,
        &node_953,
        &node_954,
        &node_955,
        &node_970,
        &node_971,
        &node_972,
        &node_973,
        &node_974
    };

    constexpr std::array<SkillNodeIconEntry, 252> ByNodeId = {
        SkillNodeIconEntry{100u, node_100.id, &node_100},
        SkillNodeIconEntry{101u, node_101.id, &node_101},
        SkillNodeIconEntry{102u, node_102.id, &node_102},
        SkillNodeIconEntry{103u, node_103.id, &node_103},
        SkillNodeIconEntry{110u, node_110.id, &node_110},
        SkillNodeIconEntry{111u, node_111.id, &node_111},
        SkillNodeIconEntry{112u, node_112.id, &node_112},
        SkillNodeIconEntry{113u, node_113.id, &node_113},
        SkillNodeIconEntry{114u, node_114.id, &node_114},
        SkillNodeIconEntry{115u, node_115.id, &node_115},
        SkillNodeIconEntry{130u, node_130.id, &node_130},
        SkillNodeIconEntry{131u, node_131.id, &node_131},
        SkillNodeIconEntry{132u, node_132.id, &node_132},
        SkillNodeIconEntry{133u, node_133.id, &node_133},
        SkillNodeIconEntry{134u, node_134.id, &node_134},
        SkillNodeIconEntry{135u, node_135.id, &node_135},
        SkillNodeIconEntry{150u, node_150.id, &node_150},
        SkillNodeIconEntry{151u, node_151.id, &node_151},
        SkillNodeIconEntry{152u, node_152.id, &node_152},
        SkillNodeIconEntry{153u, node_153.id, &node_153},
        SkillNodeIconEntry{154u, node_154.id, &node_154},
        SkillNodeIconEntry{155u, node_155.id, &node_155},
        SkillNodeIconEntry{170u, node_170.id, &node_170},
        SkillNodeIconEntry{171u, node_171.id, &node_171},
        SkillNodeIconEntry{172u, node_172.id, &node_172},
        SkillNodeIconEntry{173u, node_173.id, &node_173},
        SkillNodeIconEntry{174u, node_174.id, &node_174},
        SkillNodeIconEntry{175u, node_175.id, &node_175},
        SkillNodeIconEntry{200u, node_200.id, &node_200},
        SkillNodeIconEntry{201u, node_201.id, &node_201},
        SkillNodeIconEntry{202u, node_202.id, &node_202},
        SkillNodeIconEntry{203u, node_203.id, &node_203},
        SkillNodeIconEntry{210u, node_210.id, &node_210},
        SkillNodeIconEntry{211u, node_211.id, &node_211},
        SkillNodeIconEntry{212u, node_212.id, &node_212},
        SkillNodeIconEntry{213u, node_213.id, &node_213},
        SkillNodeIconEntry{214u, node_214.id, &node_214},
        SkillNodeIconEntry{215u, node_215.id, &node_215},
        SkillNodeIconEntry{230u, node_230.id, &node_230},
        SkillNodeIconEntry{231u, node_231.id, &node_231},
        SkillNodeIconEntry{232u, node_232.id, &node_232},
        SkillNodeIconEntry{233u, node_233.id, &node_233},
        SkillNodeIconEntry{234u, node_234.id, &node_234},
        SkillNodeIconEntry{235u, node_235.id, &node_235},
        SkillNodeIconEntry{250u, node_250.id, &node_250},
        SkillNodeIconEntry{251u, node_251.id, &node_251},
        SkillNodeIconEntry{252u, node_252.id, &node_252},
        SkillNodeIconEntry{253u, node_253.id, &node_253},
        SkillNodeIconEntry{254u, node_254.id, &node_254},
        SkillNodeIconEntry{255u, node_255.id, &node_255},
        SkillNodeIconEntry{270u, node_270.id, &node_270},
        SkillNodeIconEntry{271u, node_271.id, &node_271},
        SkillNodeIconEntry{272u, node_272.id, &node_272},
        SkillNodeIconEntry{273u, node_273.id, &node_273},
        SkillNodeIconEntry{274u, node_274.id, &node_274},
        SkillNodeIconEntry{275u, node_275.id, &node_275},
        SkillNodeIconEntry{300u, node_300.id, &node_300},
        SkillNodeIconEntry{301u, node_301.id, &node_301},
        SkillNodeIconEntry{302u, node_302.id, &node_302},
        SkillNodeIconEntry{303u, node_303.id, &node_303},
        SkillNodeIconEntry{310u, node_310.id, &node_310},
        SkillNodeIconEntry{311u, node_311.id, &node_311},
        SkillNodeIconEntry{312u, node_312.id, &node_312},
        SkillNodeIconEntry{313u, node_313.id, &node_313},
        SkillNodeIconEntry{314u, node_314.id, &node_314},
        SkillNodeIconEntry{315u, node_315.id, &node_315},
        SkillNodeIconEntry{330u, node_330.id, &node_330},
        SkillNodeIconEntry{331u, node_331.id, &node_331},
        SkillNodeIconEntry{332u, node_332.id, &node_332},
        SkillNodeIconEntry{333u, node_333.id, &node_333},
        SkillNodeIconEntry{334u, node_334.id, &node_334},
        SkillNodeIconEntry{335u, node_335.id, &node_335},
        SkillNodeIconEntry{350u, node_350.id, &node_350},
        SkillNodeIconEntry{351u, node_351.id, &node_351},
        SkillNodeIconEntry{352u, node_352.id, &node_352},
        SkillNodeIconEntry{353u, node_353.id, &node_353},
        SkillNodeIconEntry{354u, node_354.id, &node_354},
        SkillNodeIconEntry{355u, node_355.id, &node_355},
        SkillNodeIconEntry{370u, node_370.id, &node_370},
        SkillNodeIconEntry{371u, node_371.id, &node_371},
        SkillNodeIconEntry{372u, node_372.id, &node_372},
        SkillNodeIconEntry{373u, node_373.id, &node_373},
        SkillNodeIconEntry{374u, node_374.id, &node_374},
        SkillNodeIconEntry{375u, node_375.id, &node_375},
        SkillNodeIconEntry{400u, node_400.id, &node_400},
        SkillNodeIconEntry{401u, node_401.id, &node_401},
        SkillNodeIconEntry{402u, node_402.id, &node_402},
        SkillNodeIconEntry{403u, node_403.id, &node_403},
        SkillNodeIconEntry{410u, node_410.id, &node_410},
        SkillNodeIconEntry{411u, node_411.id, &node_411},
        SkillNodeIconEntry{412u, node_412.id, &node_412},
        SkillNodeIconEntry{413u, node_413.id, &node_413},
        SkillNodeIconEntry{414u, node_414.id, &node_414},
        SkillNodeIconEntry{415u, node_415.id, &node_415},
        SkillNodeIconEntry{430u, node_430.id, &node_430},
        SkillNodeIconEntry{431u, node_431.id, &node_431},
        SkillNodeIconEntry{432u, node_432.id, &node_432},
        SkillNodeIconEntry{433u, node_433.id, &node_433},
        SkillNodeIconEntry{434u, node_434.id, &node_434},
        SkillNodeIconEntry{435u, node_435.id, &node_435},
        SkillNodeIconEntry{450u, node_450.id, &node_450},
        SkillNodeIconEntry{451u, node_451.id, &node_451},
        SkillNodeIconEntry{452u, node_452.id, &node_452},
        SkillNodeIconEntry{453u, node_453.id, &node_453},
        SkillNodeIconEntry{454u, node_454.id, &node_454},
        SkillNodeIconEntry{455u, node_455.id, &node_455},
        SkillNodeIconEntry{470u, node_470.id, &node_470},
        SkillNodeIconEntry{471u, node_471.id, &node_471},
        SkillNodeIconEntry{472u, node_472.id, &node_472},
        SkillNodeIconEntry{473u, node_473.id, &node_473},
        SkillNodeIconEntry{474u, node_474.id, &node_474},
        SkillNodeIconEntry{475u, node_475.id, &node_475},
        SkillNodeIconEntry{476u, node_476.id, &node_476},
        SkillNodeIconEntry{500u, node_500.id, &node_500},
        SkillNodeIconEntry{501u, node_501.id, &node_501},
        SkillNodeIconEntry{502u, node_502.id, &node_502},
        SkillNodeIconEntry{503u, node_503.id, &node_503},
        SkillNodeIconEntry{510u, node_510.id, &node_510},
        SkillNodeIconEntry{511u, node_511.id, &node_511},
        SkillNodeIconEntry{512u, node_512.id, &node_512},
        SkillNodeIconEntry{513u, node_513.id, &node_513},
        SkillNodeIconEntry{514u, node_514.id, &node_514},
        SkillNodeIconEntry{515u, node_515.id, &node_515},
        SkillNodeIconEntry{530u, node_530.id, &node_530},
        SkillNodeIconEntry{531u, node_531.id, &node_531},
        SkillNodeIconEntry{532u, node_532.id, &node_532},
        SkillNodeIconEntry{533u, node_533.id, &node_533},
        SkillNodeIconEntry{534u, node_534.id, &node_534},
        SkillNodeIconEntry{535u, node_535.id, &node_535},
        SkillNodeIconEntry{550u, node_550.id, &node_550},
        SkillNodeIconEntry{551u, node_551.id, &node_551},
        SkillNodeIconEntry{552u, node_552.id, &node_552},
        SkillNodeIconEntry{553u, node_553.id, &node_553},
        SkillNodeIconEntry{554u, node_554.id, &node_554},
        SkillNodeIconEntry{555u, node_555.id, &node_555},
        SkillNodeIconEntry{570u, node_570.id, &node_570},
        SkillNodeIconEntry{571u, node_571.id, &node_571},
        SkillNodeIconEntry{572u, node_572.id, &node_572},
        SkillNodeIconEntry{573u, node_573.id, &node_573},
        SkillNodeIconEntry{574u, node_574.id, &node_574},
        SkillNodeIconEntry{575u, node_575.id, &node_575},
        SkillNodeIconEntry{600u, node_600.id, &node_600},
        SkillNodeIconEntry{601u, node_601.id, &node_601},
        SkillNodeIconEntry{602u, node_602.id, &node_602},
        SkillNodeIconEntry{603u, node_603.id, &node_603},
        SkillNodeIconEntry{610u, node_610.id, &node_610},
        SkillNodeIconEntry{611u, node_611.id, &node_611},
        SkillNodeIconEntry{612u, node_612.id, &node_612},
        SkillNodeIconEntry{613u, node_613.id, &node_613},
        SkillNodeIconEntry{614u, node_614.id, &node_614},
        SkillNodeIconEntry{615u, node_615.id, &node_615},
        SkillNodeIconEntry{630u, node_630.id, &node_630},
        SkillNodeIconEntry{631u, node_631.id, &node_631},
        SkillNodeIconEntry{632u, node_632.id, &node_632},
        SkillNodeIconEntry{633u, node_633.id, &node_633},
        SkillNodeIconEntry{634u, node_634.id, &node_634},
        SkillNodeIconEntry{635u, node_635.id, &node_635},
        SkillNodeIconEntry{650u, node_650.id, &node_650},
        SkillNodeIconEntry{651u, node_651.id, &node_651},
        SkillNodeIconEntry{652u, node_652.id, &node_652},
        SkillNodeIconEntry{653u, node_653.id, &node_653},
        SkillNodeIconEntry{654u, node_654.id, &node_654},
        SkillNodeIconEntry{655u, node_655.id, &node_655},
        SkillNodeIconEntry{670u, node_670.id, &node_670},
        SkillNodeIconEntry{671u, node_671.id, &node_671},
        SkillNodeIconEntry{672u, node_672.id, &node_672},
        SkillNodeIconEntry{673u, node_673.id, &node_673},
        SkillNodeIconEntry{674u, node_674.id, &node_674},
        SkillNodeIconEntry{675u, node_675.id, &node_675},
        SkillNodeIconEntry{700u, node_700.id, &node_700},
        SkillNodeIconEntry{701u, node_701.id, &node_701},
        SkillNodeIconEntry{702u, node_702.id, &node_702},
        SkillNodeIconEntry{703u, node_703.id, &node_703},
        SkillNodeIconEntry{710u, node_710.id, &node_710},
        SkillNodeIconEntry{711u, node_711.id, &node_711},
        SkillNodeIconEntry{712u, node_712.id, &node_712},
        SkillNodeIconEntry{713u, node_713.id, &node_713},
        SkillNodeIconEntry{714u, node_714.id, &node_714},
        SkillNodeIconEntry{715u, node_715.id, &node_715},
        SkillNodeIconEntry{730u, node_730.id, &node_730},
        SkillNodeIconEntry{731u, node_731.id, &node_731},
        SkillNodeIconEntry{732u, node_732.id, &node_732},
        SkillNodeIconEntry{733u, node_733.id, &node_733},
        SkillNodeIconEntry{734u, node_734.id, &node_734},
        SkillNodeIconEntry{735u, node_735.id, &node_735},
        SkillNodeIconEntry{750u, node_750.id, &node_750},
        SkillNodeIconEntry{751u, node_751.id, &node_751},
        SkillNodeIconEntry{752u, node_752.id, &node_752},
        SkillNodeIconEntry{753u, node_753.id, &node_753},
        SkillNodeIconEntry{754u, node_754.id, &node_754},
        SkillNodeIconEntry{755u, node_755.id, &node_755},
        SkillNodeIconEntry{770u, node_770.id, &node_770},
        SkillNodeIconEntry{771u, node_771.id, &node_771},
        SkillNodeIconEntry{772u, node_772.id, &node_772},
        SkillNodeIconEntry{773u, node_773.id, &node_773},
        SkillNodeIconEntry{774u, node_774.id, &node_774},
        SkillNodeIconEntry{775u, node_775.id, &node_775},
        SkillNodeIconEntry{800u, node_800.id, &node_800},
        SkillNodeIconEntry{801u, node_801.id, &node_801},
        SkillNodeIconEntry{802u, node_802.id, &node_802},
        SkillNodeIconEntry{803u, node_803.id, &node_803},
        SkillNodeIconEntry{810u, node_810.id, &node_810},
        SkillNodeIconEntry{811u, node_811.id, &node_811},
        SkillNodeIconEntry{812u, node_812.id, &node_812},
        SkillNodeIconEntry{813u, node_813.id, &node_813},
        SkillNodeIconEntry{814u, node_814.id, &node_814},
        SkillNodeIconEntry{815u, node_815.id, &node_815},
        SkillNodeIconEntry{830u, node_830.id, &node_830},
        SkillNodeIconEntry{831u, node_831.id, &node_831},
        SkillNodeIconEntry{832u, node_832.id, &node_832},
        SkillNodeIconEntry{833u, node_833.id, &node_833},
        SkillNodeIconEntry{834u, node_834.id, &node_834},
        SkillNodeIconEntry{835u, node_835.id, &node_835},
        SkillNodeIconEntry{850u, node_850.id, &node_850},
        SkillNodeIconEntry{851u, node_851.id, &node_851},
        SkillNodeIconEntry{852u, node_852.id, &node_852},
        SkillNodeIconEntry{853u, node_853.id, &node_853},
        SkillNodeIconEntry{854u, node_854.id, &node_854},
        SkillNodeIconEntry{855u, node_855.id, &node_855},
        SkillNodeIconEntry{870u, node_870.id, &node_870},
        SkillNodeIconEntry{871u, node_871.id, &node_871},
        SkillNodeIconEntry{872u, node_872.id, &node_872},
        SkillNodeIconEntry{873u, node_873.id, &node_873},
        SkillNodeIconEntry{874u, node_874.id, &node_874},
        SkillNodeIconEntry{875u, node_875.id, &node_875},
        SkillNodeIconEntry{876u, node_876.id, &node_876},
        SkillNodeIconEntry{900u, node_900.id, &node_900},
        SkillNodeIconEntry{901u, node_901.id, &node_901},
        SkillNodeIconEntry{902u, node_902.id, &node_902},
        SkillNodeIconEntry{903u, node_903.id, &node_903},
        SkillNodeIconEntry{910u, node_910.id, &node_910},
        SkillNodeIconEntry{911u, node_911.id, &node_911},
        SkillNodeIconEntry{912u, node_912.id, &node_912},
        SkillNodeIconEntry{913u, node_913.id, &node_913},
        SkillNodeIconEntry{914u, node_914.id, &node_914},
        SkillNodeIconEntry{930u, node_930.id, &node_930},
        SkillNodeIconEntry{931u, node_931.id, &node_931},
        SkillNodeIconEntry{932u, node_932.id, &node_932},
        SkillNodeIconEntry{933u, node_933.id, &node_933},
        SkillNodeIconEntry{934u, node_934.id, &node_934},
        SkillNodeIconEntry{935u, node_935.id, &node_935},
        SkillNodeIconEntry{950u, node_950.id, &node_950},
        SkillNodeIconEntry{951u, node_951.id, &node_951},
        SkillNodeIconEntry{952u, node_952.id, &node_952},
        SkillNodeIconEntry{953u, node_953.id, &node_953},
        SkillNodeIconEntry{954u, node_954.id, &node_954},
        SkillNodeIconEntry{955u, node_955.id, &node_955},
        SkillNodeIconEntry{970u, node_970.id, &node_970},
        SkillNodeIconEntry{971u, node_971.id, &node_971},
        SkillNodeIconEntry{972u, node_972.id, &node_972},
        SkillNodeIconEntry{973u, node_973.id, &node_973},
        SkillNodeIconEntry{974u, node_974.id, &node_974}
    };

    inline constexpr entt::id_type FindIconId(uint32_t node_id) {
        for (const auto& entry : ByNodeId) {
            if (entry.node_id == node_id) {
                return entry.icon_id;
            }
        }
        return 0;
    }

    inline constexpr const TextureAsset* FindAsset(uint32_t node_id) {
        for (const auto& entry : ByNodeId) {
            if (entry.node_id == node_id) {
                return entry.asset;
            }
        }
        return nullptr;
    }

} // namespace assets::skill_nodes