#version 430
layout(local_size_x = 16, local_size_y = 16) in;
layout(r32ui, binding = 0) uniform uimage2D integrationImg;
uniform ivec2 targetCoord;

void main() {
    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(integrationImg);
    if (coord.x >= size.x || coord.y >= size.y) return;

    if (coord == targetCoord) {
        imageStore(integrationImg, coord, uvec4(0));
    } else {
        imageStore(integrationImg, coord, uvec4(65535)); // Max distance
    }
}
