#version 430

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 2) readonly buffer CounterBuffer {
  uint visibleCount;
};

struct DrawArraysIndirectCommand {
  uint count;
  uint instanceCount;
  uint first;
  uint baseInstance;
};

layout(std430, binding = 3) buffer IndirectBuffer {
  DrawArraysIndirectCommand cmd;
};

uniform int uMaxInstanceCount;

void main() {
  uint clampedCount = min(visibleCount, uint(max(uMaxInstanceCount, 0)));
  cmd.count = 6u;
  cmd.instanceCount = clampedCount;
  cmd.first = 0u;
  cmd.baseInstance = 0u;
}
