#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
import time
from pathlib import Path
from typing import Any


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def parse_gpu_abi_version(gpu_data_hpp: Path) -> int:
    text = read_text(gpu_data_hpp)
    match = re.search(r"GPU_ABI_VERSION\s*=\s*(\d+)", text)
    if not match:
        raise RuntimeError(f"GPU_ABI_VERSION not found in {gpu_data_hpp}")
    return int(match.group(1))


def parse_binding_enum(render_constants_hpp: Path) -> dict[str, int]:
    text = read_text(render_constants_hpp)
    enum_match = re.search(r"enum\s+class\s+Binding\s*:\s*uint32_t\s*{(.*?)};", text, re.S)
    if not enum_match:
        raise RuntimeError(f"Binding enum not found in {render_constants_hpp}")

    body = enum_match.group(1)
    values: dict[str, int] = {}
    for raw_line in body.splitlines():
        line = raw_line.split("//", 1)[0].strip()
        if not line or "=" not in line:
            continue
        left, right = line.split("=", 1)
        name = left.strip()
        expr = right.split(",", 1)[0].strip()
        if not name:
            continue

        if expr in values:
            values[name] = values[expr]
            continue
        try:
            values[name] = int(expr, 0)
            continue
        except ValueError:
            pass

        raise RuntimeError(
            f"Unresolved binding expression '{expr}' for '{name}' in {render_constants_hpp}"
        )

    return values


def resolve_binding_value(value: Any, binding_enum: dict[str, int]) -> int:
    if isinstance(value, int):
        return value
    if isinstance(value, str):
        if value not in binding_enum:
            raise RuntimeError(f"Binding symbol '{value}' not found in RenderConstants::Binding")
        return binding_enum[value]
    raise RuntimeError(f"Unsupported binding value type: {type(value)}")


def emit_struct(name: str, fields: list[dict[str, str]]) -> list[str]:
    lines = [f"struct {name} {{"]
    for field in fields:
        lines.append(f"    {field['type']} {field['name']};")
    lines.append("};")
    return lines


def build_gpu_abi_content(manifest: dict[str, Any], version: int, binding_enum: dict[str, int]) -> str:
    compat_min = max(0, version - 1)
    gpu_abi = manifest["gpu_abi"]
    lines: list[str] = [
        "// Auto-generated by tools/render_abi/generate_gpu_abi.py. Do not edit manually.",
        "#ifndef NOMOREDAY_GPU_ABI_GLSLINC",
        "#define NOMOREDAY_GPU_ABI_GLSLINC",
        "",
        f"#define GPU_ABI_VERSION {version}",
        f"#define GPU_ABI_COMPAT_MIN_VERSION {compat_min}",
        "",
    ]

    for macro_name, macro_value in gpu_abi["bindings"].items():
        resolved = resolve_binding_value(macro_value, binding_enum)
        lines.append(f"#ifndef {macro_name}")
        lines.append(f"#define {macro_name} {resolved}")
        lines.append("#endif")
        lines.append("")

    for struct_item in gpu_abi["structs"]:
        lines.extend(emit_struct(struct_item["name"], struct_item["fields"]))
        lines.append("")

    lines.append("#endif // NOMOREDAY_GPU_ABI_GLSLINC")
    lines.append("")
    return "\n".join(lines)


def build_material_abi_content(manifest: dict[str, Any]) -> str:
    material = manifest["material_abi"]
    lines: list[str] = [
        "// Auto-generated by tools/render_abi/generate_gpu_abi.py. Do not edit manually.",
        "#ifndef NOMOREDAY_MATERIAL_ABI_GLSLINC",
        "#define NOMOREDAY_MATERIAL_ABI_GLSLINC",
        "",
        '#include "gpu_abi.glslinc"',
        "",
        f"#ifndef {material['exposed_binding_macro']}",
        f"#define {material['exposed_binding_macro']} {material['binding_macro']}",
        "#endif",
        "",
    ]
    lines.extend(emit_struct(material["struct_name"], material["fields"]))
    lines.append("")
    lines.append(
        f"layout(std430, binding = {material['exposed_binding_macro']}) readonly buffer {material['buffer_name']} {{"
    )
    lines.append(f"    {material['struct_name']} materials[];")
    lines.append("};")
    lines.append("")
    lines.append("#endif // NOMOREDAY_MATERIAL_ABI_GLSLINC")
    lines.append("")
    return "\n".join(lines)


def check_or_write(path: Path, content: str, check: bool) -> bool:
    current = path.read_text(encoding="utf-8") if path.exists() else None
    changed = current != content
    if check:
        return changed
    if changed:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
    return changed


def main() -> int:
    root = Path(__file__).resolve().parents[2]

    parser = argparse.ArgumentParser(description="Generate GLSL ABI includes from governance manifest.")
    parser.add_argument("--manifest", type=Path, default=root / "tools/render_abi/abi_manifest.json")
    parser.add_argument("--gpu-data", type=Path, default=root / "src/engine/render/GPUData.hpp")
    parser.add_argument(
        "--render-constants", type=Path, default=root / "src/engine/render/RenderConstants.hpp"
    )
    parser.add_argument("--out-dir", type=Path, default=root / "assets/shaders/generated")
    parser.add_argument("--check", action="store_true", help="Fail if generated files differ from repo files.")
    args = parser.parse_args()

    start = time.perf_counter()
    manifest = json.loads(read_text(args.manifest))
    version = parse_gpu_abi_version(args.gpu_data)
    binding_enum = parse_binding_enum(args.render_constants)

    gpu_abi_content = build_gpu_abi_content(manifest, version, binding_enum)
    material_abi_content = build_material_abi_content(manifest)

    gpu_abi_path = args.out_dir / "gpu_abi.glslinc"
    material_abi_path = args.out_dir / "material_abi.glslinc"

    gpu_changed = check_or_write(gpu_abi_path, gpu_abi_content, args.check)
    material_changed = check_or_write(material_abi_path, material_abi_content, args.check)

    elapsed_s = time.perf_counter() - start
    mode = "check" if args.check else "write"
    print(
        f"[render_abi] mode={mode} gpu_abi_changed={gpu_changed} "
        f"material_abi_changed={material_changed} elapsed={elapsed_s:.3f}s"
    )

    if args.check and (gpu_changed or material_changed):
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

