import os
import datetime
import sys

def create_report_file(report_content):
    # Ensure output directory exists
    output_dir = os.path.join('conductor', 'analyzer')
    os.makedirs(output_dir, exist_ok=True)

    # Generate filename with timestamp
    # Format: YYYY-MM-DD_HH-MM-SS_code_analyze.md
    now = datetime.datetime.now()
    timestamp = now.strftime('%Y-%m-%d_%H-%M-%S')
    filename = f"{timestamp}_code_analyze.md"
    filepath = os.path.join(output_dir, filename)

    # Write content
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(report_content)
    
    print(f"Report saved to: {filepath}")
    return filepath

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python generate_report.py <path_to_content_file_or_string>")
        # Default empty template if no content provided for testing
        create_report_file("# Code Analysis Report\n\n*Generated by Code Risk Analyzer*")
    else:
        # If argument is a file path, read it
        input_arg = sys.argv[1]
        content = ""
        if os.path.exists(input_arg):
             with open(input_arg, 'r', encoding='utf-8') as f:
                content = f.read()
        else:
            # Treat as direct string content
            content = input_arg
            
        create_report_file(content)
