#pragma once

#include "game/application/states/GameplayState.hpp"
#include "game/foundation/SharedContext.hpp"
#include "engine/render/RenderContext.hpp"
#include "engine/resource/AssetRegistry.hpp"
  #include "engine/resource/ResourceManager.hpp"
  #include "engine/render/GPUUtils.hpp"
#include "engine/render/CoordSystem.hpp"
#include "game/application/scene/StateManager.hpp"
#include "core/math/UUID.hpp"
#include "game/foundation/components/EquipmentComponent.hpp"
#include "game/foundation/components/InventoryComponent.hpp"
#include "game/foundation/components/LightComponent.hpp"
#include "game/foundation/components/MaterialBankComponent.hpp" // Added
#include "game/foundation/components/PlayerProfile.hpp"
#include "game/foundation/components/PlayerState.hpp"
#include "game/foundation/components/StashComponent.hpp"
#include "game/foundation/components/MapFragmentComponent.hpp" // Added for Fragment Check
#include "game/foundation/data/PlayerCombatHistory.hpp"
#include "game/foundation/data/BiomeRegistry.hpp"
#include "game/foundation/data/BiomeTypes.hpp"
#include "game/foundation/data/SkillRegistry.hpp"
#include "game/foundation/registry/GroupRegistry.hpp"
#include "game/application/states/MosaicEditorState.hpp"
#include "game/application/states/DimensionalLevelSelectState.hpp" // Added
#include "game/application/states/PauseState.hpp"
#include "game/systems/item/ItemFactory.hpp"
#include "game/systems/item/InventorySystem.hpp" // Added
#include "game/systems/world/LevelManager.hpp"
#include "game/systems/world/MapSystem.hpp"    // Explicit include
#include "game/systems/world/PortalSystem.hpp" // Moved up
#include "game/systems/world/TilemapCollisionSystem.hpp"
#include "game/systems/world/WorldConstants.hpp"
#include "game/application/render/GameplayRenderAdapter.hpp"

// Utilities (formerly in PCH)
#include "core/utils/ScopedTimer.hpp"
#include "game/foundation/components/EnemyComponent.hpp"

// Systems
#include "game/application/input/InputSystem.hpp"
#include "game/application/ui/UiRuntimeTypes.hpp"
#include "game/systems/physics/PhysicsConstants.hpp"
#include "game/systems/physics/PhysicsSystem.hpp"
#include "engine/render/GPUEntitySystem.hpp"
#include "engine/render/GPUFlowFieldSystem.hpp"
#include "engine/render/GPUParticleSystem.hpp"
#include "engine/render/GPUSkillEffectSystem.hpp"
#include "engine/render/GPUTextSystem.hpp"
#include "engine/render/RenderSystem.hpp"
#include "engine/render/trail/GPUTrailRenderer.hpp"
#include "engine/render/core/QualityTierManager.hpp"
#include "engine/vfx/VFXSequenceManager.hpp"
#include "game/foundation/components/WorldState.hpp"
#include "game/foundation/components/vfx/MotionTrailComponent.hpp"
#include "game/systems/ai/AISystem.hpp"
#include "game/systems/combat/CombatConstants.hpp"
#include "game/systems/combat/CombatHistorySystem.hpp"
#include "game/systems/combat/BossFrameworkSystem.hpp"
#include "game/systems/combat/CombatSystem.hpp"
#include "game/contracts/impl/CombatTelemetry.hpp"
#include "game/systems/combat/DamagePopupManager.hpp"
#include "game/systems/combat/EffectSystem.hpp"
#include "game/systems/combat/EliteModifierSystem.hpp"
#include "game/systems/combat/HazardSystem.hpp"
#include "game/systems/combat/MonsterAffixSystem.hpp"
#include "game/contracts/impl/ProcBudgetManager.hpp"
#include "game/systems/combat/RegenerationSystem.hpp"
#include "game/contracts/impl/StatsSystem.hpp"
#include "game/systems/item/LootGridSystem.hpp"
#include "game/systems/combat/VisualFXSystem.hpp"
#include "game/systems/combat/XPAwardingSystem.hpp"
#include "game/systems/item/DropSystem.hpp"
#include "game/systems/item/FragmentDropSystem.hpp"
#include "game/systems/item/InventorySystem.hpp"
#include "game/systems/skill/ProjectileSystem.hpp"
#include "game/systems/skill/ShadowSystem.hpp"
#include "game/systems/skill/SkillSystem.hpp"
#include "game/systems/skill/SummonSystem.hpp"
#include "game/application/ui/GameUiHost.hpp"
#include "game/application/ui/MonsterHealthBarSystem.hpp"
#include "game/application/ui/UISystem.hpp"
#include "game/foundation/components/vfx/HoloBladeComponent.hpp"
#include "game/systems/vfx/GhostSystem.hpp"
#include "game/systems/vfx/HoloBladeRenderSystem.hpp"
#include "game/systems/vfx/SwordIntentVisualSystem.hpp"
#include "game/systems/vfx/TrailSystem.hpp"
#include "game/systems/world/FogOfWarSystem.hpp"
#include "game/systems/world/MapAffixCalculator.hpp"
#include "game/systems/world/MapAffixRegistry.hpp"
#include "game/systems/combat/MovementStanceSystem.hpp"
#include "game/systems/vfx/VFXSequencerSystem.hpp"
#include "game/application/persistence/SaveManager.hpp"

#include "game/application/ui/UIRenderer.hpp"
#include "core/utils/FmtBuffer.hpp"

#include <filesystem>

