"""
NoMoreDay General Asset Registry Generator
Purpose: Scans asset directories and generates C++ header files with static asset
         handles. Supports multiple asset types and custom namespaces.
Usage: python scripts/gen_asset_registries.py
"""
import argparse
import os
import re
from pathlib import Path


def generate_registry(name, root_dir, output_file, namespace, id_prefix):
    root_path = Path(root_dir)
    if not root_path.exists():
        print(f"Warning: Directory {root_dir} does not exist. Skipping {name}.")
        return

    lines = []
    lines.append("#pragma once")
    lines.append("// This file is auto-generated by scripts/gen_asset_registries.py")
    lines.append("// Do not modify this file directly. Run the script to regenerate.")
    lines.append("")
    lines.append('#include "engine/resource/AssetRegistry.hpp"')
    lines.append("#include <array>")
    lines.append("")
    lines.append("using namespace entt::literals;")
    lines.append("")
    lines.append(f"namespace {namespace} {{")
    lines.append("")

    total_assets = 0

    root_files = sorted(list(root_path.glob("*.png")))
    subdirs = sorted([d for d in root_path.iterdir() if d.is_dir()])

    categories = {}
    if root_files:
        categories["general"] = root_files

    for subdir in subdirs:
        files = sorted(list(subdir.glob("*.png")))
        if files:
            categories[subdir.name] = files

    for category, files in categories.items():
        safe_cat_name = category.replace(" ", "_").replace("-", "_").lower()
        lines.append(f"    namespace {safe_cat_name} {{")

        category_assets = []
        for file in files:
            stem = file.stem.replace(" ", "_").replace("-", "_")

            if safe_cat_name == "general":
                id_str = f"{id_prefix}{stem}"
            else:
                id_str = f"{id_prefix}{safe_cat_name}_{stem}"

            rel_path = file.as_posix()

            var_name = stem
            if var_name[0].isdigit():
                var_name = "_" + var_name

            lines.append(
                f'        inline constexpr TextureAsset {var_name} = {{ "{id_str}"_hs, "{rel_path}" }};'
            )
            category_assets.append(var_name)
            total_assets += 1

        lines.append("")
        lines.append(
            f"        constexpr std::array<const TextureAsset*, {len(category_assets)}> All = {{"
        )
        for i, v_name in enumerate(category_assets):
            sep = "," if i < len(category_assets) - 1 else ""
            lines.append(f"            &{v_name}{sep}")
        lines.append("        };")
        lines.append(f"    }} // namespace {safe_cat_name}")
        lines.append("")

    lines.append(f"}} // namespace {namespace}")

    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    with open(output_file, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"[{name}] Generated {output_file} with {total_assets} assets.")


def generate_skill_node_registry(
    name="SkillNodes",
    root_dir="assets/textures/skill_nodes",
    output_file="src/engine/resource/SkillNodeAssetRegistry.hpp",
    namespace="assets::skill_nodes",
):
    root_path = Path(root_dir)
    if not root_path.exists():
        print(f"Warning: Directory {root_dir} does not exist. Skipping {name}.")
        return

    pattern = re.compile(r"^skill_nodes_(\d+)(?:_.*)?\.png$", re.IGNORECASE)
    files = sorted(root_path.glob("skill_nodes_*.png"))
    entries = {}
    duplicate_ids = []

    for file in files:
        match = pattern.match(file.name)
        if not match:
            continue
        node_id = int(match.group(1))
        if node_id in entries:
            duplicate_ids.append(node_id)
            continue
        entries[node_id] = file

    if duplicate_ids:
        dup = ", ".join(str(v) for v in sorted(set(duplicate_ids)))
        print(f"Warning: Duplicate skill node icon IDs found (keeping first): {dup}")

    sorted_entries = sorted(entries.items(), key=lambda item: item[0])

    lines = []
    lines.append("#pragma once")
    lines.append("// This file is auto-generated by scripts/gen_asset_registries.py")
    lines.append("// Do not modify this file directly. Run the script to regenerate.")
    lines.append("")
    lines.append('#include "engine/resource/AssetRegistry.hpp"')
    lines.append("#include <array>")
    lines.append("#include <cstdint>")
    lines.append("")
    lines.append("using namespace entt::literals;")
    lines.append("")
    lines.append(f"namespace {namespace} {{")
    lines.append("")

    var_names = []
    for node_id, file in sorted_entries:
        var_name = f"node_{node_id}"
        id_key = f"skill_node_{node_id}"
        rel_path = file.as_posix()
        lines.append(
            f'    inline constexpr TextureAsset {var_name} = {{ "{id_key}"_hs, "{rel_path}" }};'
        )
        var_names.append((node_id, var_name))

    lines.append("")
    lines.append("    struct SkillNodeIconEntry {")
    lines.append("        uint32_t node_id;")
    lines.append("        entt::id_type icon_id;")
    lines.append("        const TextureAsset* asset;")
    lines.append("    };")
    lines.append("")

    lines.append(f"    constexpr std::array<const TextureAsset*, {len(var_names)}> All = {{")
    for index, (_, var_name) in enumerate(var_names):
        sep = "," if index < len(var_names) - 1 else ""
        lines.append(f"        &{var_name}{sep}")
    lines.append("    };")
    lines.append("")

    lines.append(f"    constexpr std::array<SkillNodeIconEntry, {len(var_names)}> ByNodeId = {{")
    for index, (node_id, var_name) in enumerate(var_names):
        sep = "," if index < len(var_names) - 1 else ""
        lines.append(f"        SkillNodeIconEntry{{{node_id}u, {var_name}.id, &{var_name}}}{sep}")
    lines.append("    };")
    lines.append("")

    lines.append("    inline constexpr entt::id_type FindIconId(uint32_t node_id) {")
    lines.append("        for (const auto& entry : ByNodeId) {")
    lines.append("            if (entry.node_id == node_id) {")
    lines.append("                return entry.icon_id;")
    lines.append("            }")
    lines.append("        }")
    lines.append("        return 0;")
    lines.append("    }")
    lines.append("")

    lines.append("    inline constexpr const TextureAsset* FindAsset(uint32_t node_id) {")
    lines.append("        for (const auto& entry : ByNodeId) {")
    lines.append("            if (entry.node_id == node_id) {")
    lines.append("                return entry.asset;")
    lines.append("            }")
    lines.append("        }")
    lines.append("        return nullptr;")
    lines.append("    }")
    lines.append("")
    lines.append(f"}} // namespace {namespace}")

    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    with open(output_file, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"[{name}] Generated {output_file} with {len(var_names)} assets.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate C++ asset registry headers.")
    parser.add_argument(
        "--skip-skill-nodes",
        action="store_true",
        help="Skip generation of SkillNodeAssetRegistry.hpp.",
    )
    args = parser.parse_args()

    registries = [
        {
            "name": "Equipment",
            "root_dir": "assets/textures/equipment",
            "output_file": "src/engine/resource/EquipmentAssetRegistry.hpp",
            "namespace": "assets::equipment",
            "id_prefix": "equip_",
        },
        {
            "name": "Runes",
            "root_dir": "assets/textures/icons/materials/runes",
            "output_file": "src/engine/resource/RuneAssetRegistry.hpp",
            "namespace": "assets::runes",
            "id_prefix": "rune_",
        },
        {
            "name": "Buffs",
            "root_dir": "assets/textures/icons/buffs",
            "output_file": "src/engine/resource/BuffAssetRegistry.hpp",
            "namespace": "assets::buffs",
            "id_prefix": "buff_",
        },
        {
            "name": "Monsters",
            "root_dir": "assets/textures/monster",
            "output_file": "src/engine/resource/MonsterAssetRegistry.hpp",
            "namespace": "assets::monsters",
            "id_prefix": "monster_",
        },
    ]

    for reg in registries:
        generate_registry(**reg)

    if not args.skip_skill_nodes:
        generate_skill_node_registry()
