import os
import sys
from pathlib import Path

def generate_header(root_dir, output_file):
    root_path = Path(root_dir)
    if not root_path.exists():
        print(f"Error: Directory {root_dir} does not exist.")
        sys.exit(1)

    lines = []
    lines.append("#pragma once")
    lines.append("// This file is auto-generated by scripts/gen_equipment_registry.py")
    lines.append("// Do not modify this file directly. Run the script to regenerate.")
    lines.append("")
    lines.append('#include "engine/resource/AssetRegistry.hpp"')
    lines.append("#include <array>")
    lines.append("#include <span>")
    lines.append("")
    lines.append("using namespace entt::literals;")
    lines.append("")
    lines.append("namespace assets::equipment {")
    lines.append("")

    # Map directory names to namespace/category names
    # Key: directory name, Value: (namespace name, list of assets)
    categories = {}

    for subdir in sorted(root_path.iterdir()):
        if subdir.is_dir():
            category = subdir.name
            assets = []
            
            for file in sorted(subdir.glob("*.png")):
                # Create a unique ID name: equip_<category>_<filename_stem>
                # Sanitize filename: replace spaces/dashes with underscores
                safe_name = file.stem.replace(" ", "_").replace("-", "_")
                id_str = f"equip_{category}_{safe_name}"
                
                # Relative path from project root. Assuming root_dir is relative to project root.
                # If root_dir is 'assets/textures/equipment', then file path is good.
                # file is a Path object, so strictly it's an absolute or relative path depending on how it was constructed.
                # We want the path relative to the project root.
                # Assuming the script is run from project root, or we handle it carefully.
                # Let's assume standard 'assets/textures/equipment/...' format.
                rel_path = file.as_posix()
                
                assets.append((id_str, rel_path))
            
            if assets:
                categories[category] = assets

    for category, assets in categories.items():
        lines.append(f"    namespace {category} {{")
        
        # Generate individual asset definitions
        for id_str, path in assets:
            var_name = id_str.split('_', 2)[-1].title().replace("_", "") # e.g. Sword001
            # Actually, using the id_str as variable name might be redundant if inside namespace.
            # But let's keep it simple. Let's use the file stem as the variable name, capitalized.
            var_name = Path(path).stem.replace(" ", "_").replace("-", "_")
            
            # Ensure variable name is valid C++ identifier
            if var_name[0].isdigit():
                var_name = "_" + var_name
                
            lines.append(f'        constexpr TextureAsset {var_name} = {{ "{id_str}"_hs, "{path}" }};')
        
        lines.append("")
        
        # Generate array of all assets in this category
        lines.append(f"        constexpr std::array<TextureAsset, {len(assets)}> All = {{")
        for i, (id_str, path) in enumerate(assets):
            var_name = Path(path).stem.replace(" ", "_").replace("-", "_")
            if var_name[0].isdigit():
                var_name = "_" + var_name
            
            separator = "," if i < len(assets) - 1 else ""
            lines.append(f"            {var_name}{separator}")
        lines.append("        };")
        
        lines.append("    }")
        lines.append("")

    lines.append("}") # End namespace assets::equipment

    with open(output_file, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    
    print(f"Successfully generated {output_file} with {sum(len(a) for a in categories.values())} assets.")

if __name__ == "__main__":
    # Default paths
    ASSET_DIR = "assets/textures/equipment"
    OUTPUT_FILE = "src/engine/resource/EquipmentAssetRegistry.hpp"
    
    generate_header(ASSET_DIR, OUTPUT_FILE)
