"""
NoMoreDay General Asset Registry Generator
Purpose: Scans asset directories and generates C++ header files with static asset handles.
         Supports multiple asset types (Equipment, Runes, etc.) and custom namespaces.
         Optimized for zero-copy using pointer arrays.
Usage: python scripts/gen_asset_registries.py
"""
import os
from pathlib import Path

def generate_registry(name, root_dir, output_file, namespace, id_prefix):
    root_path = Path(root_dir)
    if not root_path.exists():
        print(f"Warning: Directory {root_dir} does not exist. Skipping {name}.")
        return

    lines = []
    lines.append("#pragma once")
    lines.append("// This file is auto-generated by scripts/gen_asset_registries.py")
    lines.append("// Do not modify this file directly. Run the script to regenerate.")
    lines.append("")
    lines.append('#include "engine/resource/AssetRegistry.hpp"')
    lines.append("#include <array>")
    lines.append("")
    lines.append("using namespace entt::literals;")
    lines.append("")
    lines.append(f"namespace {namespace} {{")
    lines.append("")

    total_assets = 0
    
    root_files = sorted(list(root_path.glob("*.png")))
    subdirs = sorted([d for d in root_path.iterdir() if d.is_dir()])
    
    categories = {}
    if root_files:
        categories["general"] = root_files
        
    for subdir in subdirs:
        files = sorted(list(subdir.glob("*.png")))
        if files:
            categories[subdir.name] = files

    for category, files in categories.items():
        safe_cat_name = category.replace(" ", "_").replace("-", "_").lower()
        lines.append(f"    namespace {safe_cat_name} {{")
        
        category_assets = []
        for file in files:
            stem = file.stem.replace(" ", "_").replace("-", "_")
            
            if safe_cat_name == "general":
                id_str = f"{id_prefix}{stem}"
            else:
                id_str = f"{id_prefix}{safe_cat_name}_{stem}"
                
            rel_path = file.as_posix()
            
            var_name = stem
            if var_name[0].isdigit():
                var_name = "_" + var_name
                
            lines.append(f'        inline constexpr TextureAsset {var_name} = {{ "{id_str}"_hs, "{rel_path}" }};')
            category_assets.append(var_name)
            total_assets += 1
        
        lines.append("")
        # 优化点：使用指针数组避免结构体拷贝
        lines.append(f"        constexpr std::array<const TextureAsset*, {len(category_assets)}> All = {{")
        for i, v_name in enumerate(category_assets):
            sep = "," if i < len(category_assets) - 1 else ""
            lines.append(f"            &{v_name}{sep}")
        lines.append("        };")
        lines.append(f"    }} // namespace {safe_cat_name}")
        lines.append("")

    lines.append(f"}} // namespace {namespace}")

    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    with open(output_file, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    
    print(f"[{name}] Generated {output_file} with {total_assets} assets (Pointer Optimization).")

if __name__ == "__main__":
    registries = [
        {
            "name": "Equipment",
            "root_dir": "assets/textures/equipment",
            "output_file": "src/engine/resource/EquipmentAssetRegistry.hpp",
            "namespace": "assets::equipment",
            "id_prefix": "equip_"
        },
        {
            "name": "Runes",
            "root_dir": "assets/textures/icons/materials/runes",
            "output_file": "src/engine/resource/RuneAssetRegistry.hpp",
            "namespace": "assets::runes",
            "id_prefix": "rune_"
        }
        ,
        {
            "name": "Buffs",
            "root_dir": "assets/textures/icons/buffs",
            "output_file": "src/engine/resource/BuffAssetRegistry.hpp",
            "namespace": "assets::buffs",
            "id_prefix": "buff_"
        }
        ,
        {
            "name": "Monsters",
            "root_dir": "assets/textures/monster",
            "output_file": "src/engine/resource/MonsterAssetRegistry.hpp",
            "namespace": "assets::monsters",
            "id_prefix": "monster_"
        }
    ]
    
    for reg in registries:
        generate_registry(**reg)
